harfbuzz/harfbuzz

src/hb-common.cc, src/hb-icu.cc
When building Firefox's in-tree copy of harfbuzz, the following clang warning is reported for the (nonatomic!) implementation of `hb_atomic_ptr_cmpexch()` used in the Firefox OS simulator builds for OS X:
```
gfx/harfbuzz/src/hb-common.cc:348:5: warning: expression result unused [-Wunused-value]
```
=> Fix hb_atomic_ptr_cmpexch -Wunused-value warnings

src/hb-common.cc, src/hb-ft.cc, src/hb-shape.cc, src/hb-shaper.cc
Commit e9171af55cc6a402eb20db4ea74c86a0b1e70e85 marked some functions as static inline to suppress -Wunused-function warnings, but this inline trick doesn't always suppress the warnings. Plus, inline doesn't make sense for function pointers passed to `atexit()`. Instead, this PR wraps these functions in `#ifdef HB_USE_ATEXIT` because they are only called by `atexit()` `#ifdef HB_USE_ATEXIT`.
This change will fix some warnings when building Firefox's in-tree copy of Harfbuzz:
```
gfx/harfbuzz/src/hb-shape.cc:283:6 [-Wunused-function] unused function 'free_static_shaper_list'
gfx/harfbuzz/src/hb-shaper.cc:44:6 [-Wunused-function] unused function 'free_static_shapers'
```
=> Add #ifdef HB_USE_ATEXIT to fix -Wunused-function warnings

src/hb-ot-shape-complex-private.hh
This is to reflect the UTC decision to change the encoding model of
New Tai Lue from logical to visual to be similar to Thai, Lao, and
Tai Viet: http://www.unicode.org/L2/L2014/14250.htm#141-C26
The visual encoding is already the current practice of encoding New
Tai Lue on the web anyway:
http://www.unicode.org/L2/L2014/14195-newtailue.txt
Fixes behdad/harfbuzz#66.
=> Change New Tai Lue shaping engine from SEA to default

src/hb-private.hh
This code is C++ only. There isn't a single C++ compiler that fails to
understand the "inline" keyword, since it's required by C++98. Any
compiler older than C++98 is likely to choke on the template usage
further down, so this isn't necessary.
Moreover, the C++ standard says you cannot define macros.
[lib.macro.names] says "Nor shall such a translation unit define macros
for names lexically identical to keywords." -- technically, it's a
promise that the Standard Library headers won't do it, the wording means
that the entire translation unit won't do it, which implies no source
can do it.
MSVC complains about it:
fatal error C1189: #error : The C++ Standard Library forbids macroizing
keywords. Enable warning C4005 to find the forbidden macro.
Author: Thiago Macieira …
=> Fix build with MSVC on CE

src/hb-common.cc, src/hb-font.cc, src/hb-shape.cc
Without the element-type they will be getting garbage, at least with
Python.
=> [bindings] Fix *_from_string functions

test/shaping/hb_test_tools.py
On ArchLinux, /usr/bin/python is linked to python 3 so HarfBuzz `make check` is broken there.
This makes hb_test_tools.py compatible with python 3 while no breaking it on python 2.
Of course this is not all good, the change on Unicode.encode is hack and probably needs figuring out what it should be done with it.
=> Make hb_test_tools.py compatible with python 3

util/options.cc
Maybe the format and options are self-evident if you know enough about typography - but I certainly didn't when I got started.
New `--help-output`:
Output destination & format options:
--output-file=filename                Set output file-name (default: stdout)
--output-format=format                Set output format
Supported output formats are: ansi/png/svg/pdf/ps/eps
New `--help-output-syntax` (renamed from `--help-format` since otherwise we have too many definitions of the word "format"):
Output syntax:
text: [<glyph name or index>=<glyph cluster index within input>@<horizontal displacement>,<vertical displacement>+<horizontal advance>,<vertical advance>|...]
json: [{"g": <glyph name or index>, "ax": <horizontal advance>, "ay": <vertical advance>, "dx": <horizontal displacement>, "dy": …
=> Improve hb-shape/hb-view's help text w.r.t. output options 

src/hb-ot-tag.cc
The code is not standardized yet, but is used in some Google fonts.
=> Add OpenType language tag 'NAV ' for Navajo.

test/api/Makefile.am
When linking test-unicode statically it needs $(ICU_LIBS)
which contains all required flags.
Especially -lstdc++.
Fixes:
http://autobuild.buildroot.net/results/210/2107f9dfb39eeb6559fb4271c7af8b39aef521ca/
Signed-off-by: Romain Naour <romain.naour@openwide.fr>
=> fix static linking with icu-uc

docs/reference/harfbuzz-docs.xml, docs/usermanual-ch01.xml, docs/usermanual-ch02.xml, docs/usermanual-ch03.xml, docs/usermanual-ch04.xml, docs/usermanual-ch05.xml
This adds the chapters of user's manual into the main Docbook document processed by gtk-doc. Running "make" on the docs will now create one HTML/PDF file with two parts: the first part is the user manual and the second part is the API reference.
=> Use gtk-doc to build user's manual as well as reference

src/hb-ot-tag.cc, test/api/test-ot-tag.c
The BCP-47 registry defines a variant subtag "fonipa" that can be used
in combination with arbitrary other language tags. For example,
"rm-CH-fonipa-sursilv" indicates the Sursilvan dialect of Romansh
as used in Switzerland, transcribed used the International Phonetic
Alphabet.
http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
=> Handle language tags that indicate phonetic IPA transcription

src/hb-buffer-private.hh, src/hb-ot-layout-common-private.hh, src/hb-ot-layout-private.hh, src/hb-ot-map-private.hh, src/hb-ot-shape-complex-arabic.cc, src/hb-private.hh, util/ansi-print.cc, util/helper-cairo.cc, util/options.cc, util/options.hh
Hi,
Sorry for this, was not that good at git and retried a pull request as a result.
I have made some updates to the sources in util/, and also added an implementation of scalbn() and scalbnf() in a header that can be force-included by pre-2013 Visual Studio, so that the tools can be built under Visual Studio as well.
However, it also seems that some more changes are needed... on Visual Studio 2010 and 2008, things went fine, but on 2012 and later, I am getting C2057 (expected constant expression) errors for:
hb-ot-shape-normalize.cc
hb-ot-shape.cc
hb-ot-shape-fallback.cc
When they include hb-ot-layout-private.hh, the error was at line 67 (in the declaration of enum hb_ot_layout_glyph_props_flags_t)
and the C2057 error for hb-glib.cc when it included gnode.h (at line 43 of gnode.h, when …
=> Update the sources so they will compile under Visual Studio

src/hb-font.cc
To avoid triggering -Wmissing-braces; see https://bugzilla.mozilla.org/show_bug.cgi?id=1226175#c8
=> Add braces for subobject initializer in _hb_font_funcs_nil

src/hb-graphite2.cc
In pango, the font->y_scale is set to be -font->x_scale. hb-gr is not honouring that, or any other difference between x and y scale. This patch changes that so that the output allows for difference in scale values.
=> Fix y_scale problems in hb-gr

src/hb-blob.h, src/hb-buffer.h, src/hb-common.h, src/hb-coretext.h, src/hb-face.h, src/hb-font.h, src/hb-ft.h, src/hb-glib.h, src/hb-gobject-enums.h.tmpl, src/hb-gobject-structs.h, src/hb-graphite2.h, src/hb-icu.h, src/hb-ot-font.h, src/hb-ot-layout.h, src/hb-ot-shape.h, src/hb-ot-tag.h, src/hb-set.h, src/hb-shape-plan.h, src/hb-shape.h, src/hb-unicode.h, src/hb-uniscribe.h, src/hb-version.h.in, src/hb.h
Hi,
This is a follow-up PR from the discussions in PR #164 to use compiler directives to export symbols using compiler directives, which involves:
-Making sure config.h, if included, is included as the first thing in each source file under src/ (it is already so)
-Decorating the public symbols in the public headers with HB_EXTERN, which is extern by default.
-Add items in the autotools files to use visibility attributes to export symbols upon builds, by overriding HB_EXTERN.  This is similar to what is now done in GLib, GTK+, Clutter, etc.
-(In PR #164) add corresponding #defines for HB_EXTERN in the pre-configured config.h.win32.in to do the same for MSVC builds.
=> Enable use of compiler directives to export symbols

src/hb-directwrite.cc, src/hb-directwrite.h
More description on this mailing list [post](http://lists.freedesktop.org/archives/harfbuzz/2015-September/005062.html).
=> Add working but less prefect DirectWrite backend

src/hb-coretext.cc
Fixes a -Wunused-label warning when building harfbuzz with clang -Wall.
=> Remove unused `retry:` label.

src/hb-coretext.cc
The coretext_aat shaper delegates to the regular coretext_..._ensure() functions, so coretext_aat_..._ensure() functions defined by these macros are unused. The compiler warns about them, which in turn can confuse people to think that the coretext_aat_..._ensure() functions weren't called by accident.
=> Remove unused HB_SHAPER_DATA_ENSURE_DECLARE lines.

.travis.yml
Trusty has gtk-doc 1.20 which has better markdown support which should
fix some of the brokenness in the newly added documentation. The build
seems to be as fast as the current container-based build on Precise.
=> [travis] Try building on Trusty

src/hb-font.cc
When HB_DISABLE_DEPRECATED is defined, no code from hb-deprecated.h
should be used, even from within HB itself.
=> Fix build with HB_DISABLE_DEPRECATED

src/hb-directwrite.cc
With these changes, dwrite backend becomes much much useful. However there are some issues that AFAICT are dwrite internal bugs:
* "rlig" and perhaps other default enabled features can not be disabled, but from my tests neither it could be on uniscribe backend nor IE/Edge with font-feature-settings
* "هٔ" (and not other Arabic diacritics) has some rendering issue, which is consistent with Edge but not IE! Windows SDK's CustomLayout dwrite sample however doesn't have this issue so I don't reject the idea that there are some chances that some thing can be improved locally.
Our output:
Edge's:
Other than these, I don't see any other remained functional issue on this backend, other than features range and sideway/vertical text (which uniscribe backend also lacks that).
=> Improve DirectWrite backend

src/hb-private.hh
0475ef2f97e3035a2eea9a0f96031331e07e8e29 broke the build by using
vsnprintf(), which is not defined on Windows CE
=> Unbreak build on Windows CE

src/hb-directwrite.cc, src/hb-directwrite.h
This patch changes DirectWrite backend to use dwrite font file stream API instead falling back to Uniscribe suited solution, and also improves the backend to not create dwrite font object each shape time which have led to a significant performance boost on my tests. As the result of these changes the incorporated tricks to create HFONT objects are no longer needed on this backend so most of GDI backend shared codes are also removed.
In case no review would be given, I think this is ready to merge.
=> 	[dwrite] Use stream font loader instead GDI interop

src/hb-private.hh
I suppose clang in GCC compatibility mode has no problem with this as it probably defines `__GNUC__`
=> clang in MSVC mode doesn't like when we redefine __attribute__

src/hb-ft.cc
Prior to this change the function `FT_Error FT_Done_Face(FT_Face *)` was
called through a pointer with the signature `void (void *)` resulting in
undefined behaviour.
=> Fix unsafe cast of FT_Done_Face in hb_ft_{face,font}_create_referenced

src/hb-coretext.cc
Merge back of a committed on Chromium patch: https://codereview.chromium.org/2118263002/
=> [coretext] Speculative fix for CoreText nullptr access

configure.ac
Regression from: b424b6c372dfe4c0ed75a49761eb34a416819446.
=> Don’t build UCDN support when building with GLib

.travis.yml, src/hb-coretext.cc
Reveals another MacOS build breakage in the Core Text shaper.
=> [travis] Fix MacOS libtool issue

src/hb-ot-tag.cc, test/api/test-ot-tag.c
OpenType language system tag: `APPH`
https://www.microsoft.com/typography/otspec/languagetags.htm
IETF BCP47 variant tag: `fonnapa`
http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
=> Support Americanist Phonetic Notation

README, appveyor.yml, win32/generate-msvc.mak
The world is changed a lot since my last try for making this happen on #112, ragel added to msys2 ([by me](https://github.com/Alexpux/MINGW-packages/pull/645)), msys2 added on appveyor (I pushed this a bit also 😊) and since then both appveyor support for msys2 and msys2 itself perhaps are polished, @fanc999 added a nmake build project file for native win32 compiles, and I added DirectWrite backend to harfbuzz; and now it is the time for adding a deserving Windows CI to harfbuzz which compiles the project against MSVC compiler and gives us more confidence on harfbuzz development. And, [here](https://ci.appveyor.com/project/ebraminio/harfbuzz) is its result :)
Please take a look at it, thank you :)
=> [ci] Add Windows CI support, provided by AppVeyor

appveyor.yml
This runs hb testsuite on msys2 but not against MSVC compiler and the original Windows SDK is not reachable (AFAIK) for this setup so no dwrite backend can be compiled here, but as uniscribe itself is a dwrite wrapper nowadays, one can use this infrastructure to setup automatic dwrite and harbuzz shapers comparator.
=> [ci] Add msys2 build to CI and run its testsuite on Windows

src/hb-ot-layout.cc
According to comments in issue #305 broken GDEF tables lead
to incorrect rendering of Latin characters. Blacklisting
this font.
=> Blacklist Padauk 2.80 and 3.00

src/hb-coretext.cc
This seems to fix crash issues on 10.9.5 reported on Chrome, compare
crbug.com/549610
=> Do reconfigure the cascade list for Emoji font on OS X 10.9.5

src/hb-coretext.cc
Fix per [this](https://github.com/behdad/harfbuzz/commit/48677345281a93d8829dd37d0480a6062945416a#commitcomment-18945709) comment and the following.
=> [coretext] Use intended coretext version check logic

configure.ac
configure uses PKG_CHECK_MODULES to find graphite2. When pkg-config is not available (e.g., as when building statically within LibreOffice tree on OS X), PKG_CHECK_MODULES fails even though GRAPHITE2_CFLAGS and GRAPHITE2_LIBS are already defined by user. This patch makes configure use GRAPHITE2_CFLAGS to check for graphite2 usability when it is requested, even if PKG_CHECK_MODULES fails.
=> Allow building with graphite2 without pkg-config

appveyor.yml, win32/README.txt, win32/config-msvc.mak, win32/config.h.win32.in, win32/info-msvc.mak
Most of harfbuzz clients don't need uniscribe and directwrite support at all
as harfbuzz is a replacement for Uniscribe so Chromium and Firefox are using
harfbuzz without this on Windows.
This removal helps win32 nmake users which even don't use the backend to have
harfbuzz on a reduced binary size and libs count.
=> Make Uniscribe optional on nmake win32 builds

appveyor.yml, win32/config-msvc.mak, win32/detectenv-msvc.mak
This merges back @vlj's local patches of vcpkg for enabling [hb-freetype](https://github.com/Microsoft/vcpkg/pull/144) there. Lets apply them locally so they would be unnecessary when the next version of harfbuzz released.
=> [ci] Enable hb-freetype on Windows build tests

src/Makefile.sources, src/hb-ot-ebdt-table.hh, src/hb-ot-font.cc
hb_font_get_glyph_extents now works for color bitmap fonts. Currently
only font having index format 1 and image format 17 is supported.
=> Introduce get_extent support for color bitmap font.

win32/build-rules-msvc.mak, win32/config-msvc.mak, win32/create-lists-msvc.mak, win32/detectenv-msvc.mak, win32/generate-msvc.mak, win32/info-msvc.mak, win32/install.mak
Windows NMake builds with the ICU option should build with a builtin ICU, rather than building with UCDN and putting the ICU Unicode functions in a separate DLL. (As suggested by @khaledhosny and @fanc999 for my previous pull request.)
=> NMake ICU option builds with builtin ICU

src/hb-directwrite.cc, src/hb-directwrite.h
This is just created to start brain storming around the way we could have some initial justification API of at least directwrite backend on harfbuzz.
Ideally, from the start, we should think about how current harfbuzz can be developed in a way to provide a justification API that would be possible to be integrated with caching word shapers solutions where the "line" concept itself is less relevant...
Obviously harfbuzz API differs from paragraph like API such as DirectWrite and that's why integrating justification with the current state of harfbuzz and its clients usage needs some considerate and innovative thinking :)
=> [dwrite] Provide an experimental API for justification

src/hb-open-type-private.hh
The `DEFINE_SIZE_UNION` macro ultimately resolves to an `inline` function, in which the macro `ASSERT_STATIC` is expanded. In `ASSERT_STATIC`, the this pointer is used in a `typedef` expression. In the C++ standard, it is not completely specified exactly when the `this` pointer can be used in a constant expression. The `typedef` in `ASSERT_STATIC`, which is the basis for the custom static assertion, will not be accepted by the compiler if the array size is not a compile time constant. This can happen if the `this` pointer is not regarded as a constant.
With the GNU compilers the `this` pointer is allowed to be a constant in expressions when a `const` specifier is added to a member function of a class or a struct. With clang and the `-pedantic-errors` flag this is not the case. With the …
=> Compilation Error for ASSERT_STATIC on Some Compilers

src/hb-ot-layout.cc
From https://bugzilla.mozilla.org/show_bug.cgi?id=1279693.
=> Add Win7 version of himalaya.ttf to the GDEF table blacklist.

src/hb-ot-layout.cc
See https://bugzilla.mozilla.org/show_bug.cgi?id=1279925.
=> Add Win10 Anniversary Update version of Tahoma to GDEF blacklist.

util/hb-shape.cc
=> util: Add missing field initialisers in constructor

src/hb-font.cc
While it’s fine to call memcmp(x, 0, 0) in practice, the C99 standard
explicitly says that this is not allowed: even if the length is zero,
the pointer arguments must be valid.
http://stackoverflow.com/a/16363034
Coverity ID: 141178
Signed-off-by: Philip Withnall <withnall@endlessm.com>
=> hb-font: Fix a potentially undefined use of memcmp()

src/hb-graphite2.cc, src/hb-graphite2.h
See https://bugs.documentfoundation.org/show_bug.cgi?id=103403#c7
This is similar to commit 061105e for Core Text.
=> [graphite] Fix shaping with varying font sizes

src/hb-ot-layout.cc
In https://crbug.com/681813 another instance of Padauk was identified
triggering collapsed glyphs. Blacklist this version by running ttx from fonttools like
ttx -l Padauk.ttf
then add the values those to the list of blacklisted table lengths.
=> Blacklist another instance of Padauk

appveyor.yml
For whatever reason the env variables need to be the Windows way or they
end up being empty.
=> [ci] Fix msys2 build on AppVeyor

win32/config-msvc.mak, win32/detectenv-msvc.mak, win32/info-msvc.mak
Hi,
The check conditions in the NMake Makefiles need to be re-ordered so that we can ensure that the ICU items are indeed built into the HarfBuzz DLL when UCDN is enabled (and the build info shows as such).  This also updates the NMake Makefiles to detect that we are using Visual Studio 2017.
=> NMake Makefiles: Fix ICU builds

src/hb-ot-layout.cc
There are more broken versions of Tahoma out there on various Windows releases,
so we need to add them to our blacklist to avoid broken rendering.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1279925 for details.
=> Blacklist GDEF table in additional Tahoma versions.

CMakeLists.txt
Is this logic sounds right to you or it should be better be like "if (HB_HAVE_GLIB OR HB_HAVE_ICU)" and maybe HB_HAVE_CORETEXT and other OS provided APIs also?
(With having this in mind that the goal of this cmake is I think to be a simple but correct (thats why I removed -DHB_NO_UNICODE_FUNCS) and easily embeddable harfbuzz distribution that maybe replaces third party distributions like [these](https://www.google.com/search?q=cmake+harfbuzz), and our internal nmake win32 port also entirely someday, if @fanc999 agrees also, other than my personal goal that is making harfbuzz development itself easier with OS provided Xcode or VS tools and extra APIs/SDKs.)
=> [cmake] Remove NO_MT flag

CMakeLists.txt
Adopted from https://github.com/tamaskenez/harfbuzz-cmake/blob/master/CMakeLists.txt#L130-L150 which is originally is from harfuzz's configure.ac
=> [cmake] Add atomic ops availability detection

CMakeLists.txt
This seems is necessary for CMake's try_compile: http://public.kitware.com/pipermail/cmake/2010-May/037144.html
=> [cmake] Fix try compile link issues

CMakeLists.txt
See https://github.com/Microsoft/vcpkg/pull/943#issuecomment-294447460
=> [cmake] Remove HB_DISABLE_DEPRECATED as it seems needed for pango build

src/hb-common.cc, src/hb-ot-layout-gsubgpos-private.hh, src/hb-shape-plan.cc
clang's new -Wcomma compiler option warns about possible misuse of the
comma operator such as between two statements.
hb-common.cc:190:9 [-Wcomma] possible misuse of comma operator here
hb-ot-layout-gsubgpos-private.hh:345:30 [-Wcomma] possible misuse of
comma operator here
hb-shape-plan.cc:438:26 [-Wcomma] possible misuse of comma operator here
=> Fix clang -Wcomma warnings (#471)

src/hb-common.cc, src/hb-private.hh
If an application provides a malloc replacement through
hb_malloc_impl() it is important that it is used to allocate
everything, but the use of strdup() circumvents this and
causes system malloc() to be called instead. This pairs
badly with the custom hb_free_impl() being called later.
=> Avoid using strdup inside library.

src/hb-private.hh
And drop GCC 2 support (is that still relevant?)
I was [reading](https://chadaustin.me/2017/05/writing-a-really-really-fast-json-parser/) about [sajson](https://github.com/chadaustin/sajson/blob/3cb7ba16ea6ff9184878f6b77f2899d95c26d270/include/sajson.h#L39) and noticed this seems missing on harfbuzz, hope would be useful.
=> Support branch prediction helpers on clang compiles

CMakeLists.txt, src/hb-buffer.cc, src/hb-common.cc, src/hb-ot-font.cc, src/hb-ot-layout.cc, src/hb-ot-shape-complex-arabic-table.hh, src/hb-ot-shape-complex-arabic.cc, src/hb-ot-shape-complex-hangul.cc, src/hb-ot-shape-complex-indic-table.cc, src/hb-ot-shape-complex-indic.cc, src/hb-ot-shape-complex-myanmar.cc, src/hb-ot-shape-complex-thai.cc, src/hb-ot-shape-complex-use-table.cc, src/hb-unicode-private.hh, src/hb-utf-private.hh
This Is a part of porting harfbuz to vitasdk, I guess "src/hb-ot-layout.cc" change part, specially, needs more careful reviewing.
=> Fix arm-none-eabi build (fixes #451)

win32/README.txt, win32/build-rules-msvc.mak, win32/config-msvc.mak, win32/create-lists-msvc.mak, win32/generate-msvc.mak, win32/info-msvc.mak, win32/pc_base.py, win32/replace.py, win32/setup.py
Hi,
To ease development on Windows using NMake, I thought it might be a good idea to support the following:
1. Allow one to generate win32\config.h.win32 and src\hb-version.h, which are distributed in a release
tarball, from a GIT checkout.
2. Allow one to generate (and re-generate) the Ragel-generated .hh headers during the NMake build 
process.
This pull request attempts to address these issues by:
-Adding Python 2.7.x+/3.x scripts to generate win32\config.h.win32 and src\hb-version.h, which is not
distributed in a release tarball, for (1).  Note that replace.py and pc_base.py are common utility Python
scripts that are the same with the ones in GLib, and will also be re-used at a later stage for generating
the HarfBuzz pkg-config files, as Meson becomes prevalent in GNOME.
-Add rules to …
=> Win32/NMake builds: Support builds from GIT

src/hb-unicode-private.hh
Following the discoveries of @eroux, discussion in #417, this minimal change to 2f560ee44b7b08683e8e6955fe3b95187e8bda32 seems to fix the rendering of long Tibetan vowel U, fixes #417.
=> Fix for reordering of Tibetan vowel u

src/hb-coretext.cc
This partly fixes https://github.com/behdad/harfbuzz/issues/338.
Note that after kerning has been disabled (i.e. by setting `kCTKernAttributeName` to zero), CoreText doesn't let us enable it again for subsequent ranges of characters in the same attributed string.
https://developer.apple.com/documentation/coretext/kctkernattributename
> If this attribute is not present, standard kerning is used.
Removing the `kCTKernAttributeName` attribute does not seem to do anything: kerning stays disabled.
=> [coretext] Allow to disable kern

src/hb-buffer.cc
Change hb_buffer_diff to explicitly cast result of abs to unsigned when
comparing with position_fuzz to avoid unsafe signed/unsigned comparions
warnings on windows.
=> Fix signed/unsigned warning in hb_buffer_diff

src/hb-buffer.h, win32/Makefile.am, win32/README.txt, win32/generate-msvc.mak, win32/info-msvc.mak, win32/replace.py, win32/sed-enums-srcs.py
Hi,
When building the HarfBuzz tools, a recently-added symbol, hb_buffer_diff(), was not marked with HB_EXTERN, so that symbol was not exported from the HarfBuzz DLL when building with Visual Studio, causing tools builds to fail, so I attached a simple patch to fix this.
On the other hand, since GLib 2.53.4 and later had glib-mkenums ported to Python, we have to change how the enum sources for HarfBuzz-GObject is generated.  The issue is, since the cmd.exe (which NMake builds run on) do not supported shebang lines, we need to first test-run glib-mkenums with Python, and fall back to PERL if that fails (and bail out if that fails as well), and use a simple Python script or PERL one-liners to do the necessary string replacements in the generated enum sources depending on whether Python or …
=> Fix build of HarfBuzz tools and HarfBuzz-GObject on Visual Studio

CMakeLists.txt
Instead of searching for freetype using pkg-config, use the FindFreetype
feature of CMake. This allows for better integration with other projects
that make use of CMake.
Fixes https://github.com/behdad/harfbuzz/issues/518
=> CMakelists.txt fix for Freetype builds

src/hb-ot-shape-complex-indic.cc
This changes a few select uses of the term "cluster" in the comments that seem to refer to syllables rather than HarfBuzz internal-buffer clusters. Microsoft documentation uses "cluster" to refer to syllable-like multi-character runs that need to be shaped. 
Using syllable may be better here, to avoid confusion between MS and HB terminology.
Also stumbled across two minor typos not likely of real significance.
=> Replacing 'cluster' with 'syllable' when comments describe certain Indic shaping behavior

src/hb-icu.cc
The new unorm2_normalize has been public API since ICU 4.4, while
the old unorm_normalize has been deprecated since ICU 56.
Now, beginning with ICU 60, unorm_normalize will also be annotated
U_DEPRECATED and trigger the compiler -Wdeprecated-declarations warning.
=> Switch from ICU deprecated unorm_normalize to unorm2_normalize.

test/shaping/record-test.sh
`--directory` doesn’t work in the macOS version of mktemp. `-d` is more portable.
=> Use `mktemp -d` instead of `mktemp --directory`

src/hb-ot-font.cc, src/hb-ot-post-table.hh, test/shaping/tests/fallback-positioning.tests, test/shaping/tests/indic-syllable.tests, test/shaping/tests/use.tests
Turns out we already have support for “post” table, it just needed to be activated and put in use.
Might not be the best way to handle this, as I don’t really think I totally understand how parsing tables in HarfBuzz works.
=> [ot-font] Implement reading glyph names

src/hb-set-private.hh, test/api/test-set.c
This fixes the bug that led to confusion about the sets involved in issue 579, because `hb_set_next` was returning incorrect results, leading to wrongly-printed set contents.
The breakage occurs when `hb_set_t::next` needs to cross a page boundary, because the new declaration of `j` in the inner loop here in `hb_set_t::page_t::next` goes out of scope when we exit with `goto found`, and we then return a result based on `j == ELT_BITS` from the termination of the preceding loop.
=> Bugfix for iteration with hb_set_next, and add failing case to hb_set tests

src/hb-set-private.hh, test/api/test-set.c
The inputs I reported in this issue were incomplete, as it turns out -- they were derived by using hb_set_next to enumerate the contents of the sets in question, but that was itself broken! So here's a complete example that fails with the 1.6.2 implementation of hb_set (but passed previously).
Obviously, this can't be merged right now as it'll make the test fail.
=> Extend hb_set test for issue 579, and fix broken hb_set operations

test/shaping/record-test.sh
record-test.sh subsets the input based on the characters in the input text. pyftsubset only includes glyphs for the characters in the input text, so if the test is of a string where OpenType inserts a dotted circle, the subsetted font will not include a dotted circle. The solution is to use `--glyphs` to tell pyftsubset to include all the glyphs HarfBuzz emits for the input text.
=> Include all relevant glyphs when subsetting a font for testing

.circleci/config.yml, README
Part of #589
@behdad, you should login into http://circleci.com and enable it for harfbuzz but before that, do you have any idea why this is happening on some compilers? Have a look at [this](https://circleci.com/gh/ebraminio/harfbuzz/tree/master) for more info.
```
[31/41] Building CXX object CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o
FAILED: CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o 
/usr/arm-linux-androideabi/bin/arm-linux-androideabi-g++ --sysroot=/usr/arm-linux-androideabi/sysroot  -DHAVE_FALLBACK -DHAVE_INTEL_ATOMIC_PRIMITIVES -DHAVE_OT -DHAVE_UCDN -I../src -Isrc -I../src/hb-ucdn  -MD -MT CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o -MF CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o.d -o CMakeFiles/harfbuzz.dir/src/hb-ot-font.cc.o -c ../src/hb-ot-font.cc
In file included from …
```
=> [ci] Add CircleCI for cross-compiling

.circleci/config.yml
fixes #589, newer versions of FreeBSD (already is 11.2) are using clang instead gcc but this is FreeBSD9 which uses gcc4 so it is testing gcc 4 in addition to FreeBSD headers compatibility (hopefully).
=> [ci] Add FreeBSD

.circleci/config.yml
As https://github.com/behdad/harfbuzz/issues/589#issuecomment-341161406 I thought adding a fedora based compile also would be nice. Unlike others, this does `make check` also.
=> [ci] Add Fedora builder

.circleci/config.yml
ArchLinux uses python3 as its default python and always ships brand new compilers and such so it would be interesting to test harfbuzz against it also, see #93 as an ArchLinux specific also that testing harfbuzz could be useful on it.
Also more of harfbuzz backends enabled on Fedora.
=> [ci] Add ArchLinux

NEWS, src/hb-ot-shape-complex-indic.cc, src/hb-ot-shape-fallback.cc
Found using `codespell -i 3 -w -I '../harf-whitelist.txt'`
whereas the whitelist contents were:
```
beng
iff
pres
ot
te
teh
```
=> Trivial typos

src/hb-graphite2.cc
This fixes cluster width problems where two clusters merge due to reordering as in the sequence 092A 0930 094D 0915 093E 092A in AnnapurnaSIL.
=> Fix graphite intergration reordered clusters problem

src/hb-coretext.cc, src/hb-coretext.h
Uncompiled, untested.
Fixes https://github.com/harfbuzz/harfbuzz/issues/628
New API:
hb_coretext_font_create()
=> [coretext] Add hb_coretext_font_create()

configure.ac, src/hb-ft.cc, util/helper-cairo.cc
FT_Set_Var_Blend_Coordinates() is not available when "Multiple Master font interface" is disabled in freetype's modules.cfg
=> [hb-ft] Fix build when Multiple Master font support is disabled in freetype

src/hb-ot-tag.cc
This makes "x-hbotpap0" etc. work.
=> Allow digits in language system tags

src/hb-ot-shape-complex-indic.cc
Replaces occurrences of "pre-base reordering" with "pre-base-reordering" in the comments.
There is a potential ambiguity for new readers in "pre-bse reordering" (one hyphen); it could be read as "pre-base, reordering" — i.e., a character in pre-base position that gets reordered.
The term actually refers to a characters **in** a post-base position that gets reordered **to** a pre-base position, so "pre-base-reordering" is somewhat clearer.
=> Indic: always hyphenate "pre-base-reordering," to reduce ambiguity.

src/hb-ot-shape-complex-arabic-fallback.hh
This pull request fixes #655 
There's a compiler bug in xlC 12 & 13 which prevents xlC from selecting the correct version of the overloaded 'cmp(..)' method from struct IntType (defined in hb-open-type-private.hh) in the two functions  'arabic_fallback_synthesize_lookup_single(..)' and 'arabic_fallback_synthesize_lookup_ligature(..)' (defined in hb-ot-shape-complex-arabic-fallback.hh).
The fix is quite easy. Instead of writing:
```
hb_stable_sort (&glyphs[0], num_glyphs, OT::GlyphID::cmp, &substitutes[0]);
```
we can help the compiler by casting 'OT::GlyphID::cmp' to the correct overloaded version of 'cmp(..'):
```
hb_stable_sort (&glyphs[0], num_glyphs, (int(*)(const OT::GlyphID*, const OT::GlyphID *)) OT::GlyphID::cmp, &substitutes[0]);
```
This issue has been fixed in the OpenJDK …
=> HarfBuzz 1.7.1 and later don't compile on AIX with xlC (#655)

configure.ac
fix iOS compilation when using CoreText, missing CoreFoundation symbols:
```
Undefined symbols for architecture armv7:
"_CFArrayAppendValue", referenced from:
__hb_coretext_shape in libharfbuzz_la-hb-coretext.o
"_CFArrayCreate", referenced from:
__hb_coretext_shaper_font_data_create in libharfbuzz_la-hb-coretext.o
"_CFArrayCreateMutable", referenced from:
__hb_coretext_shape in libharfbuzz_la-hb-coretext.o
"_CFArrayGetCount", referenced from:
__hb_coretext_shape in libharfbuzz_la-hb-coretext.o
"_CFArrayGetValueAtIndex", referenced from:
__hb_coretext_shape in libharfbuzz_la-hb-coretext.o
"_CFAttributedStringCreateMutable", referenced from:
__hb_coretext_shape in libharfbuzz_la-hb-coretext.o
"_CFAttributedStringRemoveAttribute", referenced from:
__hb_coretext_shape in …
```
=> link with CoreFoundation when using CoreText

CMakeLists.txt
Due to how ninja runs clang and gcc, it doesn't colorize the output
like make does. This forces color output in this situation.
=> [cmake] Colorize output when using cmake + ninja.

src/hb-atomic-private.hh
In macOS 10.12, the `OSMemoryBarrier` and related APIs were deprecated
in favor of using `std::atomic`. On the way to supporting `std::atomic`,
we can favor using the "Intel primitives" which are also available on
macOS.
=> atomics: Favor compiler primitives over macOS APIs.

src/hb-private.hh
Closes #693 
This fixes the build on Cygwin.
=> Move the #define of _GNU_SOURCE to the top of hb-private.hh

src/hb-blob.cc
FreeBSD libc assumes setting `_POSIX_C_SOURCE` to any POSIX version released before 1999 means disabling C99 support, which causes compilation error because many functions are not declared.
```
CXX      libharfbuzz_la-hb-blob.lo
In file included from /home/lantw44/gnome/source/harfbuzz/src/hb-blob.cc:32:
In file included from /home/lantw44/gnome/source/harfbuzz/src/hb-private.hh:43:
/usr/include/c++/v1/math.h:640:39: error: use of undeclared identifier 'fabsf'; did you mean 'fabs'?
abs(float __lcpp_x) _NOEXCEPT {return fabsf(__lcpp_x);}
^
/usr/include/math.h:255:8: note: 'fabs' declared here
double  fabs(double) __pure2;
^
In file included from /home/lantw44/gnome/source/harfbuzz/src/hb-blob.cc:32:
In file included from /home/lantw44/gnome/source/harfbuzz/src/hb-private.hh:43: …
```
=> Fix compilation error caused by  _POSIX_C_SOURCE on FreeBSD

CMakeLists.txt
This is a trivial change that fixes compilation in CMake 2.8.
The "SOURCES" option to `try_compile` is not available in the stated minimum CMake version 2.8.  However, it is only necessary if more than once source file needs to be compiled, which isn't the case here.
=> Fix for CMake 3.0 and below

test/shaping/README.md, test/shaping/record-test.sh
Since the test directories were reorganized a week ago, record-test.sh was out of date. Maybe there should be a continuous integration test for the test framework. :)
=> Update record-test.sh to the new directory layout

.circleci/config.yml, CMakeLists.txt, configure.ac, src/Makefile.am, src/check-defs.sh, src/gen-def.py
With this all the tests will be available on cmake <s>but it needs some work before the merge like passing file names from make and cmake instead finding them on python script</s>, PTAL.
@behdad, please have a look, are you ok with name of the new script, gen-def.py or what would be better?
=> Improve avoiding C++ linkage, definition creation and tests

src/hb-common.cc
I just stumbled on this ancient script from Iraq. Apparently HarfBuzz thinks it's left-to-right, but it turns out:
"Hatran is written from right to left horizontally"
http://www.unicode.org/L2/L2012/12312-n4324-hatran.pdf
This script was added with Unicode 8.0.
Also this spreadsheet (referenced in an inline comment in the source code) has it as RTL: http://goo.gl/x9ilM
=> Hatran script is right-to-left

CMakeLists.txt
As https://github.com/harfbuzz/harfbuzz/issues/723#issuecomment-360295500 no longer hacks like -D__CORRECT_ISO_CPP11_MATH_H_PROTO_FP hopefully.
=> [cmake] Use -fvisibility-inlines-hidden instead

src/hb-ot-kern-table.hh
Issue originally reported at http://cppfiles.com/chromium.txt .
This fixes what appears to be a copy - paste issue which causes both
KernSubTableFormat2::rightClassTable and the 'right' argument to
KernSubTableFormat2::get_kerning to go unused.
=> Use KernSubTableFormat2::rightClassTable

.travis.yml, src/check-defs.sh
Travis builds on macOS have been failing lately because check-defs.sh does not fully ignore the prefix “_” when comparing symbol lists. When the test fails, Travis does not print the log, because it tries to run find with a syntax that does not work on macOS.
=> Fix Travis build on macOS

src/hb-coretext.cc
In `reference_table`, if the data is empty and we return early,
we still need to release the data object.
=> [coretext] Fix memory leak.

src/hb-ot-layout.cc
If the `calloc` for `gsub_accels` or `gpos_accels` fails, then the
unlikely branch afterwards can be taken, which frees up the
`hb_ot_layout_t`, but since those fields can now be `nullptr`, then
we don't want to dereference them.
=> [ot-layout] Fix nullptr dereference.

src/hb-ot-shape-complex-use-machine.rl
As discussed in https://github.com/harfbuzz/harfbuzz/issues/542
For Newa (and any Indic 3 scripts in the future) ZWJ is needed for virama terminated clusters.
=> Allow optional ZWJ in virama terminated cluster

src/hb-private.hh
The atexit() man page indicates that this is expected to behave
in the expected way on unloading of shared libraries.
=> Enable use of atexit() on macOS and related platforms.

configure.ac
Correctly show if building documentation is enabled or not in configure summary.
Fixes https://github.com/harfbuzz/harfbuzz/issues/741
=> Correctly show documentation build status

src/hb-buffer.cc
Clang complains about this,
https://github.com/harfbuzz/harfbuzz/commit/54e6efadd6a30587736858d3fb497ed4e5e5f252#diff-d4fe75bc0a3a13a3f3bf3e0f810de372
And this is this what it could mean I guess.
https://travis-ci.org/harfbuzz/harfbuzz/jobs/337930723#L2218
=> Fix hb-buffer logic error

src/hb-buffer.h
HB_GLYPH_FLAG_UNSAFE_TO_BREAK means that the glyph with this flag is somehow affected by the previous logical glyph (the previous index in the buffer if ltr and the next index if the buffer is rtl). If these two glyphs are separated by a break (line or otherwise) then the underlying text should be re-shaped on both sides up to corresponding position in the text of some glyph not marked with this flag.
=> Documentation for HB_GLYPH_FLAG_UNSAFE_TO_BREAK.

CMakeLists.txt, src/Makefile.am, src/check-defs.sh, src/check-libstdc++.sh, src/check-symbols.sh, src/hb-subset-glyf.cc, src/hb-subset-glyf.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh, src/hb-subset.cc, src/hb-ucdn/Makefile.am
Fixes #767.
TODO:
* src/check-defs.sh
* libharfbuzz_gobject_la_LINK = $(libharfbuzz_la_LINK)
* Separate -icu and -subset on CMake also.
=> Fix symbol exporting and libstdc++ linkage of hb-subset

src/hb-subset-plan.cc
Fixes #774 and hopefully brings back some of the bots.
=> Initialize bad_indices on hb-subset

src/hb-private.hh
Visual C++ compiler doesn't define macros __OPTIMIZE__  when optimizations enabled
=> Remove checking macros __OPTIMIZE__ for MSVC

src/hb-buffer-private.hh, src/hb-coretext.cc, src/hb-directwrite.cc, src/hb-graphite2.cc, src/hb-uniscribe.cc
=> Do not mark the first glyph as unsafe to break

CMakeLists.txt, src/dev-run.sh, test/api/CMakeLists.txt
Have a look, uses cmake/ninja/fswatch. I guess we can add more features or anything useful to it. Also feel free to suggest anything about the naming or so.
I tested it with: `src/dev-run.sh "/Library/Fonts/Tahoma.ttf" سََََََََََلام` (don't run it from src/ folder, run it from root of the project, that perhaps should checked by the script also)
Caveat: Doesn't support space on font name and has not a trivial fix apparently other than double quoting.
https://twitter.com/ebraminio/status/965333488969965568
=> Add a continuous builder using fswatch

src/Makefile.sources, src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout.cc, src/hb-ot-layout-private.hh
Doc: https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6kerx.html
Far far from anything useful... based on `hb-ot-kern-table.hh` stock on implementing KerxSubTableFormat0, perhaps you should give me a hand, and no format 4 and 6 and `Glyph Coverage Tables` yet. Not sure if this has anything useful, but at least it builds and as there is no AAT vs OT duality (AFAIK), lots of unnecessary things are cleaned and tweaked some of the types that are different between the two (Offset to LOffset, uint16 to uint32) whenever I could.
=> [aat] First dig on 'kerx'

src/Makefile.sources, src/hb-aat-layout-trak-table.hh, src/hb-aat-layout.cc, src/hb-ot-layout-private.hh
Sorry that this is not that useful and obviously is erroneous, be careful when developing it. Based on Apple's [specification](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6trak.html) and [trak.js](https://github.com/devongovett/fontkit/blob/aat-kern/src/tables/trak.js)
=> [aat] First dig on 'trak'

src/hb-ot-cmap-table.hh
Fixes Chromium Android builds, compare
https://ci.chromium.org/buildbot/tryserver.chromium.android/linux_android_rel_ng/491787
=> Use %zu format specifier for size_t to fix cross platform build

src/hb-ot-glyf-table.hh, src/hb-ot-maxp-table.hh, src/hb-subset.cc
Move glyf subsetting code out of hb-subset.cc and into hb-ot-glyf-table.hh to be consistent with the other table subsetting code. Switch glyf to use hb_blob_copy_writable_or_fail instead of malloc.
=> Clean up of glyf subsetting.

src/hb-subset-glyf.cc
Ensure we are not writing out of bounds during glyf subsetting.
=> [subset] Sanity check memory writes during glyph subsetting.

util/options.cc, util/options.hh
I should have missed something...
$ build/hb-shape --font-ptem 4 HelveticaNeueDeskInterface.ttc Hi
[H=0+722|I=1+222]
$ build/hb-shape --font-ptem 10 HelveticaNeueDeskInterface.ttc Hi
[H=0+722|I=1+221]
So it has some effect, it seems.
=> [util] Implement ppem/ptem on hb-{shape,view}

src/hb-open-file-private.hh, src/hb-ot-head-table.hh, src/hb-subset.cc
Test still fails, because we do not serialize tables in the same
order that fonttools subsetter does.
=> [subset] Caclculate head table checksum adjustment

src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout-private.hh, src/hb-aat-layout-trak-table.hh, src/hb-aat-layout.cc, src/hb-open-type-private.hh, src/hb-ot-layout-private.hh, src/hb-ot-layout.cc, src/hb-ot-shape.cc
Not to forget (may or may not on this issue):
* SANITZE, SANITZIE, SANTIZE
* > Assign the UnsizedArrays to interim variables before indexing them
* > bound-check
* > Also, you need a track number, which defaults to 0. We should add API on the buffer or shape later to set traking / letter-spacing.
* > We should possibly auto-disable ligatures if traking is set.
(`ff` on Helvetica Neue)
* #808
=> [aat] Implement trak logic

.travis.yml, src/hb-aat-layout.cc, test/api/test-set.c
Hopefully to fix #807, if Chromium's builders have that mercy that our strict clang bots have! (interestingly no change was needed on gcc builders even with the addition of the flag)
=> Add -Werror=unused-function check to Travis

src/Makefile.sources, src/hb-ot-color.cc, src/hb-ot-color.h, src/hb-ot-colr-table.hh, src/hb-ot-cpal-table.hh, src/hb-ot-layout-private.hh, src/hb-ot-layout.cc
Now that we have CPAL table, lets have COLR also, hopefully we can reach to both and providing things tests, public API and such on the next release. I like to port my color emoji code to it https://github.com/ebraminio/glcourse/blob/master/emojidump.cc someday on that process hopefully I can test and make sure everything works as intended also.
=> [colr] Implement

src/hb-ot-colr-table.hh, src/hb-ot-cpal-table.hh
It works with something like this:
```C
const OT::COLR &colr = _get_colr(font->face);
const OT::CPAL &cpal = _get_cpal(font->face);
FT_Face ftface = hb_ft_font_get_face (font);
for (unsigned int I = 0; I < buffer->len; ++i)
{
hb_codepoint_t code_point = buffer->info[i].codepoint;
FT_Load_Glyph (ftface, code_point, FT_LOAD_DEFAULT);
FT_GlyphSlot slot = ftface->glyph;
FT_Render_Glyph (slot, FT_RENDER_MODE_NORMAL);
int width = slot->bitmap.width;
int height = slot->bitmap.rows;
int left = slot->bitmap_left;
int top = slot->bitmap_top;
unsigned char* image = (unsigned char*) calloc (width * height * 16, sizeof(char));
unsigned int first_layer_index, num_layers;
if (colr.get_base_glyph_record (code_point, first_layer_index, num_layers))
{
for (unsigned int j = 0; j < num_layers; ++j)
{ …
```
=> [COLR/CPAL] Provide enough helpers for rasterization

src/Makefile.sources, src/hb-ot-color-sbix-table.hh, src/hb-ot-layout.cc
PTAL, https://github.com/symbolset/ss-emoji-beta/blob/master/ss-emoji-apple.ttf or https://github.com/devongovett/fontkit/blob/master/test/data/ss-emoji/ss-emoji-apple.ttf can be used for the testing whenever we decide about a public API I guess
=> [sbix] Implementation

src/Makefile.sources, src/hb-ot-color-svg-table.hh, src/hb-ot-layout.cc
Works on https://github.com/symbolset/ss-emoji-beta/blob/master/ss-emoji-adobe-mozilla.ttf and I was able to dump the SVGs inside the font with it!
=> [SVG ] Implementation

CMakeLists.txt
This change makes sure that non-MSVC builds using CMake properly hide
non-exported functions.
We haven't reached symbol-parity yet though:
Autotools symbol list on my machine: https://paste.fedoraproject.org/paste/VndugIDtEGsXj~UDZJitzw
CMake build symbol list: https://paste.fedoraproject.org/paste/LmK7tRcdWAYAg-Y~BGq1Rw
=> CMake: hide symbols by default on non-MSVC, define export attribute

CMakeLists.txt
but keep use of cmake idiomatic way of making inlines hidden. Partially reverts #886 but keeps the good part.
=> [cmake] Don't hide symbols by default

CMakeLists.txt
Fix for reported issue 883 - [Build Fails on QNX](https://github.com/harfbuzz/harfbuzz/issues/883)
=> Add compiler check for -Bsymbolic-functions

src/Makefile.am, src/gen-def.py
Reverts the hack happened here #885 with @anthrotype help. Thanks!
=> Appropriate fix for msys2 bot fail on gen-def.py

appveyor.yml, src/hb-directwrite.cc
#884 fixed most of the GCC compile issues, this enables it on msys2 bots.
<s>The way I am checking validity of headers may don't seem good. The issue is msys2 and mingw-w64 headers are not complete and I am checking that using that `#ifdef`. I proposed a fix to upstream also but that can take years to have here so I am applying this workaround.</s> this now just downloads the needed header
Also applied https://github.com/harfbuzz/harfbuzz/pull/884#discussion_r174845362 now that it doesn't have any other hb-directwrite.cc perhaps should be separated but don't know if worths to
=> [dwrite] Use new again and enable the build on msys2 bots

src/hb-directwrite.cc
Not sure about this but now that we need to have 'new/delete' for interfaces initialization, I guess replacing the rest with the rest is not a bad idea.
=> [dwrite] Replace rest of 'malloc/free's with 'new/delete'

CMakeLists.txt
Tested with `cmake -E make_directory build && cmake -E chdir build cmake .. && cmake --build build --config Release` and `cmake -E remove_directory build && cmake -E make_directory build && cmake -E chdir build cmake -DBUILD_SHARED_LIBS=ON .. && cmake --build build --config Release`
=> CMake: Policy 0063 must be enabled to have hidden inline visibility on static builds

.circleci/config.yml
Apple GCC 4.2 is somehow last of its kind as Apple was shipping this GCC build along the OS but after that migrated to llvm's clang. As a 32bit GCC 4.2 bot was needed for https://github.com/harfbuzz/harfbuzz/issues/901#issuecomment-375925315 I went for it. I checked that It reproduces the issue #901 also
=> [ci] Add a build only apple-gcc-4.2 i686 bot

src/Makefile.sources, src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout-ltag-table.hh, src/hb-aat-layout-morx-table.hh, src/hb-aat-layout-trak-table.hh, src/hb-aat-layout.cc
Related to #905. Here is the list of the fonts and their tag numbers and values, we don't need deferring tags sanitization to runtime as they are very low, 
```
1 en /Library/Fonts/Kefa.ttc
1 pl /Library/Fonts/BigCaslon.ttf
1 fa /Library/Fonts/Al Nile.ttc
1 fa /Library/Fonts/Muna.ttc
1 fa /Library/Fonts/Farah.ttc
1 fa /Library/Fonts/Diwan Kufi.ttc
1 zh-Hant /Library/Fonts/Skia.ttf
1 fa /Library/Fonts/Beirut.ttc
1 fa /Library/Fonts/Sana.ttc
1 fa /Library/Fonts/Al Tarikh.ttc
```
Which matches `ftxdumperfuser` dump results also.
=> [aat/ltag] Implement the table parsing

util/options.cc
I have often removed the last code point from the argument to `--unicodes` without removing the preceding separator (e.g. `65,67` to `65,`), resulting in an error.
=> Allow trailing non-numeric characters in --unicodes

CMakeLists.txt, src/Makefile.am, src/dump-emoji.cc, src/hb-ot-color-cbdt-table.hh, src/hb-ot-color-sbix-table.hh, src/hb-ot-color-svg-table.hh
The plan is to have some opinionated but private developed tool to dump all the glyphs using the original format or well formed SVGs. Currently the only `sbix` is somehow OK but that also doesn't do runtime sanitizing.
=> Implement an internal emojis dumper tool

Makefile.am, README.python.md, README.wine.md, RELEASING.md
Add how to build and run harfbuzz using mingw64-i686 compiler and Wine on Linux and macOS.
Convert REAME.python to markdown
Mention the REPLACEME convention on REALESING.md.
=> Add README.wine.md and touch some other docs

src/gen-arabic-table.py, src/gen-indic-table.py, src/gen-use-table.py, test/shaping/hb_test_tools.py
This is tested on both py2 and py3. There is no difference between the previous version and the current on python2 but on python3 currently there is just a minor difference. This time I changed shebangs for my python3 testing. The generated files on this commit are by python2 by running this command,
`make -Cbuild/src arabic-table indic-table use-table && mv build/src/*.{cc,hh} src/`
for my out-of-tree build.
=> Actual py3 compatibility making on gen-* scripts

src/Makefile.sources, src/hb-aat-gcid-table.hh, src/hb-aat-layout.cc
Fixes #914. The implementation is manually tested with Sierra's Apple Gothic, the table is removed from High Sierra however and no other macOS font has it. Unlike other implemented tables probably useful only for historical reasons :)
=> [aat] Implement gcid table parsing

src/hb-coretext.cc
Hi, I'm the maintainer of harfbuzz in MacPorts. I was recently asked to enable CoreText support for harfbuzz in MacPorts. In attempting to do so, I found that although CoreText was introduced in Mac OS X 10.5, harfbuzz's CoreText support doesn't work there:
```
hb-coretext.cc: In function “const __CTFont* create_ct_font(CGFont*, CGFloat)”:
hb-coretext.cc:171: error: “kCTFontUIFontSystem” was not declared in this scope
hb-coretext.cc:173: error: “kCTFontUIFontEmphasizedSystem” was not declared in this scope
hb-coretext.cc:209: error: “kCTFontURLAttribute” was not declared in this scope
hb-coretext.cc: In function “hb_bool_t _hb_coretext_shape(hb_shape_plan_t*, hb_font_t*, hb_buffer_t*, const hb_feature_t*, unsigned int)”:
hb-coretext.cc:948: error: “kCTTypesetterOptionForcedEmbeddingLevel” …
```
=> Fix build with CoreText on OS X 10.7 and earlier

src/hb-private.hh
Obviously one can use a newer NDK for building an updated HarfBuzz
instead that now pretty old version however I am concerned if that
version checking is working with clang that is used with the newer
NDK versions.
=> Always enable atexit on Android

src/hb-common.h, src/hb-private.hh, src/hb-ucdn/ucdn.h
Closes #978 (hopefully) by cherrypicking some parts of the attached patch.
From the original patch,
```
* Revert "Remove some really old cruft".
* Add a simple macro for round().
* Guard use of BitScan intrinsics with appropriate ifdefs.
```
[The referenced change](https://github.com/harfbuzz/harfbuzz/commit/cbec0cd65e1787b20ea55dd5583a7444938bd381
), I didn't revert all of it however.
For the future reference, we are not going to actively support such compilers (specially as they are not tested by our bots) but patches are accepted as long as they don't disturb the project much.
=> Reinstate support for Visual Studio 2005

src/hb-open-type-private.hh
Splitted from #875.
Maybe better to have `to_double` and `set_double` instead?
Btw what is the difference of shortFrac and F2Dot14 on https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html ? It should be same as [OT avar](https://docs.microsoft.com/en-us/typography/opentype/spec/avar) used that on the places [AAT avar](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6avar.html) has used them but still am wondering why they have that also.
=> Implement to_float and set_float of F2DOT14

src/Makefile.am, src/dump-fon.cc
Hopefully eventually to workaround #681, useful links,
* https://github.com/wine-mirror/wine/blob/master/tools/sfnt2fon/sfnt2fon.c
* https://github.com/andrewshadura/gbdfed/blob/master/bdffnt.c
* https://anolis.codeplex.com/
* https://github.com/ebraminio/PDB-Downloader/blob/master/main.cc
* https://web.archive.org/web/20120215123301/http://support.microsoft.com/kb/65123
* http://www.csn.ul.ie/~caolan/publink/winresdump/winresdump/doc/resfmt.txt
* https://github.com/juanitogan/mkwinfont/blob/master/python/dewinfont.py
* https://github.com/juanitogan/mkwinfont/blob/master/python/mkwinfont.py
* http://font.gohu.org (.fon, would be useful)
I will try eventually to contain all the needed changes (including LE ints) PE/NE exe/fnt structs into one file.
=> Add dump-fon, a prototype on how to parse .fon/.fnt files

src/hb-open-type-private.hh
It uses floor implicitly without it but explicit use of round will be more correct.
Requested by Behdad on #984
=> Add round to F2DOT14 inner store setter

src/hb-aat-layout-morx-table.hh, src/hb-aat-layout-trak-table.hh, src/hb-ot-hdmx-table.hh, src/hb-ot-hmtx-table.hh, src/hb-ot-os2-table.hh, src/hb-ot-post-table.hh
Splitted from #950 and #986 IIRC Chromium had a policy about this encouraging it,
not sure about automated way to detect and add them but for now lets have the needed
ones of them.
=> Make some of implicit header uses explicit

src/hb-ot-os2-table.hh
As @khaledhosny cool finding on https://github.com/harfbuzz/harfbuzz/pull/981#issuecomment-381714131 this is the way uniscribe understands those fonts. Thanks Khaled! The patch is related to #681 issue.
=> Add pre-opentype font pages detection code

util/options.cc
A bit brute force and requires all shapers to be known, not just one.
Fixes https://github.com/harfbuzz/harfbuzz/issues/956
=> [util] Check all specified shapers are known

src/hb-aat-layout-trak-table.hh, src/hb-coretext.cc, src/hb-debug.hh, src/hb-dsalgs.hh, src/hb-font.cc, src/hb-ft.cc, src/hb-open-type-private.hh, src/hb-ot-font.cc, src/hb-ot-layout-common-private.hh, src/hb-ot-layout-gpos-table.hh, src/hb-ot-os2-unicode-ranges.hh, src/hb-ot-shape-complex-indic-machine.hh, src/hb-ot-shape-complex-indic-machine.rl, src/hb-ot-shape-complex-khmer-machine.hh, src/hb-ot-shape-complex-khmer-machine.rl, src/hb-ot-shape-complex-myanmar-machine.hh, src/hb-ot-shape-complex-myanmar-machine.rl, src/hb-ot-shape-complex-use-machine.hh, src/hb-ot-shape-complex-use-machine.rl, src/hb-ot-shape-normalize.cc, src/hb-set.cc, src/hb-unicode.cc, util/view-cairo.cc
Perhaps "conditional-uninitialize" is the most interesting one of them but the problem is it is not available on CI's clang. Related to #869.
Some more can be picked from these,
`CC=clang CXX=clang++ CFLAGS="-Weverything -Wno-padded -Wno-cast-qual -Wno-sign-conversion -Wno-conversion" CXXFLAGS="-Weverything -Wno-old-style-cast -Wno-documentation -Wno-conversion -Wno-sign-conversion -Wno-c++98-compat -Wno-extra-semi -Wno-c++98-compat-pedantic -Wno-documentation-unknown-command -Wno-padded -Wno-shift-sign-overflow -Wno-missing-field-initializers -Wno-double-promotion -Wno-reserved-id-macro -Wno-cast-qual -Wno-unused-parameter -Wno-comma -Wno-shadow -Wno-used-but-marked-unused -Wno-format-pedantic -Wno-zero-as-null-pointer-constant -Wno-disabled-macro-expansion -Wno-covered-switch-default …
=> Workaround to some of brand-new clang's warnings

test/subset/run-tests.py
The subset test suite fails all test due to path miss matches.
The test suite log states
```
../../../util/hb-subset --font-file=.../test/subset/data/fonts/Roboto-Regular.abc.ttf --output-file=/tmp/tmpZMWZq2/Roboto-Regular.abc.def
ault.61.ttf-subset.ttf --unicodes=61
---
+++
@@ -1,4 +1,4 @@
-Dumping ".../test/subset/data/expected/basics/Roboto-Regular.abc.default.61.ttf" to "-"...
+Dumping "/tmp/tmpZMWZq2/Roboto-Regular.abc.default.61.ttf-subset.ttf" to "-"...
<?xml version="1.0" encoding="UTF-8"?>
<ttFont sfntVersion="\x00\x01\x00\x00" ttLibVersion="3.0">
ERROR: ttx for expected and actual does not match.
Test State:
test.font_path    .../test/subset/data/fonts/Roboto-Regular.abc.ttf
test.profile_path .../test/subset/data/profiles/default.txt
test.unicodes     61
expected_file …
```
=> [subset] Do not compare ttx progress output in the tests

CMakeLists.txt
To avoid need of CMP0063 which is not available on older CMake versions
=> Set inline hidden flag only on shared library building

src/hb-blob.cc
It removes io.h and other polyfills which we no longer need as 7e76d74
=> Remove unnecessary headers and definitions of hb-blob

src/hb-blob.cc
Fixes #1038 
MAP_NORESERVE is not available on macOS for example so set the flag
to zero if not defined on the headers.
=> [blob] Use MAP_NORESERVE if available

src/gen-use-table.py, src/hb-ot-shape-complex-use-table.cc
Consonant_Initial_Postfixed was split off of Consonant_Succeeding_Repha, so it should correspond to the same USE class, CONS_FINAL.
=> Convert Consonant_Initial_Postfixed to CONS_FINAL

util/helper-cairo.cc, util/options.cc, util/options.hh
Fixes #1001 
We were passing the font path directly to freetype so rendering
was broken when we are getting the font from stdin.
This fixes it by using FT_New_Memory_Face instead.
This fixes:
* build/util/hb-view /dev/stdin text < font.ttf
* build/util/hb-view - text < font.ttf
* cat font.ttf | build/util/hb-view - text
but this doesn't work on
* cat font.ttf | build/util/hb-view /dev/stdin text
Which I will try to fix separately.
=> Fix reading fonts from stdin

util/options.cc
Fixes #1058 
In addition to check whether it exists or isn't empty or checks if the input file is a font, which is something not used to happen before.
=> Verbose fail when something is wrong with hb-shape/hb-view input font file

util/options.cc, util/options.hh
Fixes these TBRs [1](https://github.com/harfbuzz/harfbuzz/pull/1059#issuecomment-397912812), [2](https://github.com/harfbuzz/harfbuzz/pull/1060#discussion_r195945045)
> Humm. I'm leaning towards changing the API to return NULL if file does not exist. Or, better, check if blob == hb_blob_get_empty (), instead of checking length being zero.
So should I both check if `blob == hb_blob_get_empty ()` and NULL?
> On the creation side, obviously, make it return nil blob only on error.
So you like to change [this](https://github.com/harfbuzz/harfbuzz/blob/1.7.7/src/hb-blob.cc#L609) to NULL and check for that here?
=> Apply needed fixes of previous changes

util/options.cc
Fixes #1064.
Or some other token would be needed as AIX and Windows issue.
Interestingly fopen or CreateFile didn't support "STDIN" as string at least on my tests on Wine on our current CreateFile configs.
Bad idea? I am out of idea for #1064 so.
=> Treat - just as /dev/stdin and remove one extra file reader

src/hb-blob.cc
* Handle EINTR on fallback reader
* Increase fallback reader limitation size limitation to 2 << 28
* Ensure _O_BINARY does exist if MMAP is used on Windows
(maybe superfluous but makes me more confident)
=> Minor touches on hb_blob_create_from_file

src/hb-open-file-private.hh, src/hb-open-type-private.hh, src/main.cc
Fixes #128. Hi @brawer @anthrotype I've tried to use your implementations on [GNU Classpath](https://github.com/jatovm/classpath/blob/master/gnu/java/awt/font/opentype/MacResourceFork.java) and [fonttools](https://github.com/fonttools/fonttools/pull/400/files) for this (which I derived [this](https://gist.github.com/ebraminio/3b1c91ce605cc93dba59d984ecece7b7) for convenience). [This](http://mirror.informatimago.com/next/developer.apple.com/documentation/mac/MoreToolbox/MoreToolbox-99.html) doc (which its original link was dead) was very helpful
=> Support dfont font files

src/hb-ot-shape-complex-use-table.cc
Completes #1037 and fixes #1035.
This is the danger of keeping generated files in version control. Maybe you could add a CI test to verify that all generated files are up to date.
=> Regenerate the USE table for Grantha and Bhaiksuki

CMakeLists.txt, src/Makefile.am, src/gen-def.py
When one is not using the msys2 python to run the `gen-def.py` script, the header files that are passed in as environment variable cannot be found:
https://ci.appveyor.com/project/fonttools/ttfautohint-py/build/1.0.65/job/rkremny4jjid9nl2#L803
This is because msys2 shell and GNU make use POSIX paths (e.g. `/c/Users/clupo/...`) whereas non-msys2 python.exe uses native Windows paths (e.g. `C:\Users\clupo\...`).
Msys2 will automatically convert command line arguments (but not environment variables) from POSIX to Windows paths when calling a native win32 executable, so we need to pass the header paths as arguments instead of environment variables.
This way the gen-def.py script can support both mingw python running in an MSYS2 shell, and native win32 python.
This is required for building the …
=> gen-def.py: pass headers as arguments so that msys2 can convert posix paths

src/hb-ot-layout-common-private.hh, src/hb-ot-layout.cc
Limit the number of iterations of the closure algorithm and don't reprocess glyphs added during single subst closure.
=> Fix fuzzer timeout.

src/hb-ft.cc, src/hb-glib.cc, src/hb-icu.cc, src/hb-ot-font.cc, src/hb-shape.cc, src/hb-shaper.cc
Add HB_USE_ATEXIT macros around free_static function definitions to
avoid unused function compiler warnings/errors.
=> Guard free_static function definitions with macro

src/hb-common.cc
Old Hungarian, like Runic, can be written in either direction and often ligates letters.
=> Do not enforce a native direction of RTL for Old Hungarian

src/hb-font.cc
Missing "out" indicator. Affect gobject introspection.
=> Missing "out" indicator

src/hb-face.cc
There should be a colon separating "(transfer full)" and the rest. Warned by g-ir-scanner.
=> Missing colon for gobject annotation

src/hb-aat-layout-morx-table.hh
This reverts commit f4072e8cb81072cd6d51a2607efedb76c02e7db1.
https://github.com/harfbuzz/harfbuzz/issues/1195
=> [morx] Only insert glyphs at mark when a mark has been set before

configure.ac
Before this change, autoconf was emitting the following warnings:
```
configure.ac:22: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:22: the top level
configure.ac:22: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:22: the top level
configure.ac:22: warning: AC_COMPILE_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: AC_USE_SYSTEM_EXTENSIONS is expanded from...
configure.ac:22: the top level
configure.ac:22: warning: AC_RUN_IFELSE was called before AC_USE_SYSTEM_EXTENSIONS
../../lib/autoconf/specific.m4:368: …
```
=> Minor: Fix autoconf warning

test/shaping/run-tests.py
Fixes #1226, to workaround a bug apparently https://stackoverflow.com/a/4408409
=> Use tempfile in run-tests as a fix for Windows CI fails

CMakeLists.txt, src/hb.hh, test/api/test-collect-unicodes.c, test/api/test-subset-glyf.c, test/api/test-subset-hdmx.c, test/api/test-subset-hmtx.c, test/api/test-subset-post.c, test/api/test-subset-vmtx.c, test/api/test-subset.c
Hi,
There are some fixes that are needed for Visual Studio builds when:
-We are building the tools and we are building HarfBuzz as a DLL, as Visual Studio does not support GCC visibility attributes as well.
-Building the test-subset* sources on older Visual Studio, as some variables are not at the top of the block.
This PR is for the fixes that are needed.
=> Few fixes for Visual Studio

src/hb-ot-tag.cc, test/api/test-ot-tag.c
All the Indic3 tags are mapped to the same scripts as the Indic2 tags. This includes 'mym3', though 'mym2' doesn’t use the Indic shaper.
=> Parse Indic3 tags

src/hb-graphite2.cc
`_hb_graphite2_shape` is supposed to use the same script tags as OpenType, except that it prefers e.g. 'deva' to 'dev2'. If the call to `hb_ot_tags_from_script_and_language` is restricted to 2 script tags, the tags will be e.g. 'dev3' and 'dev2'.
=> Fix Indic script tags in Graphite

src/hb-ot-layout.cc
=> typo in gobject annotation - "in/out" should be "inout"

src/hb-ot-tag.cc
Fixes the following warnings:
hb-ot-tag.cc:330: Warning: HarfBuzz: invalid "allow-none" annotation: only valid for pointer types and out parameters
hb-ot-tag.cc:334: Warning: HarfBuzz: invalid "allow-none" annotation: only valid for pointer types and out parameters
=> "allow-none" annotation for "out" parameters

.circleci/config.yml, src/hb-ot-shape-complex-arabic.cc, src/hb-ot-shape-complex-myanmar.hh
Actually the check is right,
On -myanmar.hh, on that particular switch, OT_C is indic_category_t
but OT_D is myanmar_category_t so we are mixing the types in one variable.
And on -arabic.cc, step can goes one number higher than step_t enum in the
loop so we are actually using it as an unsinged int.
=> [ubsan] Use unsigned int instead enum where needed

appveyor.yml, src/hb-blob.cc, util/options.hh
DirectWrite support failed to build, so I disabled it, not sure we care about building it on Cygwin.
Gobject-Introspection failed on x86 build only, hard to debug without and actual Windows machine, so also disabled for now.
=> Cygwin fixes and CI build

src/hb-set.hh
When hb_set_t::page_for_insert needs to insert at the end of the page_map
it ends up evaluating '&page_map[i + 1]' which has hb_vector return an
lvalue of a Crap so that nothing can be moved to its address. This turns
into issues with ThreadSanitizer on Crap when two threads modify different
hb_set_t instances. This can be avoided by using '&page_map[i] + 1'
instead.
=> Remove some use of Crap in hb-set.

src/hb-debug.hh, src/hb-set.hh
Hi, and thanks for all the work on HarfBuzz.
I've been working to reduce warnings from the latest GCC, which is fairly strict.
This patch fixes some function parameter / template and other issues.
It'd be great if you consider accepting it.
=> fix various GCC 8.1.X function pointer warnings

src/hb-ot-hmtx-table.hh, src/hb-ot-os2-table.hh, src/hb-subset.cc
Other tables follow the case of the OT tag, except this one.
=> [os2] Capitalize table tag and struct

src/hb-ft.cc
See freetype/src/base/ftobjs.c:ft_recompute_scaled_metrics() and
the usage of GRID_FIT_METRICS inside.
Fixes https://github.com/behdad/harfbuzz/issues/1262
=> Use non-GRID-fitted values for metrics

src/hb-atomic.hh, src/hb-blob.cc, src/hb-mutex.hh, src/hb-ot-shape-complex-arabic-fallback.hh, src/hb.hh
Cygwin is a Posix platform to the extent possible.  It should use the
Posix API except in special circumstances.
After this change, harfbuzz-2.1.1 builds and passes all tests on both 32-bit and 64-bit Cygwin.  I can't check the git HEAD at the moment because I don't have ragel.
=> Don't use Win32 API on Cygwin

src/gen-use-table.py, src/hb-ot-shape-complex-use-table.cc
According to [L2/12-322](https://www.unicode.org/L2/L2012/12322-n4330-sharada-sandhi-mark.pdf), a Sharada cluster may have two sandhi marks, and a sandhi mark may follow U+111C8 SHARADA SEPARATOR.
=> Fix USE categories for U+111C9 SHARADA SANDHI MARK

docs/usermanual-clusters.xml
Expanding on the clusters chapter. Not a major change to the examples (yet), although this does edit the base/mark example in an attempt to be clearer. In the future I suspect real-world examples will be superior to A,B,C,D,E ... but one step at a time.
=> Usermanual: expand clusters chapter.

src/hb-machinery.hh
Profiling showed that type conversions were adding considerable cycles in time
spent doing text shaping.
The idea is to optimize it using native processor instructions to help Blink
layout performance.
NOT for commit: still needs further testing on ARM (i.e. unaligned loads) and handling other OS-es (only tested on Linux).
=> Optimize harfbuzz big integer conversions

docs/usermanual-getting-started.xml
add call to `FT_Set_Char_Size`, otherwise default size remains at `0`, and glyph positions come back as `0` too
=> update simple shaping example (closes #298)

src/hb-icu.cc
Use of the deprecated API USCRIPT_CODE_LIMIT prevents harfbuzz
using the ICU4C as a shared library.
The API has been replaced by u_getIntPropertyMaxValue(UCHAR_SCRIPT)
=> Replace @Deprecated ICU API - USCRIPT_CODE_LIMIT

src/hb-aat-layout-morx-table.hh, src/hb-dsalgs.hh, src/hb-face.cc, src/hb-machinery.hh, src/hb-open-type.hh, src/hb-ot-color-cpal-table.hh, src/hb-ot-kern-table.hh, src/hb-ot-layout-gpos-table.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-vector.hh
Testing ground to see how to better fix old-gcc's ambiguous-overload errors:
```
hb-ot-vorg-table.hh:96: error: ISO C++ says that these are ambiguous, even though the worst conversion for the first is better than the worst conversion for the second:
hb-vector.hh:87: note: candidate 1: const Type& hb_vector_t<Type, PreallocedCount>::operator[](unsigned int) const [with Type = OT::VertOriginMetric, unsigned int PreallocedCount = 8u]
hb-ot-vorg-table.hh:96: note: candidate 2: operator[](const T*, int) <built-in>
```
=> Fix ambiguous overload errors with old compilers

src/hb-cff-interp-common.hh, src/hb-cff2-interp-cs.hh
`set_bends` now takes a sub-array of blend values so that it can’t crash.
The original error check is tweaked and still used to let an error case fail early when arguments on stack too short.
Tested against the minimized test case with and without the error check.
=> [CFF] Refix oss-fuzz 11714: set_blends (PR #1458)

src/hb-ot-cff1-table.hh
Added case for OpCode_BaseFontName. This opcode is in CFF spec but practically unused.
Added a comment for the default case which can't be hit by only two callers of this function `name_op_to_index`.
=> fix for issue #1447: unhandled opcode in name_op_to_index

src/hb-ot-cff-common.hh, src/hb-ot-cff1-table.hh, src/hb-subset-cff-common.cc, src/hb-subset-cff-common.hh, src/hb-subset-cff1.cc, src/hb-subset-cff2.cc
Minimized usage of `assert()` in CFF code, either by:
(1) handle a failure condition as an error if it may ever happen with bad/unexpected input
(2) removed, if a failure shouldn't happen and cannot be easily handled as an error
(3) leave assert, if a failure shouldn't happen
=> [CFF] minimized assert usage

CMakeLists.txt, test/api/hb-test.h, test/api/test-aat-layout.c, test/api/test-font.c, test/api/test-map.c, test/api/test-ot-color.c, test/api/test-ot-face.c, test/api/test-ot-name.c, test/api/test-ot-tag.c
Hi,
This updates the flags passed to g-ir-scanner in the CMake build files so that it won't complain about not including the headers correctly, and updates the test programs (in C) to declare variables at the top of the block, so that things will continue to build properly.
=> Few fixes for Visual Studio builds

src/hb-cff-interp-common.hh, src/hb-cff-interp-cs-common.hh, src/hb-cff-interp-dict-common.hh, src/hb-cff1-interp-cs.hh, src/hb-cff2-interp-cs.hh, src/hb-ot-cff-common.hh, src/hb-ot-cff1-table.cc, src/hb-ot-cff1-table.hh, src/hb-ot-cff2-table.cc, src/hb-ot-cff2-table.hh, src/hb-subset-cff-common.cc, src/hb-subset-cff-common.hh, src/hb-subset-cff1.cc, src/hb-subset-cff2.cc, src/hb-subset-cff2.hh
Fixes issue #1496.
Reimplemented struct `ByteStr` in CFF code as `byte_str_t` based on `hb_ubytes_t`.
Uncamelized all non-table type names in CFF namespace, e.g., `CFF1TopDict_OpSerializer` to `cff1_top_dict_op_serializer_t`.
=> CFF renaming

src/hb-ot-cff2-table.hh
added a call `topDict::fini()` to `accelerator_templ_t::fini()`
(not fini_deep)
=> fix lealk with cff2::accelerator_templ_t::topDict

src/gen-os2-unicode-ranges.py
In Python 3, __reload()__ was moved and __sys.setdefaultencoding()__ because the default is already utf-8.  Also __Error()__ is an _undefined name_ and __Exception()__ creates a generic exception.
[flake8](http://flake8.pycqa.org) testing of https://github.com/harfbuzz/harfbuzz on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/gen-use-table.py:163:19: F821 undefined name 'Number'
return (UISC in [Number, Consonant, Consonant_Head_Letter,
^
./src/gen-use-table.py:163:27: F821 undefined name 'Consonant'
return (UISC in [Number, Consonant, Consonant_Head_Letter,
^
./src/gen-use-table.py:163:38: F821 undefined name 'Consonant_Head_Letter'
return (UISC in [Number, Consonant, Consonant_Head_Letter,
^
./src/gen-use-table.py:165:4: F821 …
```
=> Python 3 fixes to gen-os2-unicode-ranges.py

test/subset/generate-expected-outputs.py
[flake8](http://flake8.pycqa.org) testing of https://github.com/harfbuzz/harfbuzz on Python 3.7.1
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./src/gen-use-table.py:163:19: F821 undefined name 'Number'
return (UISC in [Number, Consonant, Consonant_Head_Letter,
^
./src/gen-use-table.py:163:27: F821 undefined name 'Consonant'
return (UISC in [Number, Consonant, Consonant_Head_Letter,
^
./src/gen-use-table.py:163:38: F821 undefined name 'Consonant_Head_Letter'
return (UISC in [Number, Consonant, Consonant_Head_Letter,
^
./src/gen-use-table.py:165:4: F821 undefined name 'Tone_Letter'
Tone_Letter,
^
./src/gen-use-table.py:166:4: F821 undefined name 'Vowel_Independent'
Vowel_Independent #SPEC-DRAFT
^
./src/gen-use-table.py:168:11: F821 undefined name …
```
=> print() is a function in Python 3

.circleci/config.yml, src/gen-use-table.py, test/subset/subset_test_suite.py
Catch missing imports and errors like #1520 and #1521
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
=> CircleCI: Test for Python 3 syntax errors and undefined names

docs/usermanual-buffers-language-script-and-direction.xml, docs/usermanual-clusters.xml, docs/usermanual-getting-started.xml, docs/usermanual-install-harfbuzz.xml, docs/usermanual-shaping-concepts.xml, docs/usermanual-what-is-harfbuzz.xml
Primarily this expands on the existing cluster material, making a few things explicit or restating them in bullet lists. That means some facts get duplicated, but it's for the sake of better guiding readers who drop into the docs without reading everything in "the correct order" starting from page zero.
Also adds 'script', 'grapheme', and 'syllable' to the Terminology list and tries to clean up some miscellaneous gtk-doc formatting troubles.
=> [docs] Usermanual: expand explicit discussion of cluster-related stuff

src/hb-subset-cff1.cc
This is a fix for oss-fuzz issue 12310.
`cff_subset_plan::~cff_subset_plan` forgot to call `subset_enc_supp_codes::fini` instead was calling `init`, likely failed to edit after copy&paste. Bummer.
=> fix leak with subset_enc_supp_codes

src/hb-coretext.cc
TARGET_OS_OSX was introduced only in late OS versions
so always returns as "0" on older systems.
Just testing for  !TARGET_OS_IPHONE can work, as it returns as !0 on older
systems where TARGET_OS_IPHONE is not defined, but is not
specific
if TARGET_OS_MAC && !(defined(TARGET_OS_IPHONE) && TARGET_OS_IPHONE)
is both specific and accurate on all systems.
This fix is tested on 10.4, 10.5, 10.6, 10.7, 10.13, and 10.14 so far.
See <https://github.com/harfbuzz/harfbuzz/issues/1540>
=> hb-coretext.cc: clean up macosx test

src/hb-coretext.cc
it is always true when building on APPLE systems
and this file only builds on APPLE systems
I am not able to test this on an iPhone build, but I can confirm it works correctly on macOS 10.4, 10.5, and 10.6.
=> hb-coretext.cc: remove TARGET_OS_MAC from test

src/hb-ot-layout.hh, src/hb-ot-shape-complex-arabic.cc
For some reasons djgpp doesn't understand "unsigned int" can be same
with one of uint*_t anyway so lets do that for it explicitly.
Just to note, our CI's djgpp is based GCC 7.2.0 and isn't old.
=> Fix djgpp complains by tweaking templates

src/hb-atomic.hh
I'd like to fix build with xlclang++ on AIX which defines `__ibmxl__` but not `__IBMCPP__`.
=> Support xlclang++ on AIX.

docs/harfbuzz-sections.txt
It is rather confusing to have script, language etc, in hb-common section while feature is in hb-shape section. I keep looking for it in hb-common section then using the API index because I can’t find it there.
=> [doc] Move feature_t and its function to hb-common

src/hb-directwrite.cc, src/hb-directwrite.h
It makes a hb_face_t from IDWriteFontFace, useful when using
DirectWrite facilities for font selection, loading and rendering
but using harfbuzz for shaping.
Fixes #1575
<details><summary>The code I've used for testing</summary>
```C
﻿#include <DWrite_1.h>
#include <stdio.h>
#include <stdint.h>
#include <hb.h>
#include <hb-directwrite.h>
class DWriteFontFileLoader : public IDWriteFontFileLoader
{
private:
IDWriteFontFileStream *mFontFileStream;
public:
DWriteFontFileLoader(IDWriteFontFileStream *fontFileStream)
{
mFontFileStream = fontFileStream;
}
// IUnknown interface
IFACEMETHOD(QueryInterface) (IID const& iid, OUT void** ppObject)
{
return S_OK;
}
IFACEMETHOD_(ULONG, AddRef) () { return 1; }
IFACEMETHOD_(ULONG, Release) () { return 1; }
// IDWriteFontFileLoader methods
virtual HRESULT …
```
=> [dwrite] hb_directwrite_face_create, a new API

src/hb-ot-shape-complex-indic.cc
This is a minor change to a recent fix for #1070.
From what I can tell, it doesn't appear possible for a `Matra` to occur before a `Halant,ZWNJ` sequence, due to `Halant,ZWNJ` being a "terminating" sequence for the Indic state machine.
Using the Devanagari test case in the comments as an example, what we get from the sequence
```
U+091F,U+094D,U+200C,U+092F,U+093F
```
is ultimately two consonant syllables `U+091F,U+094D,U+200C` and `U+092F,U+093F`. `U+093F` gets reordered in front of the second syllable's base `U+092F`, so we effectively get this check for free.
=> [indic] Remove superfluous ZWNJ check in final reorder of pre-base matras

src/gen-indic-table.py, src/gen-use-table.py, src/hb-ot-shape-complex-use-table.cc
This removes overrides from gen-indic-table.py and gen-use-table.py that subsequent changes to Unicode have made redundant. It also removes the override of U+17DD KHMER SIGN ATTHACAN in USE, which has an effect on the generated table. That is okay because Khmer text doesn’t use USE; if it ever does, then U+17DD should behave as it currently does in the Khmer shaper, i.e. only allowed at the end of syllables, so the current override to `Vowel_Dependent` is wrong.
=> Remove obsolete overrides from Indic/USE scripts

src/hb-ot-shape-complex-indic.hh
U+09FC BENGALI LETTER VEDIC ANUSVARA has gc=Lo, so it should be able to stand alone, without a dotted circle.
=> Categorize U+09FC BENGALI LETTER VEDIC ANUSVARA as a placeholder

src/hb.hh
MSVC does not set __cplusplus to the latest standard and also it does not like redefining some keywords.
=> Disable unwanted C++ definitions for MSVC.

src/gen-use-table.py, src/hb-ot-shape-complex-use-table.cc
https://github.com/harfbuzz/harfbuzz/issues/1631
=> Override USE category for Grantha and Tirhuta visargas to allow udatta and anudatta

.circleci/config.yml, .travis.yml
Fixes #1609 
I think this makes macos-10.14.3-aat-fonts on par with our current Travis CI
=> [ci] Use only CircleCI for macOS

docs/harfbuzz-sections.txt, src/hb-directwrite.cc, src/hb-directwrite.h
Can be useful when using HarfBuzz for font loading and shaping
but using DirectWrite for rendering.
Code I literally used for testing,
```C
﻿#include <DWrite_1.h>
#include <stdio.h>
#include <stdint.h>
#include <hb.h>
#include <hb-directwrite.h>
int main (int argc, char **argv)
{
hb_blob_t *blob = hb_blob_create_from_file ("C:\\Windows\\Fonts\\tahoma.ttf");
hb_face_t *hb_face = hb_face_create (blob, 0);
IDWriteFontFace *fontFace = hb_directwrite_face_get_font_face (hb_face);
hb_face_t *face = hb_directwrite_face_create (fontFace);
printf ("%d == %d == %d", hb_face_get_glyph_count (hb_face), fontFace->GetGlyphCount(), hb_face_get_glyph_count (face));
hb_face_destroy (face);
scanf ("%d", new int);
return 0;
}
```
=> [dwrite] A new API, hb_directwrite_face_get_font_face

src/hb-ot-layout-common.hh
Fixes a bug in CoverageFormat2::serialize whereby the first range
was not serialized correctly if it consists of only a single glyph ID.
This broke shaping of U+0626 in the Arabic fallback shaper, because it
is not found in the coverage table of the 'init' and 'medi' lookups.
Also fix similar bug in ClassDefFormat2::serialize, noted during code
inspection (I haven't observed a case that was actually affected by
this, but it looks broken).
Fixes https://github.com/harfbuzz/harfbuzz/issues/1504
=> Don't skip setting the .end field of the first range

src/hb-ot-cff-common.hh
Fix "warning C4138: '*/' found outside of comment"
=> Fix MSVC C4138 warning

src/hb-ot-layout.cc, src/hb-ot-layout.h
This adds GTK-Doc documentation comments for most of hb-ot-layout.cc's public API, and adds documentation comments for the hb_ot_layout_get_glyph_class enum in hb-ot-layout.h. Several odd bits and pieces remain, but this is a big chunk.
=> [Docs] Add inline gtk-doc comments for hb-ot-layout

CMakeLists.txt
Fixes #1633
The demo uses virtually all the important logic of HarfBuzz and the .wasm binary size is 710kb and 215kb zipped.
Lets see how we can have it cleanly here.
=>  Add harfbuzzjs build configuration 

src/gen-use-table.py, src/hb-ot-shape-complex-use-table.cc
According to [the Balinese Unicode proposal](https://www.unicode.org/L2/L2005/05008-n2908-balinese.pdf#page=4), U+1B01 BALINESE SIGN ULU CANDRA can appear on some punctuation and symbols.
=> Allow some Balinese punctuation and symbols as bases for aksara modre

src/hb-common.cc, src/hb-common.h
So can be used with language wrappers
What I understood while reading `hb_glyph_info_get_glyph_flags`... just wondered if is needed here also
=> Add color channels getters ABI

src/hb.hh
The use of getenv() does not make sense in a bare metal system and may be prohibited in some RTOSs since use of getenv() violates MISRA. The HarfBuzz header hb.hh already has code to disable getenv() for Windows CE and Windows Phone platforms. I’d like to add a configuration option HB_NO_GETENV to force disabling getenv() so a user could set this with either a command line definition or in config.h. I also moved the override of getenv() to happen in a single place for clarity.
=> Add configuration option HB_NO_GETENV to disable use of getenv()

src/hb-array.hh, src/hb-iter.hh
`__forward__` decreases the length of an array iterator. `__rewind__` also decreases it! That means that any code of the form `p = p - 1` where `p` is backed by an array iterator will get the wrong item from the array and eventually drain the iterator. This has the potential to cause much confusion and frustration. My fix is to keep track of the length of the array before the current index.
`__next__` advances to the next item of a filter iterator that satisfied the predicate. `__prev__` rewinds to the previous item without checking the predicate. My fix is to loop until the predicate is satisfied.
=> Fix rewinding

src/hb-ot-glyf-table.hh
Fixes bug where we wouldn't use long loca when we should.
Don't write head/loca if we know we are bailing out.
=> [subset] Correct calculation of max offset for loca

src/hb-buffer.cc, src/hb-config.hh
=> Don't use vsnprintf when HB_NO_BUFFER_MESSAGE is defined

src/hb-algs.hh, src/hb-atomic.hh, src/hb-uniscribe.cc, src/hb.hh
mingw.org's MinGW.
src/hb-algs.hh: Don't compile _BitScanForward and _BitScanReverse
for GCC >= 4.  mingw.org's MinGW doesn't have these functions.
src/hb-atomic.hh: MemoryBarrier does exist in mingw.org's MinGW,
but it is not a macro, it is an inline function.  __MINGW32_VERSION
is a macro that exists only in mingw.org's MinGW, so conditioning
on it should not affect MinGW64, where MemoryBarrier is a macro.
src/hb-uniscribe.cc: Define E_NOT_SUFFICIENT_BUFFER if it is not
defined (mingw.org's MinGW doesn't).
src/hb.hh: Don't include intrin.h for mingw.org's MinGW, since that
header is not available; instead, include windows.h.  Conditioned
on __MINGW32_VERSION to avoid affecting MinGW64.
=> This makes minor changes to allow building HarfBuzz with

src/hb-algs.hh, src/hb-array.hh, src/hb-ot-post-table.hh
#593 related, closes #1739 and fixes #1751
Using internal implementation for both:
`make -Cbuild clean && make -Cbuild CXXFLAGS="-Os" -j9` with the sort_r_simple for both
`size build/src/.libs/libharfbuzz.so.0.20501.0`
`732670	  12784	    512	 745966	  b61ee	build/src/.libs/libharfbuzz.so.0.20501.0`
Using system qsort but internal for qsort_r:
`730030	  12792	    512	 743334	  b57a6	build/src/.libs/libharfbuzz.so.0.20501.0`
Using both system's qsort_*s, no internal implementation:
`729434	  12800	    512	 742746	  b555a	build/src/.libs/libharfbuzz.so.0.20501.0`
I still like #1739 more personally as it will use an internal and well tested `qsort` implementation and can be more useful for my case and ever more a code become hot chances are PGO tunes it even better but adds bloat to …
=> Update and use internal qsort everywhere

src/hb-common.cc, src/hb.hh
The only use is in this file, or `#include <locale.h>` should be moved to hb.hh which this seems more efficient
=> Move HB_NO_SETLOCALE to closer place to its to unbreak HB_TINY build

src/hb-ot-tag.cc, test/api/test-ot-tag.c
In today’s OpenType meeting we determined that USE can’t support 'mym3' without many script-specific changes to the cluster model and that only HarfBuzz is currently interpreting 'mym3'. So let’s drop support.
=> Remove 'mym3'

src/hb-unicode.hh
Setting ccc=0 for U+0C55 and U+0C56 prevents reordering, which means among a set of canonically equivalent strings like {<0C15, 0C4D, 0C56>, <0C15, 0C56, 0C4D>} some get dotted circles and some don’t. The original reason to override their classes was to make sure U+0C4D TELUGU SIGN VIRAMA doesn’t get reordered before them, to effect which it is sufficient to change their classes to anything less than 9.
=> Canonically reorder U+0C55 and U+0C56

src/hb-coretext.cc
Follows up on #1783. While 10bac21bb5b25cf20c2198934e99e444625dfd97 fixed this for `FAIL`, it didn't touch `SCRATCH_RESTORE`, a coretext.cc-only macro which was also affected by the same issue.
=> coretext: remove trailing macro from SCRATCH_RESTORE

src/test-ot-color.cc
Should fix:
```
test-ot-color.cc:40:10: fatal error: cairo-svg.h: No such file or directory
40 | #include <cairo-svg.h>
|          ^~~~~~~~~~~~~
```
=> Add missing cairo-svg dependency to test-ot-color

src/hb-common.cc
When compiling this for Flutter, we are seeing a failure with comparing `unsigned long` with `long`.
=> Cast long->size_t to ensure comparison of similar types

src/main.cc, src/test-buffer-serialize.cc, src/test-gpos-size-params.cc, src/test-gsub-would-substitute.cc, src/test-ot-color.cc, src/test-ot-name.cc, src/test.cc
In order to compile the library however HB_NO_OPEN is also needed in CFLAGS... let me revert the change so we decide which to pick
=> Replace create_from_file with empty blob if HB_NO_OPEN is defined

src/Makefile.sources, src/hb-bimap.hh, src/hb-ot-cff-common.hh, src/hb-ot-cff1-table.hh, src/hb-subset-cff-common.cc, src/hb-subset-cff-common.hh, src/hb-subset-cff1.cc, src/hb-subset-cff2.cc
Extracted `hb_bimap_t` changes from var-subset branch.
Rewrote its implementation to use a pair of `hb_map_t` replacing a pair of `hb_map_t` & `hb_vector_t`, leaving it simple & generic.
Moved `add()` and `sort()` (renamed from `reorder`) methods to its new subclass `hb_inc_bimap_t` for use by CFF1 and CFF2 subsetters replacing `CFF::remap_t`.
Miscellaneous renaming & typo fixes.
=> add hb_bimap_t

test/api/test-unicode.c
See #1798. While I was doing this [I found a bug in GLib](https://gitlab.gnome.org/GNOME/glib/merge_requests/954).
=> Test at least one character per Unicode version

configure.ac, src/hb-directwrite.cc
I discovered that harfbuzz is blocking the execution of KICAD EDA (http://kicad-pcb.org/) on Windows XP.
This happens because the library is linked for loading DWRITE.DLL implicitely, which works fine on Windows 7 but this blocks the execution on older versions, since this library does not exists.
I would like to suggest a minimal change for checking at runtime the presence of DirectWrite support on the running platform. Together with this fix, I also included few little improvements (check return value of the creator and fix case of included PSDK file names), which are descripted in the commits.
I hope that you will find this useful.
Sincerely.
=> Make harfbuzz working on all existing versions of Windows

src/Makefile.am, src/hb-bimap.hh, src/test-bimap.cc
fixed a bug in `hb_inc_bimap_t::sort()` exposed by the test
modified `hb_bimap_t::set()` to delete an existing entry if given an invalid value. ignore call if given an invalid key
edited `hb-bimap.hh` to include `hb-map.hh` as 'hb.hh` doesn't include it for us
=> add bimap test

src/hb-ot-cmap-table.hh
Related to #1823 and https://github.com/harfbuzz/harfbuzzjs/issues/9#issuecomment-509143536
Fixes what https://circleci.com/gh/harfbuzz/harfbuzz/99080 now sees
=> Fix hb-subset unintialized memory read of cmap table

src/hb-ot-layout-gpos-table.hh
Happens when compiled with `-std=c++2a`, the fix just makes the captures explicit to resolve the issue. Just adding `this` in addition to `=` doesn't work in C++11.
```
src/hb-ot-layout-gpos-table.hh:737:18: warning: implicit capture of 'this' with a capture default of '=' is deprecated [-Wdeprecated-this-capture]
{ return (this+_).intersects (glyphs, valueFormat); })
^
src/hb-ot-layout-gpos-table.hh:736:16: note: add an explicit capture of 'this' to capture '*this' by reference
| hb_map ([=] (const OffsetTo<PairSet> &_)
^
, this
```
=> Fix C++20 compile warning on implicit capture of this with '=' default capture

src/hb-unicode.hh
This reverts commit 1c8654ead41ca746d577549c92d2a41c594ab639. It is a simpler alternative to #1778. I don’t think fonts should rely on input strings not being normalized.
=> Revert "[Myanmar] Prevent reordering between Asat and Dot below"

src/Makefile.sources, src/hb-ot-face-table-list.hh, src/hb-ot-layout.cc, src/hb-ot-meta-table.hh
As "Determining whether a font is CJK (Chinese, Japanese, or Korean) or not, as in the second-last “Else” clause above, can be done by checking the 'dlng' entry (if present) of the 'meta' table, the CJK-related bits of the OS/2.ulUnicodeRange fields, or the OS/2.ulCodePageRange fields." on https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideographic-em-box we need to parse and understand this table to check if a font is CJK. Fortunately it is already implemented on fonttools https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/_m_e_t_a.py
=> Implement meta table parsing

util/options.cc
`gs` is not freed if this error condition is met.
=> [util] Fix memory leak

CMakeLists.txt
Unfortunately, newer CMake versions die during regex variable extraction, causing the build to fail.
This is caused by the lack of escaping used around variables in the extract_make_variable function, causing these variables to be automatically unwrapped into empty strings.
```
CMake Error at CMakeLists.txt:106 (string):
string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
command.
Call Stack (most recent call first):
CMakeLists.txt:118 (extract_make_variable)```
=> [cmake] Fix CMake build on newer CMake versions

docs/harfbuzz-sections.txt, src/hb-ot-face-table-list.hh, src/hb-ot-layout.cc, src/hb-ot-layout.h, test/api/test-baseline.c
Fixes #418
Closes #1354 (that one goes for `bsln` also which this one isn't, but this one has [a not finalized] simulation per the spec)
=> [base] Add hb_ot_layout_get_baseline API

src/hb-directwrite.cc, src/hb-directwrite.h
I've specially exposed the API as I didn't know how to embed harfbuzz
easily elsewhere but now with harfbuzz.cc it has become very easy
and I don't like to see its use anywhere as it has a bad naming and
its Kashida adding is bogus and only useful to check where it should
be added not visually useful.
https://github.com/harfbuzz/harfbuzz/issues/1849#issuecomment-515232748 related
=> Remove hb_directwrite_shape_experimental_width public API

src/hb-cff-interp-dict-common.hh
Otherwise I have to provide a general propose power in harfbuzz.js's libc (or anyone like to embed harfbuzz somwhere). I like to merge entire `CFF::dict_opset_t::parse_bcd` with `parse_float` and `strtod` (and `parse_uint{32}`, `strtol` `strtoul` uses making all them free from platform locale where make sense) later if possible. Not sure where it should reside however, maybe here or, hb-common.cc above `parse_float`.
=> [cff] Implement in-house power of 10

src/hb-ft.cc
Similar to commit d304d60e4d49df14ed85d6646680085f27bafbf2 for ot-font.
=> [ft] Prefer symbol cmap subtable if found

src/Makefile.sources, src/hb-number-parser.hh, src/hb-number-parser.rl, src/hb-number.cc, src/test-number.cc
Update: Ended up to use the implementation only when strtod_l wasn't there.
----
This probably never will end up in harfbuzz repository itself but I wanted to develop it first here, test it and then move it to harfbuzzjs repository, but though having it here also isn't that bad, let's list pros and cons, at least from what I can see,
Pros:
* Having clear semantic of what `hb_parse_double` does, the use on [`parse_variation_value`](https://github.com/harfbuzz/harfbuzz/blob/1083df8b80b08aa1a4f2dabfe414aaa4a0ec8aa1/src/hb-common.cc#L990) apparently accepts space after the '=' (as `strtod` guarantees) but not before the `=` sign, I don't think that is intended.
* No locale dependency of the library for font parsing matters.
* Removal of dependency to `xlocale`, maybe there are systems that …
=> Replace strtod with a ragel implementation

src/hb-blob.cc, src/hb-config.hh, src/hb.hh
The fact this was already in use for old versions of _WIN32_WCE made me more confident that this can reside in main repo itself, useful in harfbuzz.js but more needed in the brand new harfbuzz-kernel.
=> Extract an avoid errno compile flag

src/hb-common.h
I don't expect you like this :) Other than #1973 it is the only needed change, yet is more symbolic! (otherwise makes more sense to keep the patch locally, but is the only really specific needed thing) Both probably can be avoided if I avoid whole glibc headers, which I found can be avoided.
=> Avoid stdint.h in Kernel module compiles

src/hb-serialize.hh
A fix for memory leak that stale links are not freed in pop_discard (). 
This will fix the memory leak issue detected in #1980
=> memory leak fix in serializer

src/hb.hh
Before it results into:
```
C:\Users\iceflower\test\vcpkg\harfbuzz\src/hb-directwrite.cc(883,1): error :  unused function '_hb_directwrite_shape_experimental_width' [-Werror,-Wunused-function] [C:\Users\iceflower\test\vcpkg\harfbuzz\bui
ld\harfbuzz.vcxproj]
C:\Users\iceflower\test\vcpkg\harfbuzz\src/hb-directwrite.cc(883,1): error : In file included from C:\Users\iceflower\test\vcpkg\harfbuzz\src\harfbuzz.cc:46: [C:\Users\iceflower\test\vcpkg\harfbuzz\build\harfb
uzz.vcxproj]
C:\Users\iceflower\test\vcpkg\harfbuzz\src/hb-directwrite.cc(883,1): error : In file included from C:\Users\iceflower\test\vcpkg\harfbuzz\src/hb-unicode.cc:130: [C:\Users\iceflower\test\vcpkg\harfbuzz\build\ha
rfbuzz.vcxproj]
C:\Users\iceflower\test\vcpkg\harfbuzz\src/hb-directwrite.cc(883,1): error : In file …
```
=> Define HB_UNUSED for clang

src/hb-icu.cc
And ignore extra semicolon error to ICU versions < 65
Fixes #1990
=> [icu] Remove HB_ICU_STMT

src/hb-common.h, src/hb-shape.cc
This documents hb_feature_t. This is motivated mostly by the ambiguity
of the units for 'start' and 'end' (clusters) and whether they are
inclusive or exclusive. This also documents that for lookup type 3 the
value is the one based index into the alternates and that in a list of
features later feature values override previous feature values with the
same tag.
=> Document hb_feature_t.

src/hb-ot-cmap-table.hh
It is always assumed to be the notdef glyph. Fix for #2031.
=> Don't include codepoint 0 in the results of collect_unicodes.

CMakeLists.txt
Currently the CMake files do not create the harfbuzz-icu library. This creates it if `HB_HAVE_ICU` is turned on.
=> [cmake] Add harfbuzz-icu library

src/hb-ot-layout.cc
s/substition/substitution/
s/the the/the/
=>  [minor] Fix common typos: substition, the the.

src/hb-cff-interp-cs-common.hh
We want to process all pairs of arguments except the last 6 as lines, so should have been subtracting 6 here, otherwise if the number of arguments happens to be multiples of 6 they will be all treated as curves.
See https://github.com/harfbuzz/harfbuzz/pull/2016#issuecomment-554640098
=> [cff] Fix a typo in processing rlinecurve

src/hb-unicode.hh
ccc=6 will be used in Unicode 13.0, so I moved these modified values out of its way.
=> Don’t modify a ccc to 6

src/hb-ot-color-cbdt-table.hh
Applying unary minus operator to unsigned int causes the following error on MSVS: error C4146
This patch fixes the error.
=> Fix unary minus operator applied to unsigned int

src/hb-ot-shape-fallback.cc, src/hb-ot-shape-normalize.cc
We already have a shorter method that does the same.
=> Prefer _hb_glyph_info_is_unicode_mark where possible.

src/hb-buffer.cc
Bounds are already checked by the caller.
Closes #2073
=> Remove unnecessary check in hb_buffer_t::set_masks.

src/hb-buffer.cc, src/hb-common.cc
This is a cosmetic change.
`0xC2A0` (afaiu) was used, for some reasons. It's not really a problem, but Qt Creator
constantly trying to replace them with regular spaces, so I have to edit those
files separately.
=> Remove non-breaking spaces from comments.

src/hb-sanitize.hh
Alternative fix for the problem in #2079: Never make `max_ops` bigger than `HB_SANITIVE_MAX_OPS_MAX`, especially keeping the value small enough to avoid overflows.
=> Clamp max_ops to upper bound in hb-sanitize.hh

src/hb-ot-shape.cc
Fixes #2099. Fix indentation in mirroring section as well.
=> Fix duplicate check in hb_ot_rotate chars

src/hb-ot-var-gvar-table.hh
=> un-include glyf.hh in gvar.hh

src/hb-ot-shape.cc
Related to #2129 and #2124
Dominik, can you check if this still works on those fonts?
=> Run morx if run is horizontal or GSUB doesn't exist

src/hb-buffer.hh
Cluster should be unsigned. I guess it can also lead to a precision loss on large numbers.
=> Use correct return type in _unsafe_to_break_find_min_cluster.

src/hb-ot-cff1-table.hh, src/hb-ot-cff2-table.hh, src/hb-subset-cff1.cc, src/hb-subset-cff1.hh, src/hb-subset-cff2.cc, src/hb-subset-cff2.hh, src/hb-subset.cc
Issue #1981: Quick rewrite of CFF & CFF2 table subsetter using _subset2 in place of _subset.
More changes to follow.
=> rewrite of CFF/CFF2 subsetter with _subset2

src/hb-ot-cff1-table.hh, src/hb-ot-cff2-table.hh, src/hb-ot-head-table.hh, src/hb-subset.cc
For CBDT/CBLC subsetting the test font NotoColorEmoji is used. It has no `glyf` table yet it has a `head` table to keep. Similar behavior was added inside the subset routines for `cff1` and `cff2`. 
Rather than special casing this behavior for certain tables, this PR makes this behavior the default for fonts that don't have a `glyf` table (or when the `glyf` table is dropped) by adding direct subset methods for the `head` table and calling it from `hb-subset.cc`.
This behavior is already covered by the tests for the `cff` tables.
=> [subset] Keep head when there is no glyf table

docs/harfbuzz-sections.txt, src/hb-draw.cc, src/hb-draw.h, test/api/test-draw.c
Auxiliary things
Other things to consider,
* parent parameter for create and inheritence, `hb_unicode_funcs_create (hb_unicode_funcs_t *parent);` has it but `hb_font_funcs_create (void)` don't so not sure if we need it also.
* `hb_draw_{move,line,quadratic,cubic}_to ()` and `hb_draw_close_path ()`, I think doing so implies `hb_draw_funcs_t` is useful for two ways callings but without having current points using untouched `hb_draw_funcs_t` object isn't that useful for cases line quadratic to cubic or, curve to lines translations, guess we need another abstraction, maybe called pen, to provide those.
=> [draw] Add hb_draw_funcs_is_immutable and hb_draw_funcs_make_immutable

src/hb-set.hh, test/api/test-set.c
If a process operation results in less pages then the current set has, it will likely corrupt the page_map since it overwrites page_map entries ahead of where it's processing. This fixes that problem by always writing updated entries at the end of the page_map and then compacting and cleaning up orphaned entries at the end of process().
=> Fix page_map corruption in hb_set_t during process().

docs/harfbuzz-sections.txt, src/hb-font.cc, src/hb-font.h, src/hb-font.hh, test/api/Makefile.am, test/api/test-var-coords.c
Hold design coords and simulate when normalized coords are set directly.
Fixes #1865
=> [var] Implement hb_font_get_var_coords_design

test/fuzzing/Makefile.am, test/fuzzing/hb-set-fuzzer.cc
It fuzzes all of the hb_set process methods (intersection, subtraction, union, and symmetric difference).
=> Add hb-set-fuzzer.

CMakeLists.txt, src/Makefile.am
This adds the proper c-header and pkg-config references to the GIR.
Also the correct symbol-prefix 'hb' is added instead of 'hb_'.
=> Improve GIR build

.circleci/config.yml, mingw-ldd.py, src/gen-arabic-table.py, src/gen-def.py, src/gen-emoji-table.py, src/gen-indic-table.py, src/gen-os2-unicode-ranges.py, src/gen-tag-table.py, src/gen-ucd-table.py, src/gen-use-table.py, src/gen-vowel-constraints.py, src/sample.py, test/fuzzing/run-shape-fuzzer-tests.py, test/fuzzing/run-subset-fuzzer-tests.py, test/shaping/data/text-rendering-tests/extract-tests.py, test/shaping/hb-diff, test/shaping/hb-diff-colorize, test/shaping/hb-diff-filter-failures, test/shaping/hb-diff-stat, test/shaping/hb-unicode-decode, test/shaping/hb-unicode-encode, test/shaping/hb-unicode-prettyname, test/shaping/hb_test_tools.py, test/shaping/record-test.sh, test/shaping/run-tests.py, test/subset/generate-expected-outputs.py, test/subset/run-tests.py, test/subset/subset_test_suite.py
Let's remove py2 compatibility and use `/usr/bin/env python3`. Let's see what bots think about it.
=> Remove python2 support from tests/utils scripts

src/hb-ot-layout-gsubgpos.hh
fix issue #2186 [subset] GSUB closure taking too long with a fuzzed font
=> remove invalid glyphs from closure

test/fuzzing/Makefile.am, test/fuzzing/hb-draw-fuzzer.cc
Specially checks correctness of the API semantics:
* no move happens when a path is already opened with move-to.
* no path will be left open and close-path will happen at the end of opened paths.
* no path opens with a move-to and will be closed with no length.
* paths start and ending points matches.
* no line/quadratic/cubic command will be issued when no path is started.
As the recent fixes specially the fuzzer <s>locally looks quite good!</s> (update: needs more work) Guess however there will be some failures when ran on clouds, let's see if we can fix them.
=> [draw] Add a fuzzer

src/hb-open-type.hh, src/hb-ot-name-table.hh, src/hb-serialize.hh
As described in issue #2156, I plan to use this new function `add_link_abs()` in hb-serialize.hh for setting up a sub-table link with an absolute offset (i.e., based on the very beginning of the table) for my work of modernizing CFF subsetter with _subset2 #1981.
`ofs` argument to `add_link_abs` may be a signed IntType or an unsigned IntType.
=> added add_link_abs()

src/hb-set.hh, test/api/test-set.c
Re-implemented `del_range()` as outlined in the issue #2193,  modeled upon the existing function `add_range()`.
- If a range covers entire pages, they are deleted from `pages` vector and also from `page_map` by calling `compact()`.
- Added `page_t::del_range()`modeled upon `page_t::add_range()` for hb_set_t::del_range()` to call to delete a sub-range within the corresponding page.
- Added a function `test_set_delrange()` to API test `test-set.c` to exercise & verify various cases of range deletion.
=> Re-implement hb_set_t::del_range

src/hb-array.hh, src/hb-ot-cmap-table.hh
Current versions of OTS fail fonts with cmap 14's who's last offset does not point to the a block at the end of the table.
=> When serializing cmap14 order the offsets from smallest to largest.

src/hb-cff-interp-common.hh, src/hb-ot-cff-common.hh, src/hb-subset-cff1.cc
Another step of issue #1981, rewriting CFF/CFF2 subsetter using _subset2.
Rewrote UnsizedByteStr::serialize_int() using hb_serialize_context_t::check_assign()<T1, T2> now accepts a signed type as T1.
serialize_offset4_op() and serialize_offset2_op() will be later reimplemented with add_link() but for now they call into serialize_int().
=> reimplment serialize_int using check_assign()

src/hb-ot-color-sbix-table.hh, src/hb-ot-var-gvar-table.hh, src/hb-subset.cc, src/hb-subset.hh
So no more double sanitizing source table.
Maybe there was a reason that this was left out in the original design, let's find out.
=> [subset] Add source_blob as a hb_subset_context_t field

src/hb-ot-var-fvar-table.hh, test/api/test-var-coords.c
The API was adding offset to input's infos buffer index also which is
unusual between our APIs and wrong.
=> [var] Fix hb_ot_var_get_axis_infos's offset semantic

src/hb-ot-cff-common.hh, src/hb-serialize.hh
Addresses issue #2227: revisit hb_serialize_context_t::add_link() base arg
Added a prototype of hb_serialize_context_t::add_link() taking `bias` argument (defaulting to 0) which may be specified for all whence_t enum constants `Tail`, `Absolute`, in addition to `Head`. The existing add_link() with base arg calls into this with `bias = base - c->current->head` if base is non-null.
=> add "add_link()" with bias arg

src/hb-open-type.hh, src/hb-ot-cmap-table.hh, src/hb-ot-color-cbdt-table.hh, src/hb-ot-color-sbix-table.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gdef-table.hh, src/hb-ot-layout-gpos-table.hh, src/hb-ot-layout-gsub-table.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-ot-name-table.hh, src/hb-serialize.hh
On top of PR#2232 for fixes #2227 , removed “base” arg to `add_link()` when it is actually `current->head` from cmap, gdef, gpos, gsub, cbdt, sbix subsetters.
Two places where non-head base is used, `AnchorMatrix::serialize()` and `MarkArray::serialize()` in hb-ot-layout-gpos-table.hh, convert base pointer to bias by calling `to_bias()`, then calls add_link() which takes bias replacing base. 
add_link() taking base is removed.
=> add "add_link()" with bias arg - take 2

meson.build
Are based on https://github.com/harfbuzz/harfbuzz/blob/2.6.4/configure.ac#L86
@tp-m Can you help on the comments on the patch and review please?
@khaledhosny @behdad just have merged meson port https://github.com/harfbuzz/harfbuzz/pull/1437/files and applied 1c3f80ba136bffec00343bae87269bbc9c33ecde c494d7abcd626c274477319859b9bcb873aca388 on top, let's reach to some acceptable level at least to remove CMake port before the release, please have a look at the changes and give me and @tp-m your feedbacks, thanks!
=> [meson] Add needed compiler flags

.circleci/config.yml, docs/harfbuzz-sections.txt, src/gen-def.py, src/hb-draw.cc, src/hb-draw.h, src/hb-draw.hh, src/hb-font.h, src/hb-ot-cff1-table.cc, src/hb-ot-cff1-table.hh, src/hb-ot-cff2-table.cc, src/hb-ot-cff2-table.hh, src/hb-ot-glyf-table.hh, src/main.cc, test/api/test-draw.c, test/api/test-ot-face.c, test/fuzzing/hb-draw-fuzzer.cc
Just to have a one-click away patch to disable the API.
=> [draw] Move outline draw API behind HB_EXPERIMENTAL_API directive

meson.build, meson_options.txt, src/hb-gobject-enums.cc.tmpl, src/hb-gobject-enums.h.tmpl, src/hb-gobject-structs.h, src/hb-gobject.h, src/meson.build, test/shaping/run-tests.py
Hi,
This attempts to improve build support with Visual Studio for Meson builds, by:
*  Only applying ```-DHB_DLL_EXPORT``` for the library builds, when built as a shared library
*  Skip tests that involve FreeType, if FreeType support is not enabled
*  Enable finding ICU, Cairo and FreeType manually via looking for headers and .lib's,  GObject/GLib and Graphite2 provide pkg-config files with their build systems for Visual Studio builds, so we could leave these alone.
*  Gave DirectWrite and Uniscribe build support their greenlight, with a minor update
*  Cleaned up DLL builds a bit, since HB_DLL_EXPORT would make the vs_module_defs obsolete as it activates macros to do __declspec(dllexport).  The .def files may still be useful in other situations (MinGW builds?), but that would be outside …
=> Improve Meson build support for Visual Studio

meson.build, src/meson.build, test/api/meson.build
commit 1322ebae33618c78f8e5779b05c17cdaca44c092:
```
[meson] use add_project_arguments() instead of add_global_arguments()
.. and simplify, can pass two languages in one go.
add_global_arguments() won't work if harfbuzz is used as a
meson subproject.
```
commit 7c24cc3f4e0c40d149479475c89c445993975629:
```
[meson] fix spurious warning when building test/api C sources
Fixes compiler warning
test-unicode.c:589:1: warning: ‘test_unicode_properties_lenient’ defined but not used
which didn't happen with autotools.
Reason it does with meson is that the setup for C was slightly wrong.
We would only add -DHAVE_CONFIG_H to cpp_args which is only valid when
compiling C++ code, but not plain C code, and many of these tests were
plain C.
Instead pass -DHAVE_CONFIG_H via add_project_arguments() and …
```
=> Meson test api c files build fix

src/Makefile.am
Just like other targets (except harfbuzz-icu) avoid linking to libstdc++
=> [subset] Avoid linking to libstdc++ in libharfbuzz-subset.so

src/hb-ot-layout.cc
I know the messaging API is a bit ad hoc, and I'm sorry for adding to the adhockery without stopping to plan more broadly - but currently the messaging API tells us that a lookup has been called but you don't know what table the lookup is in!
=> Add messages for GPOS/GSUB phases

src/Makefile.am, src/check-libstdc++.sh, src/check-static-inits.sh, src/check-symbols.sh, src/meson.build
* Search src/ build directory for objects in check-static-inits.sh
* Find .def files in src/ build directory in src/check-symbols.sh
* Pass builddir also in autotools also, we may just remove libs passing after autotools removal
* Move harfbuzz_subset_def target definition so can be referenced as a check-static-inits.sh dependency
=> [meson] Run check-symbols.sh and check-static-inits.sh correctly

src/hb-aat-map.cc
To properly support stable sort in compile() method.
Fixes #2288.
=> Set sequence number when adding feature to aat map builder

src/hb-aat-layout-feat-table.hh, src/hb-aat-layout-morx-table.hh, src/hb-aat-map.cc, src/hb-aat-map.hh, test/shaping/data/in-house/tests/macos.tests
AFAICS something like this should work better. (We really should have some tests, too...)
Fixes #2290.
=> Handle non-exclusive features when mapping OpenType features to AAT

src/hb-algs.hh, src/hb-ot-var-avar-table.hh, src/hb.hh
Fixes #2320
using float decreases it conversion accuracy as revealed by `test-var-coords.c` test.
=> Add an appropriate fallback to hb_signed_mul_overflows

src/hb-algs.hh, src/hb-ot-var-avar-table.hh, src/hb.hh
<s>The problem is in `test-var-coords.c`, the conversion error with it should be turned from 0.5 > to 0.8 > to allow tests be passed.</s> fixed by the comment below
=> Use float in avar calculation instead ints and checking their overflows

docs/usermanual-utilities.xml
Fixes #2324
Changes stray &lt;program&gt; DocBook tags on this page to &lt;command&gt;. No instances found in the other docs.
=> [Usermanual] - correct DocBook tags in utilities.xml

src/Makefile.am
So it ends up in the release tarball and can be used in the meson build.
Fixes #2337
=> autotools: Add fix_get_types.py to EXTRA_DIST

test/subset/run-tests.py
It assumed that stdout of a subprocess in binary mode was using
utf-8 which isn't the case. Instead open stdout of the subprocess
in text mode and let Python handle the decoding.
=> tests: fix subset/run-tests.py under Windows

meson.build, src/meson.build, test/api/meson.build
This adds a seperate library like with autotools.
This also fixes the ico feature option which was just set to required:false
when disabled instead of really disabling it.
Disabling is still broken with msvc because it then tries to find the library
another way, but that's broken for all other deps as well so I left it as is.
For tests only test-unicode.c is using icu specific functions so split it out
into its own category which depends on harfbuzz-icu.
Fixes #2338
=> meson: build a separate library for harfbuzz-icu

src/meson.build
The first commit fixes that hb-icu.h was missing, the second skips the header install in case gobject/icu are disabled.
=> meson: install gobject/icu headers if they are enabled

test/shaping/data/in-house/tests/macos.tests
Looks like there are not format 3 tests yet. And since the only font I know that uses it is Skia - I've added a new test to `macos.tests`.
=> [kern] Test format 3.

src/hb-kern.hh
This commit removes some rudimentary code like `skippy_iter.init (&c);` which isn't needed since `set_lookup_mask` and `set_lookup_props` already called it.
Also, it uses an iterator directly, without a temporary reference.
Overall, this is just a simple refactoring.
=> [kern] Simplify hb_kern_machine_t

src/meson.build
When building for linux with tests disabled, this drops the number of build files from 112 to 62, and the number of targets from 24 to 4.
=> Dont build tests when disabled

util/options.cc
This is a workaround for #2371.
=> Increase the size of the serialization buffer

docs/Makefile.am, docs/harfbuzz-docs.xml, docs/usermanual-buffers-language-script-and-direction.xml, docs/usermanual-fonts-and-faces.xml, docs/usermanual-opentype-features.xml, docs/usermanual-utilities.xml, src/hb-coretext.cc, src/hb-coretext.h, src/hb-ft.cc, src/hb-glib.cc, src/hb-gobject-structs.cc, src/hb-graphite2.cc, src/hb-graphite2.h, src/hb-icu.cc, src/hb-uniscribe.cc
This adds GTK-doc comments to the OS and other-platform-integration API files (Uniscribe, CoreText, GLib, GObject, Graphite2, FreeType, and ICU).
=> [Docs] Add gtkdoc comments to platform-integration

src/hb-coretext.cc
This works around a build issue I recent ran into when building harfbuzz via its conan recipe on bincrafters with Clang 9.0.1:
```
In file included from /Users/rmeusel/.conan/data/harfbuzz/2.6.4/bincrafters/stable/build/e904e11fef36cfcfed90909784b525499cdc3731/source_subfolder/src/harfbuzz.cc:53:
/Users/rmeusel/.conan/data/harfbuzz/2.6.4/bincrafters/stable/build/e904e11fef36cfcfed90909784b525499cdc3731/source_subfolder/src/hb-coretext.cc:608:200: error: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Werror,-Wextra-semi-stmt]
UniChar *pchars = (UniChar *) scratch; do { unsigned int _consumed = DIV_CEIL ((buffer->len * 2) * sizeof (UniChar), sizeof (*scratch)); if ((__builtin_expect (!!(_consumed > scratch_size), 0))) { ; ((void)0); } scratch += …
```
=> FIX: -Werror,-Wextra-semi-stmt in Clang9

src/hb-subset-cff2.cc
Other .resize() calls are checked, presumably this one should be as well.
=> [subset] Check vector resize() call for failure

src/hb-open-type.hh, src/hb.hh
Fixes #2312
Guess went too far, let's find a balance, I think all `sanitize ()` methods also should be marked as nodiscard as accidentally discarding their output can be catastrophic.
=> Add a not discardable bool type, hb_success_t

src/hb-ot-layout-gsubgpos.hh
return true only when all values in array are intersected with input for ChainRule/Rule.
integration tests will be added later, along with GSUB5 PR.
=> [subset] fix intersects () for Context/ChainContext tables

src/meson.build
In case a user passed -Dintrospection=enabled the build would just ignore
it by default because gobject defaults to disabled and the introspection build
gets skipped.
Instead, if introspection is explicitly enabled but gobject is for some reason
missing error out.
Fixes #2404
=> meson: error out if introspection is enabled but gobject isn't

src/Makefile.am, src/gen-harfbuzzcc.py, src/gen-hb-version.py, src/gen-ragel-artifacts.py, src/meson.build
Fixes #2245 and #2242 however has one big issue, it generates ragel artifacts each time not only when the dependent file is updated, same as harfbuzz.cc, ideally harfbuzz.cc should be generated whenever `meson.build` itself is changed and ragel artifacts only when `.rl` files are changed which not considering that causes rest of the project in need for rebuild as timestamp updates.
This is considered the official way to define command targets https://mesonbuild.com/Run-targets.html what we need is basically always running them when some of the files are updated, like what make offers.
=> [meson] Generate harfbuzz.cc, hb-version.h and ragel artifacts

docs/Makefile.am, docs/meson.build, meson.build, meson_options.txt
Fixes https://github.com/harfbuzz/harfbuzz/issues/2409
---
Does something, only lightly tested.
Note that gtk-doc docs are not built by default, only on install. Build `harfbuzz-doc` target explicitly to force a gtk-doc docs build.
=> meson: build documentation with gtk-doc

src/hb-ot-layout.cc
Hi!
I'm finding it necessary to apply this patch in order to get anything back from `hb_ot_layout_get_ligature_carets`. I'm using `Libertinus Serif Display` (`Regular`). If I'm reading the code correctly, we need to pass in the original caret count this way.
Please let me know if there's anything else you need for this PR to be applied, or if I'm mistaken somehow and the original code is correct.
Thanks!
=> minor: fix hb_ot_layout_get_ligature_carets

src/hb-aat-layout-lcar-table.hh, test/api/test-ot-face.c, test/api/test-ot-ligature-carets.c, test/fuzzing/hb-draw-fuzzer.cc
AAT::Lookup has no other way to detect whether it is returned from
a real and sanitized font data or from a null pool, this checks if
the table has been recognized valid by sanitizer by checking
table's major version which is zero if returned from a null pool and
non-zero if is from a sanitized font data, it is expected the other
calls of the table (unlikely to have more calls however) also do a
similar version check before calling the lookups used on the table.
cc: @khaledhosny @pipcet
=> Fix _get_ligature_caret's oob read issue

docs/meson.build, meson.build, src/meson.build
Fixes #2414
Looks like this, except YES and NO are colored with green and red also which looks nice!
```
harfbuzz 2.6.6
Directories
prefix: /usr/local
bindir: bin
libdir: lib
includedir: include
datadir: share
Unicode callbacks (you want at least one)
Builtin: YES
Glib: YES
ICU: YES
Font callbacks (the more the merrier)
FreeType: YES
Tools used for command-line utilities
Cairo: YES
Fontconfig: YES
Additional shapers (the more the merrier)
Graphite2: NO
Platform shapers (not normally needed)
CoreText: NO
DirectWrite: NO
GDI: NO
Uniscribe: NO
Other features
Documentation: YES
GObject bindings: NO
Introspection: NO
```
=> [meson] Add build configuration summary just like autotools

src/meson.build, test/api/meson.build, test/fuzzing/meson.build, test/shaping/meson.build, test/subset/meson.build
```
So one can run a category of interested tests like
meson test -Cbuild --suite aots --suite src --print-errorlogs
Intead issuing particular tests which also is possible like
meson test -Cbuild test-shape --print-errorlogs
```
Feel free to suggest more categories or anything!
=> [meson] Categorize tests using `suite: [...]`

src/Makefile.am, src/update-unicode-tables.make
Also downloads things needed for its job
#2436 related
Needs to be ran in `src/` using `./update-unicode-tables.make`, or in project's root using `make -C src -f update-unicode-tables.make`
=> Move update unicode tables to its own make file

meson.build, src/meson.build, test/api/meson.build, test/fuzzing/meson.build, util/meson.build
Instead of passing dependencies as required we used one giant shared
dependency list containing all dependencies for every library/executable.
While this kinda works, the specified deps are also used for generating
the pkg-config files and this leads to lots of Requires.private and Libs.private
entries which aren't really needed.
This removes the "deps" array and replaces it with a few smaller ones and
makes sure the public libraries only get passed the dependencies actually
needed.
Fixes #2441
=> [meson] Only pass required dependencies to everything

meson_options.txt
Meson doesn't have DISTCHECK_CONFIGURE_FLAGS like concept IIUC
and enabling these is the main thing we are doing with
distcheck flags anyway so lets turn these to auto.
#2436 related
=> [meson] Make gobject and introspection features automatic

meson.build
Originally done [here](https://github.com/harfbuzz/harfbuzz/commit/71cef14ac3de07e4fed0a2903b1f0f639406ec6c) and both our autotools and cmake port have it so guess now our meson port also should, let's see, found it while #2446.
`
[77/249] clang  -o src/libharfbuzz.so.0.20607.0 'src/25a6634@@harfbuzz@sha/hb-aat-layout.cc.o' ... 'src/25a6634@@harfbuzz@sha/hb-glib.cc.o' -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libharfbuzz.so.0 -Bsymbolic-functions -pthread -lm /usr/lib/libfreetype.so /usr/lib/libglib-2.0.so -Wl,--end-group
`
vs autotools',
`
/bin/sh ../libtool  --tag=CC   --mode=link clang  -g -O2  -Bsymbolic-functions -o libharfbuzz.la  -lm -version-info 20600:7:20600 -no-undefined   -rpath /usr/local/lib libharfbuzz_la-hb-aat-layout.lo ... …
=> [meson] Add -Bsymbolic-functions

meson_options.txt, src/meson.build
This was done in #770 as google/oss-fuzz#1085 but no indication of anyone is using it, let remove it from our meson port and autotools so we can just don't care about after the meson migration.
Closes #2446
=> [meson] Remove with_libstdcxx build option

src/meson.build
`default_library` might be 'both', in which case we will fail to link when building with MSVC.
=> meson: Export symbols for a DLL when not building statically

Makefile.am, meson.build, write-tarball-revision.py
Fixes #2472
Am open about the naming and so, inspired by https://github.com/GNOME/phodav/blob/7dc0ab1/meson.build#L12 and learned things from https://github.com/freedesktop/xdg-desktop-file-utils/blob/46d5759/changelog.py
=> [meson] Add git log of last commit to .tarball-revision while dist

test/api/test-ot-face.c, test/fuzzing/hb-shape-fuzzer.cc
Making some use for result of some of the test_font calls to make sure compilers in fuzzers aren't just optimizing the calls or their results.
This is due to my personal experience that sanitizers won't flag any issue unless they see some side effect having operation is happened and just moving of a memory doesn't convince them that something wrong has happened.
=> [fuzzer] Make some use for test_font API calls

src/meson.build, test/fuzzing/meson.build, test/subset/meson.build
So one can skip them easily by `meson test -Cbuild --no-suite slow`
This decreases my time to running the test suite to 6s.
```
Ok:                 304 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            15  
Timeout:            0   
meson test -Cbuild --no-suite slow  26.65s user 12.29s system 586% cpu 6.635 total
```
=> [meson] Mark longer tests with slow

src/hb-ot-var-fvar-table.hh
so no repeated calls to get_axes and in multiple levels, which probably was optimized anyway yet feel better personally for clarity.
=> [fvar] minor

configure.ac, meson.build, src/meson.build
We never practiced the concept of stable and unstable releases, let's
remove the code and always use the stable scheme.
With this we will just always use stable scheme, nothing different from "stable" releases but we may need to tag 2.7.0 after this change to not have confused versioning.
About the meson `version =` part, there is no consistent state between the changes those this is in one commit.
using autotools and issuing 2.7.0, before this change,
`/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2  -Bsymbolic-functions -o libharfbuzz.la  -lm -version-info 20600:8:20600 -no-undefined   -rpath /usr/local/lib libharfbuzz_la-hb-aat-layout.lo ... libharfbuzz_la-hb-ft.lo -lglib-2.0  -lfreetype         `
After the change
`/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2 …
=> Remove concept of stable/unstable from build tools

.circleci/config.yml, .github/workflows/linux-ci.yml, meson.build, meson_options.txt, perf/meson.build, perf/perf-draw.hh, perf/perf-extents.hh, perf/perf-shaping.hh, perf/perf.cc, subprojects/.gitignore, subprojects/google-benchmark.wrap
`rm -rf build && meson build -Dbenchmark=true -Dexperimental_api=true -Doptimization=2 && ninja -Cbuild && build/perf/perf`
gives
```
---------------------------------------------------------------------------------------
Benchmark                                                Time           CPU Iterations
---------------------------------------------------------------------------------------
shape/fa-thelittleprince.txt - Amiri              72493871 ns   72339936 ns          9
shape/fa-thelittleprince.txt - NotoNastaliqUrdu  276136994 ns  275646177 ns          2
shape/fa-monologue.txt - Amiri                    12534512 ns   12508287 ns         58
shape/fa-monologue.txt - NotoNastaliqUrdu         49263441 ns   49196080 ns         13
shape/en-thelittleprince.txt - Roboto …
```
=> Add performance benchmark for shaping, get extents and draw

src/Makefile.am
How this works? gen-harfbuzzcc.py operates at its own source path (see its 7th line)
and that is reliable when used both on meson and autotools.
Just like 19ecabed, weirdly this didn't come up sooner, guess it has something
to do with timestamps. Fortunately whole harfbuzz.cc just doesn't matter for
packagers but we can tag a release only for this if needed.
Just received an email that a Linux user on Debian isn't able to compile harfbuzz for sometime and now that the release is happened that person decided to send a similar to this patch to me. Thanks for letting me know. We have OpenBSD ports https://twitter.com/OpenBSD_ports/status/1275389506120593408 and ArchLinux https://twitter.com/arch_update_bot/status/1275182798857310208 that were able to update their packages and our distcheck …
=> Fix autotools's harfbuzz.cc build

src/hb-ft.cc
=> [ft] Handle nullptr when destroying freetype font

src/hb-blob.cc, src/hb-mutex.hh, src/hb.hh
Use the WINAPI_PARTITION macro to filter desktop/app flavors.
We use a negated desktop check because the default (for mingw-w64 at
least) is to allow all API by combining desktop + app partitions.
This causes build failures if we were to filter using
WINAPI_PARTITION(WINAPI_FAMILY_APP) because it would always be true, but
those API also require Windows 8 or later, while we only require Vista
Fixes warnings like
../src/hb-blob.cc:572:47: warning: 'WINAPI_FAMILY_PC_APP' is not defined, evaluates to 0 [-Wundef]
#if defined(WINAPI_FAMILY) && (WINAPI_FAMILY==WINAPI_FAMILY_PC_APP || WINAPI_FAMILY==WINAPI_FAMILY_PHONE_APP)
^
../src/hb-blob.cc:572:86: warning: 'WINAPI_FAMILY_PHONE_APP' is not defined, evaluates to 0 [-Wundef]
#if defined(WINAPI_FAMILY) && (WINAPI_FAMILY==WINAPI_FAMILY_PC_APP || …
=> win32: Cleanup PARTITION handling

src/gen-emoji-table.py, src/gen-harfbuzzcc.py, src/gen-hb-version.py, src/gen-indic-table.py, src/gen-ragel-artifacts.py, src/gen-ucd-table.py, src/gen-use-table.py, src/gen-vowel-constraints.py
mostly from https://lgtm.com/projects/g/harfbuzz/harfbuzz/?mode=list as #2526 and applied one minor thing on gen-harfbuzzcc.py on a separate commit.
have tested unicode tables generator scripts with `(cd src && ./update-unicode-tables.make)`
=> minor on python scripts

src/Makefile.am
Partially reverts 4fc6189
#2530 related so I can fix that without having to think about autotools effect, who cares anyway, better to not touched them at the first place, I just wanted to show the logic that is used by autotools is also used by meson and actually I am bumping versions for releases using meson anyway.
=> [make] Revert the way harfbuzz.cc and hb-version.h were generated

src/check-c-linkage-decls.py, src/check-externs.py, src/check-header-guards.py, src/check-includes.py, src/gen-harfbuzzcc.py, src/gen-hb-version.py, src/gen-ragel-artifacts.py, src/meson.build
As described in https://github.com/mesonbuild/meson/issues/7156#issuecomment-629622827
Fixes #2530
=> [meson] use the recommended way to store generated files

test/shaping/meson.build, test/shaping/run-tests.py
Reverts da95a8c and use another approach for no-ft compiles
Before the change,
`meson test -Cbuild --no-suite slow  31.22s user 15.25s system 569% cpu 8.157 total`
After the change,
`meson test -Cbuild --no-suite slow  25.07s user 7.21s system 503% cpu 6.406 total`
With 1.5s difference however I was thinking also dropping whole --batch support to avoid the need for #2313 or maybe not, we can discuss that also.
=> [tests] Use shared --batch process

src/meson.build
Libreoffice tries to use only `harfbuzz-icu.pc` and assumes this includes `-lharfbuzz`.
=> meson: Make Requires in .pc files match autotools

test/fuzzing/hb-set-fuzzer.cc
../test/fuzzing/hb-set-fuzzer.cc: In function ‘int LLVMFuzzerTestOneInput(const uint8_t*, size_t)’:
../test/fuzzing/hb-set-fuzzer.cc:38:82: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
38 |   const instructions_t &instructions = reinterpret_cast<const instructions_t &> (data);
|
And it is already disabled at project level so let's disable it here also.
=> Minor, disable strict-aliasing warning in set fuzzer

src/hb-ot-color-colr-table.hh, src/hb-ot-layout-common.hh
Fixing these complains raised by newer versions of clang,
`./hb-ot-layout-common.hh:1720:53: error: loop variable 'gid_klass_pair' is always a copy because the range of type 'hb_map_iter_t<hb_sorted_array_t<OT::HBGlyphID>, (lambda at ./hb-ot-layout-common.hh:1672:29), hb_function_sortedness_t::RETAINS_SORTING, nullptr>' does not return a reference [-Werror,-Wrange-loop-analysis]
for (const hb_pair_t<hb_codepoint_t, unsigned>& gid_klass_pair : + it)`
And
`./hb-ot-color-colr-table.hh:177:44: error: loop variable '_' is always a copy because the range of type 'hb_map_iter_t<hb_filter_iter_t<hb_map_iter_t<hb_range_iter_t<unsigned int, unsigned int>, (lambda at ./hb-ot-color-colr-table.hh:209:31), hb_function_sortedness_t::RETAINS_SORTING, nullptr>, (anonymous struct at ./hb-algs.hh:331:1) &, …
=> Minor, fix -Wrange-loop-analysis warnings

appveyor.yml, meson.build
This, I believe, will prevent any automatic use of subprojects be default and will only look for dependencies on the system.
https://mesonbuild.com/Subprojects.html#commandline-options
=> [meson] Set the default wrap mode to nofallback

src/meson.build
fixes #2564 
Why I care anyway? It reduces whole fuzzer build and run to `CXXFLAGS="-fsanitize=address,fuzzer-no-link" meson build --default-library=static -Dfuzzer_ldflags=-fsanitize=address,fuzzer && ninja -Cbuild && build/test/fuzzing/hb-shape-fuzzer` (no need to explicit disabling of introspection)
=> [meson] Don't allow introspection on static library

.github/workflows/msys2-ci.yml, appveyor.yml
This is motivated by our new github action https://github.com/msys2/setup-msys2 which makes spawning a MSYS2 env easy and hides the install/update details..
(and also github actions has 20 parallel jobs.. compared to 1 in appveyor)
=> CI: Port MSYS2 jobs from appveyor to github actions

src/check-symbols.py
Adds 'mangle_path' to IGNORED_SYMBOLS in order to fix testing under PGO builds
=> [tests] fix PGO build testing

docs/meson.build, meson.build, meson_options.txt
Feels like a better naming as used in fribidi https://github.com/fribidi/fribidi/blob/master/meson_options.txt also
=> [meson] Rename gtk_doc option to docs

test/subset/run-tests.py
This reduces the time needed for tests depending on fonttool's ttx(e.g 20/42 took ~34 seconds before this now it takes ~14 seconds)
Before:
After:
=> Use fonttools's python package instead of cli

src/failing-alloc.c, src/meson.build, test/fuzzing/hb-draw-fuzzer.cc, test/fuzzing/hb-fuzzer.hh, test/fuzzing/hb-set-fuzzer.cc, test/fuzzing/hb-shape-fuzzer.cc, test/fuzzing/hb-subset-fuzzer.cc, test/fuzzing/meson.build
If ever happens… going to be fun!
How to test, 
`CXXFLAGS="-fsanitize=address,fuzzer-no-link" meson build --default-library=static -Dfuzzer_ldflags="-fsanitize=address,fuzzer" && ninja -Cbuild test/fuzzing/hb-{shape,draw,subset,set}-fuzzer` (or `ninja -Cbuild`)
Then run
`build/test/fuzzing/hb-{shape,set,draw,subset}-fuzzer` 
(make sure llvm package thus llvm-symbolizer command is installed)
=> [fuzz] Implement failing allocator

.github/workflows/linux-ci.yml, perf/meson.build, perf/perf-draw.hh, perf/perf-extents.hh, perf/perf.cc, subprojects/ttf-parser.wrap
```
meson build -Dexperimental_api=true -Doptimization=2
ninja -Cbuild
build/perf/perf
```
ttf-parser's extents calculates costly for variable font's when there is no actual coordinates so needs some tweaks, https://github.com/RazrFalcon/ttf-parser/issues/28 and https://github.com/RazrFalcon/ttf-parser/issues/27 to become comparable, it is still comparable when coordinate are given (`/vf` cases) and specially in CFF/CFF2
rustybuzz is a gradual port of harfbuzz to rust https://github.com/RazrFalcon/rustybuzz that now doesn't have glyph related part of our font parsing logics still runs our test suite thanks to ttf-parser.
things can be improved on ot-draw if path command 'sanitization'  be removed.
picked up from https://circleci.com/gh/harfbuzz/harfbuzz/146188 "build/perf/perf && rm -rf …
=> benchmark against ttf-parser

src/meson.build
We now have,
```
$ otool -L src/libharfbuzz.dylib
src/libharfbuzz.dylib:
@rpath/libharfbuzz.0.dylib (compatibility version 0.0.0, current version 0.0.0)
```
And with the change we should get
```
$ otool -L src/libharfbuzz.dylib
src/libharfbuzz.dylib:
@rpath/libharfbuzz.0.dylib (compatibility version 20700.0.0, current version 20700.0.0)
```
Not compatible with autotools result but guess is ok.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2598
=> [meson] Add darwin versions to library()

src/hb-shape.cc, test/fuzzing/hb-shape-fuzzer.cc
@khaledhosny does it make sense? Maybe doesn't worth it as it is highly unlikely or maybe not? Please have a look. Thanks!
=> Skip hb_shape if buffer object is immutable

src/hb.hh
As #2555 turned out some glib headers are imposing that so let's turn it to warning
Fixes #2555
=> Turn -Wunused-but-set-variable to warning

test/fuzzing/hb-draw-fuzzer.cc, test/fuzzing/hb-fuzzer.hh, test/fuzzing/hb-shape-fuzzer.cc, test/fuzzing/hb-subset-fuzzer.cc
It is really unused when failing-alloc isn't on.
As I use clang locally for sanitizer and things I didn't see it locally but in bot logs which use GCC so let's address it.
=> [fuzzer] Mark alloc_state as unused

src/meson.build
Facing problems generating introspection files during the macOS build of
harfbuzz on conda-forge, inspired me to come up with this fix.
Only libharfbuzz_gobject is introspectable, not libharfbuzz. Therefore,
it makes no sense to target the latter for introspection: it should
instead be listed as a dependency.
=> [meson] fix generating introspection

.circleci/config.yml, docs/meson.build, meson.build, perf/meson.build, src/meson.build, test/fuzzing/meson.build, test/shaping/meson.build, test/subset/meson.build
Contains a just put together summary feature polyfill and ternary operator avoidance as fixed by meson in https://github.com/mesonbuild/meson/pull/5007 later
` / ` operator were added in 0.49 so removed the use and turned to `join_paths`
fribidi uses 0.48 https://github.com/fribidi/fribidi/blob/master/meson.build and with this we will get 0.47.0.
Tested in CI also to protected future regressions.
`-Doption={auto,enabled,disabled}` and meson dictionaries aren't supported before 0.47 so likely that can be considered a good stop.
`<0.53`:
```
Directories:
prefix:
/usr/local
bindir:
bin
libdir:
lib
includedir:
include
datadir:
share
Unicode callbacks (you want at least one):
Builtin:
true
Glib:
true
ICU:
true
Font callbacks (the more the merrier):
FreeType:
true
Dependencies used for …
```
=> [meson] Make compatbile with 0.47.0

src/gen-tag-table.py, src/hb-ot-tag-table.hh, test/api/test-ot-tag.c
'TWI ' has a single primary BCP 47 candidate ("tw"), so gen-tag-table.py treated it as unambiguous. However, 'TWI ' also has the non-primary candidate "ak", which alphabetically precedes it, so 'TWI ' was being converted to "ak". That is wrong.
'TWI ' is now converted to "tw". Similarly, 'HYE ' and 'TOD ' are now converted to "hyw" and "xwo". It is a bit odd to convert 'HYE ' (Armenian) to "hyw" (Western Armenian) instead of the more likely "hy" (Armenian, implicitly Eastern Armenian), but this is necessary to make the mapping bijective.
=> Disambiguate OT language system tags when the primary tag is not first

src/hb-gobject-enums.cc.tmpl
This is beneficial for reproducible builds, as build paths can vary
between builds.
=> src/hb-gobject-enums.cc.tmpl: write out only the filename, not the full path

src/gen-hb-version.py, src/meson.build
We need to make sure that the generator for hb-version.h is tracked as a
dependency, otherwise it can be re-generated too late causing compile
errors.
Closes #2667
=> meson: add hb-version.h to dependencies correctly

src/gen-tag-table.py, src/hb-ot-tag-table.hh
Abyssinica SIL 2.000 does not use the unregistered language system tags 'GUK ' and 'SGW '. I think it is safe to remove support for them. I’d like to remove support for 'KHN ' too, but I don’t know what Microsoft fonts are supposed to have used it, so I can’t verify that it would be safe. Instead, I demoted it below the correct tag, 'KHT '. (This will only matter for a font supporting both tags but enabling different lookups for each, which is unlikely.)
=> Demote unregistered vendor-specific language tags

.ci/publish_release_artifact.sh, .circleci/config.yml
Closes #2663.
...and more besides — in addition to posting the prebuilt Windows artifacts (`harfbuzz-win32-<version>.zip`) this also posts the autotools generated dist file (`harfbuz-<version>.tar.xz`).
See [this caveat](https://github.com/harfbuzz/harfbuzz/issues/2663#issuecomment-691089335) about the API token I currently configured in Circle CI.
=> Post build artifacts from CI jobs

src/hb-ot-var.cc, src/hb-ot-var.h
This adds GTK-Doc comments and annotations for hb-ot-var.cc and .h.
=> [Docs] Add gtk-doc comments for hb-ot-var

src/hb-face.cc, src/hb-face.h, src/hb-ot-font.cc, src/hb-ot-layout.cc, src/hb-ot-shape.cc, src/hb-shape-plan.cc, src/hb-shape-plan.h, src/hb-unicode.cc, src/hb-unicode.h
This adds gtk-doc inline comments to mid- and higher-level shaping API funcs & enums, namely in hb-face, hb-unicode, and several OpenType-specific sections of hb-ot-*. Also adds smaller fixes to existing GTK-Doc comment blocks for formatting and consistency.
=> [Docs] Add GTK-Doc comments for external APIs

src/hb-ot-layout-base-table.hh
This patch fixes `Axis::get_baseline` to return `false` if the specified `baseline_tag` does not exist.
=> Fix get_baseline when `baseline_tag` does not exist

src/hb-ot-shape-complex-use-machine.hh, src/hb-ot-shape-complex-use-machine.rl
I don’t understand why, but this seems to fix #2689. The MSYS2 timeouts are unrelated: they first appeared in #2648, before the MSVC tests started failing.
=> [use] Fix tests with MSVC

src/gen-tag-table.py, src/hb-ot-tag-table.hh, test/api/test-ot-tag.c
These are a few unrelated changes to gen-tag-table.py.
The first is purely cosmetic for more consistency of language names in comments.
The second adds a mapping from "hy-arevmda" (Western Armenian) to 'HYE ' (Armenian). Previously, the variant subtag was unrecognized, so it mapped to HYE0 (Eastern Armenian) as plain "hy" does. "arevmda" is deprecated, but it should be recognized to support documents created in the 11 years it was recommended.
The third fixes the mapping from 'MNK ' to "man". Previously it was being mapped to "emk". It was a general bug but it happened to only affect this single mapping.
The fourth maps every individual language to its macrolanguage’s language system tag (if any). For example, "prs" maps to 'DRI ' as before, but now falls back to 'FAR '. Previously it …
=> Fix and tweak gen-tag-table.py

util/hb-subset.cc
* Check that output-file option is actually set before trying to open it.
* Print file name and `errno` when opening the output file fails.
* Be more resilient when writing output file and use `ferror()` to check for errors.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2711
=> [hb-subset] Improve error handling a bit

.circleci/config.yml, test/fuzzing/meson.build, test/fuzzing/run-draw-fuzzer-tests.py, test/fuzzing/run-shape-fuzzer-tests.py, test/fuzzing/run-subset-fuzzer-tests.py
See https://github.com/harfbuzz/harfbuzz/issues/2707#issuecomment-707744079
This wasn’t inconsistent as well, `HB_TEST_SUBSET_FUZZER_TIMEOUT` defaulted to 12 in the test runner, but it was overridden to 50 in meson.build, and then meson has its own test timeout.
=> [test] Remove timeout from test runners

src/hb-ot-shape-fallback.cc
=> [hb-shape-fallback] Use signed int for correction

.circleci/config.yml
Latest ragel version is broken (https://github.com/adrian-thurston/ragel/issues/56), but we also don’t need to regenerate state machine on CI jobs.
=> [CI] Don’t install ragel on circleci jobs

docs/usermanual-buffers-language-script-and-direction.xml
Make it abundantly clear that the context's script etc. don't matter.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2730
=> [docs] Describe buffer context applicability more explicitly

src/gen-tag-table.py, src/hb-ot-tag-table.hh
A BCP 47 language tag with both a script subtag and a region subtag would be printed as a human-readable name in hb-ot-tag-table.hh as if it only had its language subtag.
=> Fix names for language tag in gen-tag-table.py

src/hb-ot-layout.cc, src/hb-ot-shape-complex-indic.cc, src/hb-ot-shape-complex-khmer.cc, src/hb-ot-shape-complex-myanmar.cc, src/hb-ot-shape-complex-use.cc, src/hb-ot-shape-normalize.cc, src/hb-ot-shape.cc
Fixes #2683
```
$ ./util/hb-shape -V dalekh_si.ttf '<1a2f><1a6e><1a6c><1a65><1a41>'
trace: begin preprocess        buffer: [U+1A2F|U+1A6E|U+1A6C|U+1A65|U+1A41]
trace: end preprocess   buffer: [U+1A2F|U+1A6E|U+1A6C|U+1A65|U+1A41]
trace: begin normalize  buffer: [U+1A2F|U+1A6E|U+1A6C|U+1A65|U+1A41]
trace: end normalize    buffer: [U+1A2F|U+1A6E|U+1A6C|U+1A65|U+1A41]
trace: start table GSUB buffer: [uni1A2F=0|uni1A6E=0|uni1A6C=0|uni1A65=0|uni1A41=4]
...
trace: start reordering USE     buffer: [uni1A2F=0|uni1A6E=0|.notdef=0|uni1A6C=0|uni1A65=0|uni1A41=4]
trace: end reordering USE       buffer: [uni1A6E=0|uni1A2F=0|.notdef=0|uni1A6C=0|uni25CC=0|uni1A65=0|uni1A41=4]
```
=> More tracing

.circleci/config.yml, meson.build, subprojects/cairo.wrap, subprojects/expat.wrap, subprojects/fontconfig.wrap, subprojects/google-benchmark.wrap, subprojects/libpng.wrap, subprojects/zlib.wrap
When cairo comes from a subproject fallback it should still take
cairo-ft dependency, otherwise it miss freetype2 cflags.
Also update wrap file to use upstream repository now that meson support
has been merged.
This requires Meson >= 0.54.0 because cairo itself requires that version
and we use the new `fallback: 'cairo'` syntax without specifying a
variable name because cairo does not provide a variable name for
cairo-ft.
=> meson: Fix cairo_ft_dep when fontconfig is a subproject

src/gen-tag-table.py, src/hb-ot-tag-table.hh, src/hb-ot-tag.cc, test/api/test-ot-tag.c
If nothing else works, `hb_ot_tags_from_language` falls back to uppercasing a three-letter BCP 47 language subtag in the hope that it might match a language system tag. For example, "ach" falls back to matching 'ACH '. That is a fine optimization, but there are some false positives. For example, "far" falls back to matching 'FAR '; however, the former is Fataleka and the latter is Persian. Such a mapping does not make sense. I have updated gen-tag-table.py to detect these tricky language system tags and preemptively map them in `hb_ot_tags_from_complex_language` to nothing.
=> Don’t map BCP 47 tags to coincidentally similar language system tags

src/hb-ot-layout-gsubgpos.hh
If the table is kept, when the table is present but only the accelerator
allocation failed, then we run into nullptr dereferences downstream in
hb_ot_map_t::apply when trying to access proxy.accels[i].
To fix this, instead of only setting lookup_count of accelerator_t
itself, drop the whole table to avoid hb-ot-map construction assuming
that the lookups will work correctly despite accelerator allocation
having failed.
Fixes:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24490
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24473
=> [ENOMEM] Drop layout table if layout lookup accelerator allocation failed

src/meson.build
@CURRENT_SOURCE_DIR@ is not listed as a valid string substitution for custom targets in the Meson reference, and in practice it does not get substituted when using the vs2019 backend.
=> meson: use meson.current_source_dir() instead of @CURRENT_SOURCE_DIR@

CMakeLists.txt
Hi,
From the commit message (I am aware the CMake build system is going out, but, anyways :)):
<i>Without this, the built library for harfbuzz-gobject is unuseful.</i>
The reason is because the code in there are only built if `HAVE_GOBJECT` is defined during compilation, so without that, we are more or less building an empty harfbuzz-gobject dll|lib|so.
=> CMake: Define HAVE_GOBJECT when harfbuzz-gobject is built

configure.ac
ICU `pkg-config` support have been available for a long time, and `icu-config` often breaks cross-compiling when the one from host system is found.
=> [autotools] Don’t fallback to icu-config

src/gen-hb-version.py
The file is a dependency for the library as a whole, so previously editing the Meson build files at all would force a full rebuild. This will only rebuild it if the version has changed.
=> meson: avoid regenerating hb-version.h unnecessarily

docs/harfbuzz-sections.txt, src/hb-blob.cc, src/hb-blob.h, src/hb-buffer.cc, src/hb-buffer.h, src/hb-common.cc, src/hb-common.h, src/hb-face.cc, src/hb-font.cc, src/hb-font.h, src/hb-ft.cc, src/hb-map.cc, src/hb-map.h, src/hb-set.cc, src/hb-set.h, src/hb-shape-plan.cc, src/hb-unicode.cc, src/hb-unicode.h
This fills in and adds GTK-Doc inline documentation for several lower-level APIs, namely hb-set, hb-map, hb-common, hb-blob, and hb-buffer. It also propagates some small changes in capitalization and punctuation to existing GTK-Doc comments to look better in the final generated HTML output.
=> [Docs] Add gtkdoc comments for low-level core APIs

.circleci/config.yml
To fix missing --enable-introspection from release tarballs.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2779
=> [ci] Install gobject-introspection on distcheck job

src/hb-ot-layout.cc
Document that language_tag in hb_ot_layout_get_baseline() is currently unused.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2662
=> [docs] Document unused language in get_baseline

docs/harfbuzz-docs.xml
Commit 443f87213272be5ae0579dce4749b2036dfe3815 seems to have moved it to the API part by mistake.
=> [docs] Move note about harfbuzz-old to proper place

src/hb-ot-layout.h, src/hb-ot-meta.h, src/hb-ot-metrics.h, src/hb-ot-var.h, src/hb-style.cc
`/*< skip >*/` does not seem to hide them.
=> [docs] Hide private enum values

src/hb-ot-shape-complex-use-table.cc, src/ms-use/IndicSyllabicCategory-Additional.txt
This uses the data files from
<https://github.com/microsoft/font-tools/tree/ed7b825ddbbd072d8bc731b7f12c54cb375e2f89/USE>.
=> [use] Update overrides to 2021-01-04

src/hb-ot-layout-common.hh
Just avoiding overhead as measured by Garret.
Should rewrite as dagger in the future and confirm that it has the
same benefits. Later on, rewrite as lfind() maybe.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2826
=> Speed up ClassDef/Coverage intersect methods

src/hb-ot-color-colr-table.hh
Coverity reported that this value was uninitialized. It is set later during serialization (line 181) as the number of layers is needed to compute this value. However, the value should be default initialized (to 0).
This should fix #2829
=> [subet/COLR] Default initialize firstLayerIdx

test/fuzzing/hb-set-fuzzer.cc
Currently the fuzzer can create arbitarily long inputs which once big enough will trigger a timeout.
=> [set fuzzer] limit the total number of set members in a fuzzing input.

src/Makefile.sources, src/meson.build
hb-subset-plant.hh and hu-subset.hh have been declared twice in build script, i.e. src/makefile.sources and src/meson.build
=> remove duplicate file names

meson.build, meson_options.txt
It downloads a dependency from the internet, and in the same time not used anywhere (one needs to explicitly call ninja benchmark), not even on the CI (not sure if it that would make much sense since it does not seem to ever fail).
=> Disable benchmark feature by default

.circleci/config.yml, test/subset/data/Makefile.am
A regression from 7b77ce0507e18fb981a9b865f3eaac0c2ae06044.
It was caught by the CI build in the PR, but apparently we are now used to CI failures that they are effectively ignored.
Also, yay for multiple build systems.
=> [build] Fix make distcheck

subprojects/fontconfig.wrap
Pin it to a known working tag instead.
=> [meson] Don’t build FontConfig subproject from master

src/hb-aat-layout-common.hh, src/hb-aat-layout-morx-table.hh, src/hb-algs.hh, src/hb-open-type.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gsubgpos.hh
This breaks tests on my Linux box, but passes on Mac. Sending to
bots to see if helps me figure out what's going on.
The main change is in cast operators of BEInt used to return Type,
now return Wide. I don't understand why that can fail tests (and
with no compiler diagnostic message...).
Nor do I remember why I made this change back in June...  I *think*
I made it to make the types be closer to regular small-int types by
involving just one conversion to signed/unsigned instead of two,
which becomes important in template matching. However, I don't
remember the exact details. Sigh...
=> [constexpr] IntType

src/hb-blob.cc, src/hb-coretext.cc, src/hb-ot-color.cc, src/hb.hh, src/test-buffer-serialize.cc, src/test-gpos-size-params.cc, src/test-gsub-would-substitute.cc, src/test-ot-glyphname.cc, src/test-ot-meta.cc, src/test-ot-name.cc, src/test.cc
Remove unnecessary includes.
Fixes build with some known broken SDKs (Nintendo Switch?)
https://en.cppreference.com/w/cpp/header
Fixes https://github.com/harfbuzz/harfbuzz/pull/2881
=> Include C headers with their C++ names

src/gen-tag-table.py
gen-tag-table.py had a couple strange formatting choices because it was originally written to be compatible with both Python 2 and Python 3. When [Python 2 support was removed](https://github.com/harfbuzz/harfbuzz/commit/e17fd0d91cbd69fa9c01b20bd5c448d0a4fe0e67#diff-99e33544113cf4657f80e03573b539f1aa59964a37f6aaf9a5670818e8cf2b16), the code was not reformatted.
=> Reformat gen-tag-table.py

.circleci/config.yml, Makefile.am, configure.ac, docs/usermanual-install-harfbuzz.xml, meson.build, meson_options.txt, subprojects/.gitignore, subprojects/fontconfig.wrap
We don’t currently use it anywhere. It was used briefly for the `hb-fc-list` tool, but this tool have not been built since 2015:
```
commit cd042fc8c4a3984c3647cd22a27c34f00636f6e8
Author: Behdad Esfahbod <behdad@behdad.org>
Date:   Thu Jun 18 10:55:13 2015 -0700
[util] Disable hb-fc-list for now
Until I figure out what to do about the API, and finalize
the tool.
```
=> [build] Don’t look for FontConfig

src/hb-config.hh
Currently config-override.h is included at the end of this file. This caused a problem for me while undefing HB_DISABLE_DEPRECATED, namely HB_IF_NOT_DEPRECATED was defined before actual undef took place and broke the whole build. I believe it would break builds for some other defines, too. Moving config-override.h include right after predefined configs is more sane and fixes all potential problems with includes.
=> hb-config: Include config-override earlier

src/hb-sanitize.hh
Counting bytes as the operations is likely to be a better proxy for how
much work processing the table will cost vs. the current approach of
counting the number of sub-objects.
This should allow checks for max features, max scripts, etc. to be removed.
I tested this change against the full collection of fonts at https://github.com/google/fonts
and a max ops factor of 3 was sufficient to successfully sanitize all of them.
=> [sanitize] change max ops to track number of bytes processed.

CMakeLists.txt
- Without `target_include_directories()` harfbazz library will not export include directories. This is the main fix.
- Requiring too old cmake version causes warning from cmake that support for old versions can be removed from cmake, so I upped the version requirement. I don't mind if this gets excluded, but I think this should be fixed as well.
- I also silenced the warning about cmake support being maybe removed. I don't see that happening, at least for a while. Yes, I still think this even though I would happy with meson as well. I don't mind if this gets excluded, but I don't believe cmake support can be removed for a while.
=> Fix to export target include directories

src/hb-ot-layout.hh
Used `_hb_glyph_info_substituted()` similar to the change made to `_hb_glyph_info_is_default_ignorable()` in 7686ff854bbb9698bb1469dcfe6d288c695a76b7.
=> [ot] Update _hb_glyph_info_is_default_ignorable_and_not_hidden()

src/hb-ot-shape-fallback.cc, src/hb-unicode.hh
improve comments to reflect that:
ccc 18 includes both "flavors" of qamats: qamats [gadol] and qamats qatan
ccc 19 includes both "flavors" of holam: holam [not haser for vav] and holam haser for vav
This code and its comments may have been written before these code points were added to Unicode.
I.e. originally, these comments may have been complete, but they may have become incomplete in the meantime.
=> improve comments on Hebrew ccc 18 & 19

src/hb-array.hh, src/hb-null.hh
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1577584
This looks like should work to me; but multiple tests fail.  Leaving here to be debugged.  Maybe someone helps me. :)
=> Avoid undefined-behavior, another try

.circleci/config.yml, .github/workflows/linux-ci.yml, .github/workflows/msys2-ci.yml, configure.ac, meson.build, meson_options.txt, util/Makefile.am, util/helper-cairo-ansi.cc, util/meson.build
Link with and use Chafa if available. This produces high-quality terminal graphics using symbols or sixels according to the detected terminal capabilities.
Fixes #2430.
=> [hb-view] Use Chafa for terminal graphics if available

.circleci/config.yml
This version of macOS is no longer supported by Homebrew, it takes 26 minutes to brew the dependencies before it fails.
=> [ci] Drop macos-10_13_6-aat-fonts job

src/hb-ot-shape-complex-use-machine.hh
Hi,
Please consider this fix for a build warning with gcc 8 and earlier. This causes problems in OpenJDK, see issue for details.
Thank you!
..Thomas
=> Fix for: Warnings with gcc 8 and earlier #2972

src/hb-ot-color-colr-table.hh, src/hb-repacker.hh, src/hb-serialize.hh
also support Offset24 in serializer and repacker. 
This depends on PR #2937
=> add subset() method for COLRv1 paint tables, , BaseGlyphV1List and LayerV1List

src/hb-aat-layout-common.hh, src/hb-aat-layout-morx-table.hh, src/hb-aat-layout.cc, src/hb-ot-shape.cc, test/shaping/data/in-house/tests/macos.tests
When zeroing by GDEF late, we need to re-check the GDEF table
(if it is the source of glyph classes) because substitutions may
mean that we now have mark glyphs in slots that were not flagged
as such initially.
Fixes #2967.
=> Update glyph properties during AAT substitutions so that mark zeroing works as expected

src/hb-ot-color-colrv1-closure.hh, src/hb-subset-plan.cc
Use class instead of typename, move _remap_indexes out of #ifndef.
Fixes #2979
=> Chromium build fixes for C++ 17 warning and missing _remap_indexes

src/hb-set.hh, test/api/test-set.c
Test subsets one page at a time instead of by codepoints. On my machine
this is about 250x (not enough samples in the profiler after so this could be
off by a lot) faster than the previous implementation.
I have no clue what the preferred style is for this project so please let me know if if something is off.
=> [set] Compute is_subset by comparing pages.

src/hb-set.hh
Reuse it if possible on consecutive calls to next(). Will signifcantly speed up cases where the entire set is iterated. In local testing iterating a very large set was 10x faster.
=> [subset] Optimize set iteration by caching the last found pagemap idx.

src/hb-subset-cff1.cc
Variable `supp_size` is set but unused and on newer clang versions, see [this](https://reviews.llvm.org/rGcf49cae278b4e972cd2547d72f9ee7d9d69a3af4), this represents an issue.
=> Removed unused variable `supp_size` from plan_subset_encoding(...).

src/hb-graphite2.cc
As of graphite2 1.3.7, `gr_make_face` is deprecated in favor of `gr_make_face_with_ops`. It's a one-liner to port over to using it.
This is potentially a compatibility break since I'm not sure when the `with_ops` API was added, but the minimum version of graphite2 that's supported by Harfbuzz doesn't seem to be documented anywhere anyway.
=> Avoid a deprecation warning in graphite2

src/hb-coretext.cc
Test:
Before:
$ ./hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=coretext
[gid781=0@-78,0+841]
$ ./hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=ot
[gid781=0@-78,0+842]
After:
$ ./hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=coretext
[gid781=0@-78,0+842]
$ ./hb-shape /System/Library/Fonts/ヒラギノ丸ゴ\ ProN\ W4.ttc １ --features="+palt" --shaper=ot
[gid781=0@-78,0+842]
I've verified in the font that 842 is correct.
=> [coretext] Round position info

src/hb-open-type.hh, src/hb-ot-layout-gdef-table.hh, src/hb-ot-layout-gpos-table.hh, src/hb-ot-layout-gsub-table.hh, src/hb-ot-layout-gsubgpos.hh
Fixes GSUB/GPOS table size inflation noticed in #2986
There's an often used pattern in the current serialization code to serialize an object point to an offset by calling serialize() on the OffsetTo which embeds the pointed to structure at the current serializer head. This bypasses the push()/pop_pack() mechanism which can prevent the point to structure from being deduplicated. Ultimately this can result in inflated table sizes.
This PR introduces a new serialize_serialize() method on OffsetTo which wraps push()/pop_pack() around the serialization of the pointed to structure to enable correct deduplication.
=> [subset] Always serialize objects point to by OffsetTo to a new serializer object.

.ci/build-win32.sh
=> Don’t build Cairo subproject with FontConfig on win32 cross-build

RELEASING.md
In anticipation of #3048 I checked the release notes file in the repo and realized it is a bit out of date. At least two points are completely obsoleted by CI changes. Possibly more but I did the ones I know about.
While I was at it I made the list a Markdown checklist suitable for copy/pasting into an issue or PR to track release progress if that is ever desired. I find it handy but that's really up to the fellow doing the work more than anything else.
=> Update release notes to reflect actual current procedure

src/hb-buffer.cc
Seems like a historical artefact that it was true.
=> [buffer] Change nil buffer have_output to false

src/hb.hh
The condition is inverted, regression from 40ec187dec07e97ed4004b9831e7be844e6e7948.
=> Don’t disable getenv on Windows

test/shaping/data/in-house/Makefile.sources, test/shaping/data/in-house/meson.build
It was introduced in 205737acdc268b1c90cf00bde2d2038519a8bf48 but was not actually used.
See https://github.com/harfbuzz/harfbuzz/issues/2098
=> [tests] Add missed test file to Makefile/meson

util/options.cc, util/options.hh
This speeds up `emoji-clusters` by 2x, but overall `time make check -j10` in `test/shaping` stays around 20s; mostly because most of our tests files have few tests in them. So I'm not impressed. Still, this is correct so I'm happy to take it. Specially so if it will also come handy for `hb-subset` batch mode https://github.com/harfbuzz/harfbuzz/issues/3089
Main slowdown seems to be spawning processes; so having test files that batch more tests will be much faster...
=> [util/hb-shape] Cache blob/face in batch mode

src/hb-object.hh
hb_object's user_data is created lazily. The previous implementation of hb_object_set_user_data created space for the user_data but did not actually construct it. This means that hb_user_data_array_t's lock was not constructed. If hb_mutex_t is backed by an implementation which requires that it be constructed (not just zero initialized) then errors will occur when taking the lock when setting the user data.
Change hb_object_set_user_data to construct the user_data in the created space and hb_object_fini to call the destructor.
=> Construct user_data in hb_object

src/hb-ot-glyf-table.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gpos-table.hh, src/hb-ot-maxp-table.hh, src/hb-ot-name-table.hh, src/hb-ot-os2-table.hh, src/hb-ot-post-table.hh, src/hb-ot-var-gvar-table.hh, src/hb-ot-var-hvar-table.hh, src/hb-subset-cff-common.hh, src/hb-subset-cff1.cc, src/hb-subset-cff2.cc, src/hb-subset-input.cc, src/hb-subset-input.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh, src/hb-subset.cc, src/hb-subset.h, test/api/hb-subset-test.h, test/api/test-subset-cff1.c, test/api/test-subset-cff2.c, test/api/test-subset-glyf.c, test/api/test-subset-gvar.c, test/api/test-subset-hvar.c, test/api/test-subset-vvar.c, test/api/test-subset.c, test/fuzzing/hb-subset-fuzzer.cc, util/hb-subset.cc, util/options-subset.cc, util/options.hh
By switching both to bit sets we can easily support a batch set/clear method and as an added bonus makes adding new flags trivial.
One other notable change is this updates the subset fuzzer to take the entire flags bit set from the fuzzer input, which will now allow the fuzzer to toggle any combination of flags.
For #3086
=> [subset] change input and plan flags to be bit sets.

src/hb-subset.h
HB_SUBSET_FLAGS_DEFAULT is 0, and hb_subset_input_create_or_fail
initializes its flags to HB_SUBSET_FLAGS_DEFAULT, so currently all flags
are set to false by default. The documentation for
HB_SUBSET_FLAGS_NO_HINTING is fixed to state that it is false by
default, and the default state is documented for
HB_SUBSET_FLAGS_NO_PRUNE_UNICODE_RANGES and
HB_SUBSET_FLAGS_RETAIN_ALL_FEATURES.
=> Fix documentation of hb_subset_flags_t defaults

util/face-options.hh, util/hb-subset.cc, util/options.hh
This loads the font face before parsing other args, so we can parse glyph names / etc as we go, which allows for correctly removing glyphs by name as well, eventually, after we also implement `hb_set_invert` (to be used for handling `--unicodes='*'` and `--gids='*'` etc).
=> [util/hb-subset] preload face

.ci/publish_release_artifact.sh, .circleci/config.yml
This should fix the issue [noted here](https://github.com/harfbuzz/harfbuzz/issues/3078#issuecomment-900896994) in the 2.9.0 release cycle where the automatic release artifact publishing did not work.
The culprit here was d203267e5 which on first glance is quite logical. The trouble is Circle CI is not logical here and these filters were not "effectively ignored", they were effectively helping the jobs to not be ignored. In order for a job to run as a dependency of another job that has filters it must itself have a filter.
Since clearly the intent of d203267e5 was to also run `distcheck` on PRs and branch pushes, I went ahead and setup filters that will work for that as well as for use as a dependency for the ‘publish-*’ series of jobs.
The expected workflow output can be [previewed on CI …
=> Fix CI workflow for publishing releases

util/shape-options.hh
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Today I lost half an hour to the fact that the OpenType language tag for Turkish is &quot;TRK &quot; and the ISO639-3 language tag is &quot;tur&quot; but if you want hb-shape to select Turkish you have to give it the ISO639-1 language tag, which is &quot;tr&quot;.</p>&mdash; Simon Cozens (@simoncozens) <a href="https://twitter.com/simoncozens/status/1427731577321267204?ref_src=twsrc%5Etfw">August 17, 2021</a></blockquote>
=> Replace "langstr" with more helpful help.

src/hb-subset-input.cc, src/hb-subset-plan.cc, src/hb-subset.h, test/api/test-subset.c, util/hb-subset.cc
Instead use inverted sets to handle requesting all features. Modifies feature collection in subset plan to intersect the set of requested features against the features in the font. This prevents iterating a fully filled feature tag set.
=> [subset] Remove retain all layout features flag.

src/hb-ot-name.cc
Mention that the returned strings are always nul terminated for convenience.
=> Small docs improvement

test/shape/meson.build
No idea why test names are underscorified but it it just makes calling `meson test testname` harder than it should being not able to copy file name directly.
=> [test] Make shape test names match file names

docs/usermanual-getting-started.xml, docs/usermanual-install-harfbuzz.xml
It turns out that the harfbuzz.github.io repo is merely a mirror of this existing doc repo, that is rewritten by a CI bot every night.
Two patches: one about a dead link, and one spelling error, were already merged there, only to be rewritten over by the CI process. This patch places the fixes in the main repo docs, so when the CI rewrites the harfbuzz.github.io repo, it will have the fixes behdad merged.
=> Place fixes from harfbuzz.github.io into main repo

src/hb-ot-shape-complex.hh
Khitan Small Script and Yezidi were the only scripts listed in the USE spec that HarfBuzz didn’t send to USE.
=> [USE] Send Khitan Small Script and Yezidi to USE

.github/workflows/linux-ci.yml, meson_options.txt, src/meson.build
Add an option to build fallback ragel subproject when no suitable ragel version is found, and make it off by default since most builder don’t need ragel at all.
Fixes https://github.com/harfbuzz/harfbuzz/issues/3208 (hopefully)
=> [meson] Add ragel_subproject option

src/hb-style.cc, src/hb.hh
Internets says I need it on MS compilers. I don't believe the internets.
GCC gives me unused-macros warning. Pushing to CI to check.
=> [style] Try removing _USE_MATH_DEFINES

src/hb-atomic.hh, src/hb-mutex.hh
Supersedes https://github.com/harfbuzz/harfbuzz/pull/3100.
This implementation requires libc++. But I'm fine with that because it's plugged in a place that we were err'ing and failing before.
=> [mutex] Add hb_mutex_t std::mutex implementation

src/hb-repacker.hh, src/test-repacker.cc
Prior to this fix id remapping at the end of the isolation operation was fed the old subgraph instead of the new one. Which results in object indices being remapped for the nodes outside of the new subgraph. Adds a test which detects this problem.
=> [repacker] fix bug in subgraph isolation.

src/hb-ot-glyf-table.hh
Adding the result of add_gid_and_children to operation count over counts the number of operations.
=> [subset] Fix bug in composite operation counting.

src/gen-use-table.py, src/hb-ot-layout.hh, src/hb-ot-shape-complex-arabic.cc, src/hb-ot-shape-complex-use-table.hh, src/hb-unicode.hh, src/ms-use/IndicPositionalCategory-Additional.txt, src/ms-use/IndicSyllabicCategory-Additional.txt
This updates USE to use the data files of 2021-09-28. IndicSyllabicCategory-Additional.txt is no longer unclear as to how to categorize hieroglyphs, so I have removed the `extended` hack I added in #2652.
I also added code for the new U+180F MONGOLIAN FREE VARIATION SELECTOR FOUR, which I should have done in #3206. This is mostly unrelated to USE but IndicPositionalCategory-Additional.txt reminded me of it.
=> [USE] Update the data files

.github/workflows/msvc-ci.yml
https://github.com/actions/virtual-environments/issues/4312
`windows-latest` is the same as `windows-2019`, but we are using explicit `windows-2019` image for when they become different.
=> [ci] `windows-2016` image is going away in a bit

src/hb-repacker.hh, src/hb-subset.cc, src/test-repacker.cc
Previous algorithm was to split off roots to their own space one at a time. Instead on each iteration grab the set of all roots that contain at least one overflow and move them to their own space.
Helps with fonts with large numbers of lookups sharing a single space such as in #3316
In the fonts I've tested with the resolver now concludes in a single iteration instead of multiple iterations and produces a final packed size even smaller than the previous implementation.
Additionally this fixes two other bugs I encountered:
- Reduce the number of bits used for 'order' in the modified distance. Under the previous 22 bits the  41 bit distance number was overflowing with fonts that had more than ~500 spaces.
- Have the repacker compute the final buffer size and allocate it, instead of relying …
=> [repacker] Move all overflowing roots to a new space simultaneously.

src/hb-repacker.hh
A change in space will effect the distance assigned to the node and any of it's children so clear the distance cache.
=> [repacker] Clear distance and position cache when assigning a new space.

src/hb-ot-layout-gsubgpos.hh, src/hb-ot-layout.cc
Fixes two problems:
1. Double counting of visited lookups in closure_lookups()
2. Reset the visited count between each iteration during the glyph closure. Each iteration potentially scans all lookups again thus should be working with the full limit.
Fixes #3323
=> [subset] Improve lookup visit counting

CMakeLists.txt
Add check for Freetype CMake target. If it is found:
- enable HB_HAVE_FREETYPE option
- add HAVE_FREETYPE=1 define
- bypass finding Freetype as cmake package
- add Freetype CMake target as dependency to harfbuzz
=> Use freetype from CMake target when present

src/hb-ot-color.cc
Document that the SVG and PNG getters return
the singleton empty blob if the glyph has no
color.
Fixes: #1413
=> color: Document empty returns

meson.build, subprojects/cairo.wrap, subprojects/freetype2.wrap, subprojects/glib.wrap
This converts the "old style" `fallback` keyword arguments to use `[provide]` entries in wrap files instead. This makes it more convenient to use Harfbuzz as a subproject in other projects. Due to backwards compatibility issues having those `fallback` entries may cause unwanted subproject promotions. This is also more compatible with getting dependencies from WrapDB instead.
We are currently discussing how wrap files should be handled in release tarballs. Maybe they should be removed altogether, especially those that do Git checkouts. But that is a decision for another time.
=> Convert fallback kwargs to [provide] entries.

src/hb-ot-color-cbdt-table.hh, src/hb-vector.hh, src/test-vector.cc
Compiler catches cases where types are not safe to do so. We should fix these. Most are in CFF code but a few are not.
We should fix this in main branch and rebase this on top till it's happy, then this branch can continue to make vector follow C++ memory semantics.
=> [vector] Move semantics when resizing

NEWS, RELEASING.md, docs/Makefile.am, docs/repacker.md, docs/usermanual-integration.xml, src/gen-os2-unicode-ranges.py, src/hb-aat-layout-just-table.hh, src/hb-array.hh, src/hb-cff2-interp-cs.hh, src/hb-draw.h, src/hb-ot-color.cc, src/hb-ot-layout-common.hh, src/hb-ot-shape-complex-hangul.cc, src/hb-ot-shape.cc, src/hb-ot-var-gvar-table.hh, src/hb-ot-var.h, src/hb-repacker.hh, src/hb-serialize.hh, src/ms-use/IndicPositionalCategory-Additional.txt, test/api/test-ot-math.c, test/fuzzing/hb-set-fuzzer.cc, util/ansi-print.hh, util/hb-subset.cc
Found via `codespell -q 3 -S ./perf/texts -L actualy,ba,beng,fo,gir,inout,nd,ot,pres,ro,te,teh,timne`
=> Fix various typos

meson.build
In some cases we need to add additionl defs to build against icu if icu has certain options configured.
ICU warns about this when building:
*** WARNING: You must set the following flags before code compiled against this ICU will function properly:
-DU_DISABLE_RENAMING=1
We can fetch these flags from the icu pkgconfig and add them if required.
This fixes symbol errors if ICU is built without renaming.
=> [meson] add icu DEFS required for compilation

src/hb-ot-glyf-table.hh
length() shouldn't be used again as the end of instruction offset is already included in flags_offset.
=> [subset] Fix bound check when setting overlap bit.

meson.build
Fix cross compilation to win64
=> meson: Enable big objects support

src/hb-buffer.h
GTK-Doc does not like the empty lines here, and interprets everything
after the first empty line as the description of the enum itself not a
specific member and the generated text makes no sense.
Removing the empty lines makes the text harder to read (both in source
and HTML), but at least it is correctly organized.
=> [doc] Fix generation of hb_glyph_flags_t docs

.github/workflows/msvc-ci.yml
Downgrade pip, turns out, pip 22.0 is the source of the breakage: https://github.com/mesonbuild/meson/issues/9955#issuecomment-1030843844, https://github.com/pypa/pip/issues/10875
=> [ci] Fix MSVC build

docs/harfbuzz-sections.txt, src/hb-common.h, src/hb-ot-deprecated.h, src/hb-ot-math.h, src/hb-ot-tag.cc, test/api/test-ot-tag.c
The [ISO 15924 code](https://unicode.org/iso15924/iso15924-codes.html) for mathematical notation is `Zmth`, but the corresponding [OpenType script tag](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags) is `math`. HarfBuzz needs to know about the mapping, or else OpenType features that depend on the `math` script won’t be applied. This PR adds `HB_SCRIPT_MATH` to `hb_script_t` (for convenience) and changes `hb_ot_tags_from_script_and_language` and `hb_ot_tag_to_script` to do the necessary conversion.
=> [ot-tag] Add HB_SCRIPT_MATH (Zmth) and map it to OT ‘math’ tag

docs/harfbuzz-sections.txt, src/hb-ot-math-table.hh, src/hb-ot-math.cc, src/hb-ot-math.h, test/api/test-ot-face.c, test/api/test-ot-math.c
This PR implements `hb_ot_math_get_glyph_kernings`, as discussed in #3396.
As described in https://github.com/harfbuzz/harfbuzz/issues/3396#issuecomment-1028299055, designing an API to get this information is awkward, as there is one more kern value than there are correction heights. However, I ended up going with an API closer to the one I initially proposed, which looks like this:
```c
typedef struct {
hb_position_t max_correction_height;
hb_position_t kern_value;
} hb_ot_math_kern_entry_t;
unsigned int
hb_ot_math_get_glyph_kernings (hb_font_t *font,
hb_codepoint_t glyph,
hb_ot_math_kern_t kern,
unsigned int start_offset,
unsigned int *entries_count, /* IN/OUT */
hb_ot_math_kern_entry_t *kern_entries /* OUT */)
```
Since the last entry’s `max_correction_height` field does not correspond …
=> [ot-math] Add hb_ot_math_get_glyph_kernings

src/hb-algs.hh
Hi,
This attempts to fix the build for the tip of the main branch when Visual Studio 2015 is being used, as a `static_assert` (error C2338) is triggered during the build, where the compiler does not recognize the `std::hash` call on `hb_decay<decltype (hb_deref (v)>`, so give it a shove so that it is recognized.
=> hb-algs.hh: Fix build on Visual Studio 2015

meson.build
Hi,
This attempts to fix the build when ICU is found via `meson.get_compiler('cpp').find_library()` instead of pkg-config, as one can call `get_variable()` on the `icu_dep` dependency object only if ICU was found via pkg-config.
=> meson.build: Fix configuration if ICU was found via find_library()

test/api/Makefile.am
The test-draw.c can now optionally uses hb-ft, but automake file was not passing FreeType cflags or libs to it.
=> [autotools] Fix make distcheck

src/hb-style.cc, test/api/test-style.c
Add a test that reveals synthetic slant brokenness. We report twice the expected value
=> Test synthetic slant

src/hb-subset-plan.cc, src/hb-subset-plan.hh, src/hb-subset.cc, src/hb-subset.h, test/api/test-subset.c
For #3140 
Provides access to the subset plan so callers can find information on things such as the glyph mapping from the subset.
=> [subset] expose subset plan in public subsetting API

docs/serializer.md, src/hb-buffer-deserialize-text.hh, src/hb-buffer-deserialize-text.rl, src/hb-buffer.h
Found via `codespell -q 3 -S ./perf/texts -L actualy,als,ba,beng,clen,crasher,dependant,eachother,fo,gir,inout,ist,nd,ned,ot,pres,ro,statics,te,teh,timne`
=> Fixed various misc. typos

src/hb-ot-layout-base-table.hh, src/hb-ot-layout.cc
For BASE table format 1.1, the handling of design
space vs user space coordinates was inconsistent.
We were applying design -> user transformation
twice for the deltas, leading to wrong baseline
values.
Patch by Ebrahim Byagowi <ebrahim@gnu.org>
Fixes: #3476
=> [layout] Fix handling of baseline variations

src/hb-static.cc
Fixes build errors complaining about this function being unused.
=> Make load_num_glyphs_from_loca conditional on HB_NO_BORING_EXPANSION

src/hb-ot-layout.hh
This PR fixes #3487 by adding 
```
if (unlikely (!lig_id))
lig_id = _hb_allocate_lig_id (buffer); /* in case of overflow */
```
back to `_hb_allocate_lig_id` function as suggested by @jfkthame in #3487.
=> Fix for rendering of nuqtas in certain cases

test/shape/data/in-house/Makefile.sources
Hi,
From the commit message--I presume the release tarballs are generated from the autotools builds?
<i>For builds from release tarballs, the tests fail in the DirectWrite and Uniscribe tests when these platform shapers are enabled, since the data files were not found in the source tree, when building with Meson at least.</i>
<i>Fix this by dist'ing the platform shaper test data files.</i>
This will fix the failing tests when building from the release tarballs when platform shapers are enabled.
Sorry, I am not that good in autotools to attempt to enable the platform shaper tests in the autotools builds, so I am not attempting to do that here in this PR.
=> test: Dist the platform shaper test data

src/hb-ot-shape-complex-indic.hh
U+0D04 MALAYALAM LETTER VEDIC ANUSVARA has gc=Lo, so it should be able to stand alone, without a dotted circle.
=> [indic] Categorize U+0D04 as Consonant_Placeholder

src/hb-blob.cc
Fix a couple of cases where it would return empty blob, possibly missed in bdfed8f113431a2156e13d59a4b21e19feb7efd9.
=> [blob] Return nullptr from create_from_file_or_fail

CMakeLists.txt
As of CMake 3.0.0, the `CMAKE_*_COMPILER_ID` for the Apple-provided Clang is no longer "Clang" but "AppleClang".
https://cmake.org/cmake/help/v3.0/release/3.0.0.html#other-changes
This PR ensures that we match either "Clang" or "AppleClang" when adding the flags which prevent from linking with the libc++.
Without this, we currently end up with a shared library on macOS that links with libc++, which is undersirable for pure-C projects like https://github.com/rougier/freetype-py/pull/148
=> CMakeLists.txt: also match 'AppleClang' compiler to not link with libc++

util/hb-subset.cc
With this I can keep the SVG table like this:
```
$ hb-subset --retain-gids --drop-tables-=SVG --passthrough-tables --output-file=build/Font.subset.ttf build/Font.ttf abc
```
I used `--passthrough-tables` instead of `--passthrough-unrecognized` to match the FontTools' pyftsubset CLI -- the respective hb-subset API flag is named HB_SUBSET_FLAG_PASSTHROUGH_UNRECOGNIZED -- but I can change it if you prefer.
FIxes #3532
=> [subset] Expose --passthrough-tables option to hb-subset CLI tool

src/hb-ot-shape-complex-myanmar.cc
The Myanmar shaper doesn't use masks, but a comment taken from the Indic shaper implies that it does.
=> [myanmar] Reword confusing comment about masks

src/hb-aat-layout-morx-table.hh, src/hb-ot-shape.cc, test/shape/data/in-house/tests/macos.tests
And undo the morx direction reversal change introduced in
https://github.com/harfbuzz/harfbuzz/pull/3315
23159084b43c1ce429d9e98035bf845919fd8a89
This fixes original bug https://github.com/harfbuzz/harfbuzz/issues/3314
And the reversion in morx code fixes regressions:
https://github.com/harfbuzz/harfbuzz/issues/3528
https://github.com/harfbuzz/harfbuzz/issues/3535
Supersedes:
https://github.com/harfbuzz/harfbuzz/pull/3529
=> Enforce Regional_Indicators native direction to LTR

src/hb-ot-cmap-table.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh
- Cache an ordered list of unicode -> new glyph id. This saves from having to repeatedly generate the ordered list from the unicodes set and glyph maps during cmap generation.
- Also use the above cache to populate the unicodes set in order to make use of recently added set page lookup caching on insert.
Median reduction in subsetting time of 12% for the MPlus 1p and 10,000 codepoint case. Full benchmark diff:
BM_subset_codepoints/subset_roboto/10_median                              +0.0985         +0.0978             0             0             0             0
BM_subset_codepoints/subset_roboto/64_median                              +0.0296         +0.0309             1             1             1             1
BM_subset_codepoints/subset_roboto/512_median …
=> [subset] Further cmap subsetting speed optimizations

src/hb-cff-interp-common.hh, src/hb-cff-interp-cs-common.hh, src/hb-cff1-interp-cs.hh, src/hb-cff2-interp-cs.hh, src/hb-ot-cff-common.hh, src/hb-ot-cff1-table.cc, src/hb-ot-cff1-table.hh, src/hb-ot-cff2-table.cc, src/hb-ot-cff2-table.hh, src/hb-subset-cff-common.hh, src/hb-subset-cff1.cc
The length_at() function makes sure out-of-range offsets
are discarded. We just need to check the last offset.
=> [cff-common] INDEX cleanup

src/hb-cff-interp-common.hh, src/hb-cff2-interp-cs.hh, src/hb-ot-cff2-table.cc, src/hb-subset-cff2.cc
Do the blending immediately.
Fixes https://github.com/harfbuzz/harfbuzz/issues/3559
Benchmark on AdobeVFPrototype shows 35% speedup. Now we're faster
than FreeType:
Benchmark                                                           Time             CPU      Time Old      Time New       CPU Old       CPU New
------------------------------------------------------------------------------------------------------------------------------------------------
BM_Font/glyph_extents/AdobeVFPrototype.otf/hb                    -0.3792         -0.3792          1584           983          1581           982
BM_Font/glyph_extents/AdobeVFPrototype.otf/ft                    +0.0228         +0.0224          1220          1248          1218          1245
BM_Font/glyph_extents/AdobeVFPrototype.otf/var/hb …
=> [cff2] Change extents/shape stack to be just a number

BUILD.md
for fedora/centos/opencloudos, building harfbuzz requires cairo-devel rather than cairo-dev
=> fix build requirements for fedora/centos in buiding document

src/hb-ot-cff1-table.hh, src/hb-subset-cff1.cc
Improves subset benchmarks by up to 70% for small CFF1 subset of
non-CID fonts!
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/10                              -0.7067         -0.7071             1             0             1             0
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/64                              -0.4817         -0.4824             1             0             1             0
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/512                             -0.1948         -0.1956             2             2             2             2
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/2000                            -0.0767         -0.0761             6             6             6             6
=> [cff1] Lazy-load & sort glyph names

src/hb-ot-layout-common.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh
This allows for slightly faster filtering in ClassDef/Coverage by avoiding using the gsub glyph set. Gives 1-2% speedup for Noto Nastaliq subsetting.
=> [subset-perf] Cache a glyph map specific to gsub.

src/gen-tag-table.py, src/hb-ot-tag-table.hh
`hb_ot_tags_from_complex_language` had two conditions guarding the sequence of checks that don’t check the language subtag.
The first condition was `limit - lang_str > 5`. I modified it to `limit - lang_str >= 7`. This is because 5 is the minimum length of a relevant language tag excluding the language subtag. The minimum language subtag length is 2. Therefore, the minimum total language tag length is 7. The practical effect is minimal: 6-character tags like `zh-cmn` no longer pass into that block.
The second condition was `(limit - lang_str == 5 && *lang_str == '-')`. That accepts language tags like `-geok`. However, language tags can’t begin with hyphens, so no valid input would ever pass this condition, so I removed it.
I also fixed gen-tag-table.py to add 1 for each subtag’s hyphen, …
=> [ot-tags] Fix `min_subtag_len` calculations

src/hb-priority-queue.hh
Fixes https://oss-fuzz.com/testcase-detail/5148625505746944.
=> [subset] fix fuzzer found underflow when heap push fails.

src/hb-ot-font.cc, src/hb-ot-hmtx-table.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gpos-table.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-ot-var-hvar-table.hh
Fixes issue originally raised in https://github.com/harfbuzz/harfbuzz/pull/2878#issuecomment-785340348
Hi Jonathan,
Can you test this in Firefox and see if it helps with variable font performance?
Thanks
=> Cache varstore

.circleci/config.yml
Fedora 33 is EOL since 2021-11-30, try the latest Fedora release (36).
=> [ci] Fix fedora-valgrind job

src/hb-subset.cc, test/api/test-subset.c
Fixes #3609 
If subsetting a face create by hb_create_for_tables then hb_face_get_table_tags doesn't work. So fallback processing all non-empty tables that are in the list of tables the subsetter can subset and the 'no subset tables' list.
=> [subset] fix subsetting of faces created via hb_face_create_for_tables. 

src/Makefile.am, src/meson.build
Fixes the warnings:
../src/hb-ft.cc:810: Warning: HarfBuzz: hb_ft_face_create: argument ft_face: Unresolved type: 'FT_Face'
../src/hb-ft.cc:886: Warning: HarfBuzz: hb_ft_face_create_cached: argument ft_face: Unresolved type: 'FT_Face'
../src/hb-ft.cc:855: Warning: HarfBuzz: hb_ft_face_create_referenced: argument ft_face: Unresolved type: 'FT_Face'
../src/hb-ft.cc:920: Warning: HarfBuzz: hb_ft_font_create: argument ft_face: Unresolved type: 'FT_Face'
../src/hb-ft.cc:1029: Warning: HarfBuzz: hb_ft_font_create_referenced: argument ft_face: Unresolved type: 'FT_Face'
../src/hb-ft.cc:240: Warning: HarfBuzz: hb_ft_font_get_face: return value: Unresolved type: 'FT_Face'
../src/hb-ft.cc:262: Warning: HarfBuzz: hb_ft_font_lock_face: return value: Unresolved type: 'FT_Face'
=> [gi] Add freetype2-2.0 for g-i-r includes

src/meson.build
It is unlikely to be a developer build in that case.
=> Skip warning when building as subproject and  ragel is missing

src/hb-ft.cc, src/hb-ft.h
New API:
- hb_ft_hb_font_changed()
Mostly reverts 56e0ff9ea129aa91dfcc746cd61f8cbbc427dba7
Related https://github.com/harfbuzz/harfbuzz/issues/2270
Fixes https://github.com/harfbuzz/harfbuzz/issues/3619
=> [ft] Add API to notify that hb_font_t changed

.github/workflows/configs-build.yml, .github/workflows/coverity-scan.yml, .github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml, .github/workflows/msvc-ci.yml, .github/workflows/msys2-ci.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

src/hb-buffer.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-ot-layout.cc, src/hb-ot-layout.hh, src/hb-ot-shaper-indic.cc, src/hb-ot-shaper-khmer.cc, src/hb-ot-shaper-myanmar.cc, src/hb-ot-shaper-syllabic.cc, src/hb-ot-shaper-syllabic.hh, src/hb-ot-shaper-use.cc
[layout] Use a cache for main input ClassDef of ChainContextLookups
I expected this to speed up NotoNastaliqUrdu, but didn't make a dent.
Need to profile on Linux to understand why. But it's mostly because
the cache is only effective when we enter the lookup from the main
loop (apply_forward), but NotoNastaliq mostly recurses...
=> Classdef cache

src/hb-gobject-enums.h.tmpl
These headers are not acceptable to modern compilers.
gcc says things like:
/usr/include/harfbuzz/hb-gobject-enums.h:100:1: warning:
function declaration isn’t a prototype [-Wstrict-prototypes]
100 | hb_gobject_ot_metrics_tag_get_type () G_GNUC_CONST;
=> Fix the generated gobject headers

src/hb-meta.hh, src/hb.hh
Fixes the following Windows warnings seen in Firefox builds:
```
hb-meta.hh(191,5): warning: '__GNUG__' is not defined, evaluates to 0 [-Wundef]
#if __GNUG__ && __GNUC__ < 5
^
```
```
hb.hh(187,10): error: '_USE_MATH_DEFINES' macro redefined [-Werror,-Wmacro-redefined]
^
mozilla-config.h(158,9): note: previous definition is here
#define _USE_MATH_DEFINES 1
^
```
=> Fix Windows build warnings

src/hb-blob.cc
This function will return NULL for the the
empty blob. That is important information for
bindings that treat nullability as a type trait.
=> Fix the annotation for hb_blob_get_data

test/api/test-ot-face.c
Extend testing to cover parts that are missing according to the recent
oss-fuzz-coverage report:
- Retriving all constants from MathConstants.
- Retrieving entries from MathKern, MathGlyphPartRecord and
MathGlyphAssembly.
- Retrieving italic correction from MathGlyphAssembly.
- Choosing between horizontal/vertical offset in MathVariants.
https://storage.googleapis.com/oss-fuzz-coverage/harfbuzz/reports/20220627/linux/src/harfbuzz/src/hb-ot-math-table.hh.html
https://github.com/harfbuzz/harfbuzz/issues/3688
=> [math] Improve fuzzing coverage

src/graph/graph.hh, src/hb-repacker.hh, src/test-repacker.cc
The boring expansion (https://github.com/be-fonts/boring-expansion-spec) plans to introduce 24bit offsets into GSUB/GPOS. This changes the repacker to treat 24 bit offsets similar to 32 bit offsets and assign the top level 24 bit offsets into spaces to improve packing.
=> [subset] Prepare the repacker for handling 24bit offsets in GSUB/GPOS.

src/hb-ot-color.h
Mention that a palette index of 0xFFFF
means to use the foreground color.
=> docs: Clarify 0xFFFF as palette index

src/hb-repacker.hh, src/hb-subset-repacker.cc
Fix for https://github.com/fonttools/fonttools/issues/2691
=> [repacker] Increase max_rounds when called via public api.

src/hb-repacker.hh
Restore max rounds to 20 but don't count space isolation against the limit. The number of iterations space isolation can make changes for is already bounded to a reasonable max (the number of lookups in the font) so no need to cap the number of iterations.
=> [repack] Don't count space isolation against round limit.

src/hb-meta.hh
For whatever reason, em++ takes the first branch and spouts a gazillion warnings like:
```
./harfbuzz/src/hb-vector.hh:229:20: warning: builtin __has_trivial_assign is deprecated; use __is_trivially_assignable instead [-Wdeprecated-builtins]
hb_enable_if (hb_is_trivially_copy_assignable(T))>
^
./harfbuzz/src/hb-meta.hh:193:44: note: expanded from macro 'hb_is_trivially_copy_assignable'
```
=> [meta] Fix warning with emscripten

src/hb-subset-plan.cc
So this just fixed issues in subset_plan.cc, the build is not fine yet. 
I see there're still build issues in hb-shape:
```
FAILED: util/hb-ot-shape-closure 
c++  -o util/hb-ot-shape-closure util/hb-ot-shape-closure.p/hb-ot-shape-closure.cc.o -Wl,--as-needed -Wl,--no-undefined -DHB_NO_VAR=1 '-Wl,-rpath,$ORIGIN/../src' -Wl,-rpath-link,/usr/local/google/home/qxliu/harfbuzz/build/src -Wl,--start-group src/libharfbuzz.so.0.40401.0 /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib/x86_64-linux-gnu/libcairo.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so -Wl,--end-group
/usr/bin/ld: util/hb-ot-shape-closure.p/hb-ot-shape-closure.cc.o: in function `font_options_t::post_parse(_GError**)':
/usr/local/google/home/qxliu/harfbuzz/build/../util/font-options.hh:105: undefined reference to …
```
=> build fix for HB_NO_VAR in hb-subset-plan.cc

src/OT/Layout/GPOS/CursivePosFormat1.hh, src/OT/Layout/GPOS/MarkArray.hh, src/OT/Layout/GPOS/PairPosFormat2.hh, src/OT/Layout/GPOS/PairSet.hh, src/OT/Layout/GPOS/SinglePosFormat1.hh, src/OT/Layout/GPOS/SinglePosFormat2.hh, src/OT/Layout/GSUB/AlternateSet.hh, src/OT/Layout/GSUB/Ligature.hh, src/OT/Layout/GSUB/ReverseChainSingleSubstFormat1.hh, src/OT/Layout/GSUB/Sequence.hh, src/OT/Layout/GSUB/SingleSubstFormat1.hh, src/OT/Layout/GSUB/SingleSubstFormat2.hh, src/hb-debug.hh
Eventually will fix https://github.com/harfbuzz/harfbuzz/issues/2910
@simoncozens how's the proposed message format?
Eg:
```
trace: start lookup 106	buffer: [BehxIni=0|OneDotBelowNS=0|HehMed=1|DalFin=2|AlefSep=3|DalSep=4]
trace: replacing glyph at 2: gid625 -> gid798	buffer: [BehxIni.outD5=0|OneDotBelowNS=0|HehMed=1|DalFin=2|AlefSep=3|DalSep=4]
trace: end lookup 106	buffer: [BehxIni.outD5=0|OneDotBelowNS=0|HehMed.inD5outT1=1|DalFin=2|AlefSep=3|DalSep=4]
```
I opted for leaving out the lookup-type from the message. WDYT?
cc @khaledhosny
=> Towards adding more buffer messages

src/Makefile.am, src/Makefile.sources, src/graph/graph.hh, src/graph/gsubgpos-graph.cc, src/graph/gsubgpos-graph.hh, src/graph/serialize.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-repacker.hh, src/hb-subset-repacker.cc, src/meson.build, src/test-repacker.cc
When enabled analyzes the non-extension lookups within a GSUB/GPOS table and decides if any need to be promoted into extensions prior to space assignemnt.
This is v1 of the algorithm which doesn't factor in shared nodes between lookups.
=> [repacker] Extension promotion mechanism in the repacker

src/gen-harfbuzzcc.py, src/harfbuzz-subset.cc
Using `os.path.basename()` breaks files in subdirectories (`gsubgpos-graph.cc` instead of `graph/gsubgpos-graph.cc`). The relative paths that meson returns look a bit ugly but they still work.
=> [meson] Don’t tamper with paths in amalgam files

src/hb-subset-repacker.cc, src/hb-subset-repacker.h, test/api/test-subset-repacker.c
This is needed to allow table specific optimizations to be performed during repacking.
=> [repacker] Add a second repacker api method which takes a table tag.

meson.build, src/meson.build
To account for both MSVC and clang-cl.
Fixes https://github.com/harfbuzz/harfbuzz/issues/3756
=> [meson] use cpp.get_argument_syntax not cpp.get_id

src/hb-ot-layout-common.hh
I think this is a bug that needs a fix when LONG_WORDS flag is set. Correct me if I'm wrong cause I tried to understand the code according to the spec.
Given below variables defined in the function:
lcount: num of INT 32 deltas
scount: num of INT16 deltas
count: total num of deltas
when LONG_WORDS flag is set, this get_delta() was not working correctly
- the "row" is not computed correctly
- lcursor should be interpreted as INT32
I don't have a testcase for this, but existing tests don't seem to catch this.
=> bug fix in VarData get_delta ()

src/hb-subset-plan.cc, src/hb-subset-plan.hh
Now that object destroy calls the destructor of plan, that can cause problems when destructing its members afterwards.
=> [subset] add destructor to subset plan so it's members destruct before the plan object.

src/hb-ot-layout.cc
Various functions take hb_tag_t arrays. Those
arrays are expected to be 0-terminated. Document
that.
=> docs: Improve docs for some apis

util/helper-cairo.hh
Similar to the logic that detects iterm2, but look for
TERM_PROGRAM=WezTerm which identifies wezterm is present.
This allows hb-view to output an image directly to the terminal.
=> hb-view: Detect WezTerm and use iterm2 image protocol

src/hb-ot-font.cc
Like we do for sbix table.
Fixes https://github.com/harfbuzz/harfbuzz/issues/3827
=> [ot-font] Try CBDT extents before outline tables

src/OT/glyf/Glyph.hh, src/OT/glyf/SubsetGlyph.hh, src/OT/glyf/glyf.hh
When retain gids is enabled the subset plan may require the output of many empty glyphs. This change optimizes the glyf subsetting code when the number of retained glyphs << number of output glyphs. Unnessecary lookups to the glyph map are reduced by iterating through the glyph map instead of the output glyph set.
=> [subset] optimize glyf subsetting w/ retain gids.

src/graph/graph.hh, src/graph/gsubgpos-graph.hh, src/graph/markbasepos-graph.hh, src/graph/pairpos-graph.hh, src/hb-repacker.hh
Also make mutable copies (when needed) of the top level subtables during a split operation.
=> [repacker] use mutable copies of Coverage/ClassDef in MarkBasePos shrink operation.

src/graph/pairpos-graph.hh
During splitting of PairPosFormat2 the code was assuming the maximum size of the generated coverage table would be equal too the current size. This is incorrect size the new coverage table may not preserve the ranges found in the original coverage table (since we are splitting based on class, not coverage) and in the worst case may convert from format2 to format1. So use the size of a format1 table as the max size.
=> [repacker] fix incorrect coverage table size estimation.

perf/benchmark-subset.cc, src/Makefile.sources, src/gen-def.py, src/hb-subset-accelerator.hh, src/hb-subset-input.cc, src/hb-subset-input.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh, src/hb-subset.cc, src/hb-subset.h, src/meson.build, test/subset/run-tests.py, util/hb-subset.cc
The subset accelerator is cached data that can be attached to a hb_face_t and used in subsequent subsetting operations. This allows those subsetting operations to avoid doing things such as collecting the full unicode to gid mapping.
Gives significant speedups of up to 40% in some cases:
BM_subset/subset_glyphs/Roboto-Regular.ttf/10_median                                     -0.2081         -0.2079             0             0             0             0
BM_subset/subset_glyphs/Roboto-Regular.ttf/64_median                                     -0.1231         -0.1226             0             0             0             0
BM_subset/subset_glyphs/Roboto-Regular.ttf/512_median                                    -0.0378         -0.0379             1             1             1             1 …
=> [subset] Begin implementing a subset accelerator

.github/workflows/arm-ci.yml, src/graph/graph.hh, src/hb-ot-layout-common.hh, src/hb-ot-post-table-v2subset.hh, src/hb-ot-var-fvar-table.hh, src/hb-repacker.hh
I've been working with arm-none-eabi recently and trying to build HarfBuzz for it. I was getting a few errors about mismatches between integer types - this makes it build cleanly.
If we want to ensure this doesn't regress I'd be happy to add a CI job for this, but it might end up being a little overspecific based on the toolchain used.
=> Make build work for arm-none-eabi

src/hb-ot-layout-common.hh
The rest of layout subsetting depends on lookup indices being consistent with those computed during planning. So if an empty lookup is discarded during the subset phase it will invalidate all subsequent lookup indices. Generally we shouldn't end up with an empty lookup as we pre-prune them during the planning phase, but it can happen in rare cases such as when a subtable is considered degenerate (eg. #3853)
=> [subset] Always output Lookup's even if they are empty.

src/harfbuzz-config.cmake.in, src/meson.build
The previous code concatenates includedir to _harfbuzz_prefix verbatim, which results in a wrong final include path in case includedir is an absolute path. Instead, we can let meson determine the absolute include and lib paths in advance and save them in the cmake config.
This is an issue in nixpkgs, where includedir is set to the final (absolute) path of the built library in the Nix store, which causes CMake projects depending on harfbuzz to not configure.
See https://github.com/NixOS/nixpkgs/issues/180054.
=> Pass through absolute paths to cmake config directly

src/hb-ft.cc
Clang 16 has got a new stricter warning for casts of function types (see https://github.com/llvm/llvm-project/commit/1aad641c793090b4d036c03e737df2ebe2c32c57).
This new warning gets included as part of the existing error diagnostic setting of -Wcast-function-type.
This fixes errors like these:
```
../src/hb-ft.cc:1011:34: error: cast from 'void (*)(FT_Face)' (aka 'void (*)(FT_FaceRec_ *)') to 'FT_Generic_Finalizer' (aka 'void (*)(void *)') converts to incompatible function type [-Werror,-Wcast-function-type-strict]
ft_face->generic.finalizer = (FT_Generic_Finalizer) hb_ft_face_finalize;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> freetype: Fix function signatures to match without casts

src/hb-map.hh, src/test-map.cc
It was not working when the value type is hb_bytes_t because hb_array_t overloaded operator &
=> fix bug in hb_hashmap_t has() interface

test/subset/data/Makefile.am, test/subset/data/Makefile.sources, test/subset/meson.build
Automatically enable them when the experimental api is enabled.
=> [subset] Include instancing tests in distribution.

meson.build
In #3811 / commit 53a194aa3f5f7de0b40e879e41fcbe0de6e9fefe a broken and half-implemented approach to kind of sort of handling the detection of both pkg-config and cmake names for dependencies, was implemented. It just checked for both versions with required: false, but when the build was configured with *disabled* options, it was still found because it was treated as auto.
Really, the problem here is trying to outsmart Meson, which handles a lot of edge cases correctly. But it's possible, albeit very wordy, to manually implement Meson's internal logic via if/else fallbacks. Do so here.
Fixes failure to build on Gentoo, /cc @thesamesam
Fixes:
https://bugs.gentoo.org/880405
https://bugs.gentoo.org/880479
=> meson: fix regression in detecting freetype2/icu-uc when explicitly disabled

src/hb-subset-input.cc, src/hb-subset-plan.cc, src/hb-subset-plan.hh
=> Avoid use values () in hb-hashmap if value_t has an overriden operator &

src/hb-subset-accelerator.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh, src/hb-subset.cc
Speeds up SourceHanSans-Regular/10000 benchmark by %25.
=> [subset] Cache has_seac in accelerator

src/OT/glyf/glyf.hh, src/hb-subset-input.cc, src/hb-subset-input.hh, src/hb-subset-plan.cc, src/hb-subset-plan.hh
Long loca is needed so that we can store the trimmed glyph bytes to allow us to safely skip trimming in the later subset.
=> [subset] In the preprocess subset call always use long loca.

src/hb-ot-cff1-table.hh, src/hb-ot-cff2-table.hh, src/hb-subset-accelerator.hh, src/hb-subset-cff-common.hh
Gives speed ups across the CFF subsetting benchmarks (up to 45% at large subset sizes):
BM_subset/subset_glyphs/SourceHanSans-Regular_subset.otf/10_median | -3%
BM_subset/subset_glyphs/SourceHanSans-Regular_subset.otf/64_median | -11%
BM_subset/subset_glyphs/SourceHanSans-Regular_subset.otf/512_median | -27%
BM_subset/subset_glyphs/SourceHanSans-Regular_subset.otf/4096_median | -40%
BM_subset/subset_glyphs/SourceHanSans-Regular_subset.otf/10000_median | -44%
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/10_median | -3%
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/64_median | -13%
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/512_median | -35%
BM_subset/subset_glyphs/SourceSansPro-Regular.otf/2000_median | -33%
BM_subset/subset_codepoints/SourceHanSans-Regular_subset.otf/10_med …
=> [subset] Cache parsed char strings in CFF accelerator

src/hb-subset-cff-common.hh
Previously they were being copied in. Copying is no longer necessary now that hint dropping doesn't mutate the arrays. Gives 8% speedup on the large CJK CFF subsetting.
=> [subset] use a reference to cached global/loca subrs.

src/hb-ot-cmap-table.hh, src/hb-subset-accelerator.hh, src/hb-subset.cc
22-27% improvement for the 10 codepoint CFF subsets.
=> [subset] Cache per subtable cmap unicode mappings.

subprojects/freetype2.wrap
Freetype is now at `2.12.1` as per https://gitlab.freedesktop.org/freetype/freetype/-/tags
=> Update freetype subproject to 2.12.1

src/hb-mutex.hh, src/hb-subset-accelerator.hh, src/hb-subset-plan.hh
Big wins all across small subsets
BM_subset/subset_codepoints/Roboto-Regular.ttf/nohinting/10                              -0.1140         -0.1129             0             0             0             0
BM_subset/subset_codepoints/Amiri-Regular.ttf/nohinting/10                               -0.4717         -0.4714             0             0             0             0
BM_subset/subset_codepoints/NotoNastaliqUrdu-Regular.ttf/nohinting/10                    -0.8147         -0.8146             0             0             0             0
BM_subset/subset_codepoints/NotoSansDevanagari-Regular.ttf/nohinting/10                  -0.3248         -0.3242             0             0             0             0
BM_subset/subset_codepoints/Mplus1p-Regular.ttf/nohinting/10                             …
=> [subset] Accelerate sanitize-table-cache

src/hb-ot-cmap-table.hh, src/hb-subset-accelerator.hh, src/hb-subset-cff-common.hh
To prevent unintentional modification while they are used in subsetting operations.
=> [subset] make cff accelerator and cmap cache const

src/hb-ot-cff2-table.hh, src/hb-subset-cff-common.hh, src/hb-subset-cff1.cc
Benchmark                                                                                      Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_subset/subset_codepoints/SourceHanSans-Regular_subset.otf/nohinting/10                   -0.0841         -0.0843             0             0             0             0
BM_subset/subset_codepoints/SourceHanSans-Regular_subset.otf/nohinting/64                   -0.1305         -0.1305             0             0             0             0
BM_subset/subset_codepoints/SourceHanSans-Regular_subset.otf/nohinting/512                  -0.1398 …
=> [subset-cff1] Cache glyph-to-sid-map in the accelerator

src/hb-array.hh, src/hb-subset-cff-common.hh, src/hb-vector.hh
Saves 32% on SourceHanSans/10000 benchmark!
Also, use memcmp now for writing out strings since now that our ops are not super short, that's faster.
This makes cff-japanese test takes super long though; that needs inspection.
=> [subset-cff] Compact parsed strings if using accelerator

src/hb-ot-color-colr-table.hh, src/hb-ot-font.cc, src/hb-ot-layout-common.hh, src/hb-ot-var-common.hh, src/hb-static.cc
This is a first step; ultimatively, we should compute the extents is ClipBoxes are missing.
=> COLRv1: use ClipBoxes for extents

src/OT/glyf/VarCompositeGlyph.hh
msvc is rightfully complaining that the types on the sides of the ternary are not matching:
```
C:\pango\subprojects\harfbuzz\src\OT\glyf\VarCompositeGlyph.hh(317): error C2446: ':': no conversion from 'const OT::HBUINT16' to 'const OT::HBUINT8'
```
=> VarC: properly cast int

src/hb-ot-color-colr-table.hh
The variations are for xMin, yMin, xMAx, yMax.
Apply them before converting to extents..
=> COLRv1: Apply variations correctly

src/meson.build, util/meson.build
With this change, harfbuzz can be consumed as a subproject without making any changes to the build files of a project. All you need to do is provide a wrap file with a `[provide]` section:
https://mesonbuild.com/Wrap-dependency-system-manual.html#provide-section
This is also necessary because otherwise projects need to hard-code the subproject name, which might be `harfbuzz` when using `wrap-git` or `harfbuzz-6.0.0` when using `wrap-file` (to build from a release tarball). This can cause conflicts between different subprojects that consume harfbuzz differently.
Other projects like glib, cairo, pango, etc already do this.
=> meson: Override dependencies to improve usage as a subproject

src/hb-draw.h
Disambiguate the origin of draw_data and user_data, this had me confused a few times.
Fixes: https://github.com/harfbuzz/harfbuzz/issues/3955
=> [draw] Clarify the docs

util/hb-subset.cc
=> [subset] don't segfault when --help-all is specified w/ instancing options.

src/hb-subset-input.cc
The caller of the method is expected to destroy the returned result.
=> [subset] when subsetting preprocessor fails, reference the returned face.

docs/harfbuzz-sections.txt, src/hb-ot-color-colr-table.hh, src/hb-ot-color.cc, src/hb-ot-color.h, test/api/test-ot-color.c, test/api/test-paint.c
See https://github.com/harfbuzz/harfbuzz/issues/3977
There is an unrelated fix for hb_ot_color_has_paint here too, with test.
I can put that in a separate PR if you prefer.
=> Add hb_ot_color_glyph_has_paint

src/hb-ft-colr.hh, src/hb-ot-color-colr-table.hh
Instead of just checking the depth, just count
the number of edges in the graph we've followed,
and give up after 256.
=> [paint] Limit the size of the graph we follow

src/meson.build
Similar to: https://github.com/harfbuzz/harfbuzz/pull/2853
This time, g-ir-scanner is trying to parse system headers for some reason and is giving a gazillion of gibberish warnings. This hack is to prevent it from including macOS system headers:
```
[6/6] Generating src/HarfBuzz-0.0.gir with a custom command (wrapped by meson to set env)
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/os/clock.h:14: syntax error, unexpected ':', expecting identifier or typedef-name or '{' in 'typedef enum : uint32_t { OS_CLOCK_MACH_ABSOLUTE_TIME = 32, } os_clockid_t;' at ':'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dispatch/queue.h:816: syntax error, unexpected ':', expecting …
```
=> [introspection] Fix g-ir-scanner syntax errors on macOS

src/hb-paint-extents.cc
Without these functions excluded from the build, setting `HB_NO_PAINT` will result in these linking errors:
```
"_hb_paint_funcs_create", referenced from:
hb_paint_extents_funcs_lazy_loader_t::create() in libharfbuzz.a(harfbuzz.cc.o)
"_hb_paint_funcs_destroy", referenced from:
hb_paint_extents_get_funcs() in libharfbuzz.a(harfbuzz.cc.o)
free_static_paint_extents_funcs() in libharfbuzz.a(harfbuzz.cc.o)
"_hb_paint_funcs_get_empty", referenced from:
hb_paint_extents_get_funcs() in libharfbuzz.a(harfbuzz.cc.o)
free_static_paint_extents_funcs() in libharfbuzz.a(harfbuzz.cc.o)
"_hb_paint_funcs_make_immutable", referenced from:
hb_paint_extents_funcs_lazy_loader_t::create() in libharfbuzz.a(harfbuzz.cc.o)
"_hb_paint_funcs_set_color_func", referenced from: …
```
=> Disable `hb_paint_extents_*` functions if `HB_NO_PAINT` is defined

src/hb-face.cc
Here's a typo noticed in passing.
And a question: Should you not empty out that static_unicodes set to avoid accumulating memory there?
=> docs: Fix a typo

src/hb-ot-name-table.hh, test/api/test-subset-nameids.c
If a nameRecord with provided name_id/platform_id/encoding_id/lang_id is not retained after subsetting, create it and insert it to the name table. So we need to check against retained name_records rather than name_record in the original name table.
=> [subset] Fix issue in hb_subset_input_override_name_table()

test/api/results/bad-20-0-154, test/api/results/hand-20-0-10, test/api/results/hand-20-0.2-10, test/api/results/test-20-0-10, test/api/results/test-20-0-106, test/api/results/test-20-0-116, test/api/results/test-20-0-123, test/api/results/test-20-0-165, test/api/results/test-20-0-175, test/api/results/test-20-0-6, test/api/results/test-20-0-92, test/api/test-paint.c
This is an attempt to work around rounding differences seen in some of the ci runs, for clipboxes.
=> test-paint: Limit the precision of clip boxes

test/api/test-draw.c
This test compares output between ft and ot font funcs.
It fails. I don't know if that is expected or not, but this is the core of the differences
between paint extent computation for ft and ot.
I believe the difference is due to FreeType scaling the outlines.
=> Draft: Add a draw test

docs/harfbuzz-docs.xml
For whatever reason, GTK-Doc 1.33.1 will not generate HTML files for indices that has these role attributes.
=> [doc] Fix API indices generation

test/threads/hb-subset-threads.cc
This week's `gcc-13` snapshot cleaned further up it's standard headers and exposed missing declaration as a build failure:
../test/threads/hb-subset-threads.cc: In function 'void test_operation(operation_t, const char*, const test_input_t&)':
../test/threads/hb-subset-threads.cc:127:3: error: 'printf' was not declared in this scope
../test/threads/hb-subset-threads.cc: In function 'int main(int, char**)':
../test/threads/hb-subset-threads.cc:157:19: error: 'atoi' was not declared in this scope
=> test/threads/hb-subset-threads.cc: add missing <cstdio> include

src/hb-cairo-utils.cc
Make reversed angles not infloop, and
cap the number of interval repetitions
at 1000.
Fixes: https://github.com/harfbuzz/harfbuzz/issues/4055
=> [hb-cairo] Fixes for sweep gradients

util/hb-info.cc
The output for palette names was mangled.
This commit makes things come out ok.
For flags, we use "Both" when both LIGHT
and DARK are set.
Output before:
```
Index	Flags	Name
---------------------
0	Default palette
1	DarkFirst non-default palette
2	LightSunny colors
Colors:
Index	Name
------------
0	The first color
1	The second color
2	Out of color names
[...]
```
Output after:
```
Index	Flags	Name
---------------------
0	        Default palette
1	Dark    First non-default palette
2	Light   Sunny colors
Colors:
Index	Name
------------
0	The first color
1	The second color
2	Out of color names
[...]
```
=> [hb-info] Fix output for CPAL

meson.build, src/hb-cairo-utils.cc, subprojects/packagefiles/ragel/meson.build, test/api/test-paint.c, util/ansi-print.hh
Revert the exceptions part of:
```
commit 22cbd038d3578c344e265a098fc98ef168f8d18b
Author: Khaled Hosny <khaled@aliftype.com>
Date:   Tue Sep 14 12:34:25 2021 +0200
[meson] Add ragel subproject
```
To get ride of the following warnings:
```
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
```
=> [meson] Try to make MSVC build less spammy

test/api/Makefile.am, test/api/meson.build, test/api/test-glyph-names.c
This verifies that hb_font_get_glyph_name
returns false for nonexisting glyphs.
=> Add a test for glyph names

src/OT/glyf/SubsetGlyph.hh, src/OT/glyf/glyf.hh
Also calculate max_offsets after glyph bytes are compiled, cause byte length of a glyph might change after compile
=> [instancer] fix potential memory leak for compiled glyph bytes

COPYING
This brings the COPYRIGHT file up to date, looking more like what I ended up filling out in Debian's debian/copyright file (the main difference being that the decopy script put names into alphabetical order, which I'm happy to do for harfbuzz if you'd like).
Adobe, Inc has copyright in src/hb-subset-cff*, test/api/test-subset*, and misc other places.
Ebrahim Byagowi has copyright as far back as 2015 in places like src/hb-directwrite.cc.
Google, Inc has newer copyright into 2022 in places like src/graph/test-classdef-graph.cc. Also, listing every year was getting a bit unwieldy, so just do 2010-2022.
Igalia S.L. contributed the stuff in src/hb-ot-math*.
The only references I could find to Martin Hosken & SIL were in src/hb-graphite2*, and they were 2011, not 2009.
Mozilla's got a bunch of …
=> [COPYING] Another update

meson.build, src/hb-cairo-utils.cc, src/hb-cairo.cc
Use the new cairo_user_scaled_font_get_foreground_color to obtain the foreground color, since the cr's source can't be trusted.
Requires https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/420
=> hb-cairo: Fix handling of foreground color

src/hb-ot-cmap-table.hh, src/hb-ot-font.cc
Use the cmap cache for get_nominal_glyph and
get_variation_glyph as well. The first of these
is used a lot in pango.
=> [ot-font] Use the cmap cache more

src/hb-subset-plan.cc
Fixed a bug caused by typo. When finding duplicate features, we should use feature substitutes if they exist.
I'll see if I can generate a small test for it. Current file is too large, but once I subset it down, the issue disappeared.
=> [instancer] bug fix

src/hb-blob.cc, src/hb-mutex.hh
Without the additions, building for the Microsoft GDK fails, since it's assumed to be UWP.
I found that GLAD performs a similar check:
```
#if !WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
#define GLAD_PLATFORM_UWP 1
#endif
```
=> Use proper preprocessor checks for UWP

src/meson.build
Pass --experimental-api to all gen-def.py when generating all .def files, not only harfbuzz.def.
Fixes https://github.com/harfbuzz/harfbuzz/issues/4117
=> [meson] Fix test failure with experimental_api

src/hb-shape.cc
When expanding/shrinking the buffer to max (and still not fitting), we need to also set var_value to the axis max/min otherwise client not have the correct axis value to draw with.
=> [justify] Set var_value when expanding/shrinking to max

.github/workflows/linux-ci.yml, docs/meson.build, meson_options.txt
It slows build as it causes documentation to be always rebuilt. We now disable it by default and enable it on relevant CI jobs.
=> [docs] Disable gtdoc-check by default

src/hb-common.cc
Tifinagh can be written RTL as well as LTR. Without support from Harfbuzz this causes weird reordering problems (see https://github.com/notofonts/tifinagh/issues/17).
=> Add Tifinagh to list of both-directions scripts

src/OT/glyf/glyf.hh
The iterator in this loop is a map iterator so glyphs are not necessarily traveresed in order.
=> [subset] don't free glyphs by range.

src/hb-outline.cc
This file contains an extra blank line in the copyright header, which is different from other HarfBuzz source files.
Flutter uses a script that parses the source of its dependencies in order to collect licenses.  This inconsistency is causing issues for the script.
=> Remove extra blank line in hb-outline.cc

src/hb-subset-plan.hh
Lock variable must have a name or it will immediately destruct.
=> [subset] fix incorrectly specified lock.

.github/workflows/cifuzz.yml
Fixes #4190.
As mentioned in the issue, this PR adds read-only token permissions to the cifuzz.yml workflow, making it compatible with the other workflows (they were fixed in #3639). This reduces the risk of supply-chain attacks on the project.
=>  Add read-only top-level permissions to cifuzz.yml

meson.build, meson_options.txt
Adds the missing utilities option to meson builds for parity with CMake builds
See also: https://github.com/harfbuzz/harfbuzz/blob/main/CMakeLists.txt#L53
=> meson: add an option to disable utilities building

src/hb-buffer.cc
```cpp
void
hb_buffer_t::similar (const hb_buffer_t &src)
{
hb_unicode_funcs_destroy (unicode);
unicode = hb_unicode_funcs_reference (src.unicode);
flags = src.flags;
cluster_level = src.cluster_level;
replacement = src.invisible; // <- this should be src.replacement
invisible = src.invisible;
not_found = src.not_found;
}
```
=> [buffer] fix `hb_buffer_t::similar` setting `replacement` to `src.invisible`

src/OT/Layout/GSUB/Ligature.hh, src/OT/Layout/GSUB/LigatureSet.hh
Match the first component of the ligature in the LigatureSet loop.
Speeds up Roboto shaping by 25%. I don't think it breaks anything. The test suite seems happy.
=> [Ligature] Speed up

src/hb-ot-math.cc
Simple typo in the documentation of the hb_ot_math_get_constant() function of hb-ot-math.
The 3rd percent constant is HB_OT_MATH_CONSTANT_RADICAL_DEGREE_BOTTOM_RAISE_PERCENT and not HB_OT_MATH_CONSTANT_SCRIPT_PERCENT_SCALE_DOWN.
=> Typo in the documentation of hb-ot-math

src/OT/glyf/Glyph.hh, src/hb-ot-hmtx-table.hh, src/hb-subset-plan-member-list.hh, src/hb-subset-plan.cc
Is faster.
Part of https://github.com/harfbuzz/harfbuzz/issues/4231
=> [subset] Use vector instead of map for glyph bounds

src/harfbuzz-config.cmake.in
Hi,
This attempts to improve the CMake config file that is generated during the autotools/Meson builds so that the CMake config file is usable under Windows as well, with the appropriate library prefixes and suffixes.
Note: Sadly I lost access to my former account `fanc999`.
=> harfbuzz-config.cmake.in: Support Windows usage

src/OT/glyf/SubsetGlyph.hh
Mplus benchmark:
```
Benchmark                                                                      Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------------------------------
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/10                   -0.1764         -0.1771             0             0             0             0
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/64                   -0.1394         -0.1394             0             0             0             0
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/512                  -0.0644         -0.0645             0             0 …
```
=> [subset/regaingid/glyf] Add a fastpath for empty glyphs

src/Makefile.am, src/hb-ot-var-common.hh, src/hb-ot-var-cvar-table.hh, src/hb-subset-instancer-solver.hh, src/meson.build, src/test-tuple-varstore.cc
- add merge_tuple_variations (), this is not covered by unit test yet.
- fix the issue in hashmap usage: use axis tag as the hashmap key instead of axis index, this makes remove_axis and set_tent faster
- add unit test for change_tuple_variation_axis_limits (). Test is still cvar only,  currently gvar is not supported cause we don't have code to unpack shared_tuples yet. will work on it later.
=> [instancer] change tuple variations' axis limits

.github/workflows/arm-ci.yml, .github/workflows/cifuzz.yml, .github/workflows/configs-build.yml, .github/workflows/coverity-scan.yml, .github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml, .github/workflows/msvc-ci.yml, .github/workflows/msys2-ci.yml
See #4273.
This PR hash-pins all Actions in your workflows, transforming `actions/checkout@v3` into `actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2`. This is the commit SHA associated with the most recent version of the Action.
Note that the Actions are called by their commit SHA, but we also have the associated version tag in a comment. Dependabot is already set up to keep Actions up-to-date. It will continue to do so, and it will update both the hash and the version comment. (To see some examples, check out the [pull requests on my fork](https://github.com/pnacht/harfbuzz/pulls), when I hash-pinned some Actions to outdated versions)
So whenever the new version of `hendrikmuhs/ccache-action` comes out, you'll receive a dependabot PR with
```diff
- …
```
=> Pin Actions by commit SHA

src/hb-ot-var-common.hh, src/hb-ot-var-cvar-table.hh, src/test-tuple-varstore.cc
1. Added code to compile tuple_variations_t into bytes, also added unit testing code for it.
- compile all points_set and store the bytes data in a hashmap in tuple_variations_t, cause some points_set could be reused
- compile deltas and tuple variation header for each tuple_delta_t, bytes stored within each tuple
- shared_tuples not supported yet
2. Added subset()/serialize() method in TupleVariationData and cvar for instantiating cvar table, this is not covered by test yet, I'll add a full test once gvar is supported.
=> [instancer] compile tuple variations

src/hb-ot-shaper-use-machine.rl
The part of the USE spec corresponding to hb-ot-shaper-use-machine.rl’s `consonant_modifiers` is `(CMAbv)* (CMBlw)* (< H B [VS] | SUB > (CMAbv)* (CMBlw)*)*`, so multiple CMAbv glyphs should be allowed after a subjoined glyph.
=> [use] Allow multiple CMAbv glyphs on subjoined

.github/workflows/scorecard.yml, README.md
Fixes #4296.
This PR adds the Scorecard Action to harfbuzz. The Action monitors the project's security posture and makes suggestions when applicable.
As-is, the Action will run using the workflow's default GITHUB_TOKEN. This works just fine. However, there are a few datapoints that are useful for the Branch-Protection and (optional) Webhooks checks that aren't accessible with the default token. If you wish, you can instead create a fine-grained personal access token and Scorecard will use it to fetch the relevant info to strengthen the branch protection and webhooks checks. This is entirely optional; if you'd rather just use the GITHUB_TOKEN, just merge the workflow as-is!
I've taken the liberty of adding a badge showing the project's current Scorecard score to the README. Let me know if …
=> Add Scorecard action

src/OT/Layout/GPOS/AnchorFormat3.hh, src/OT/Layout/GPOS/AnchorMatrix.hh, src/OT/Layout/GPOS/MarkArray.hh, src/OT/Layout/GPOS/SinglePosFormat1.hh, src/OT/Layout/GPOS/SinglePosFormat2.hh, src/OT/Layout/GPOS/ValueFormat.hh, src/hb-kern.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-ot-layout.cc, src/hb-ot-shaper-arabic-fallback.hh, src/hb-sanitize.hh
This speeds up face loading for variable fonts by average 80%!
```
Benchmark                                                                          Time             CPU      Time Old      Time New       CPU Old       CPU New
---------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_Font/load_face_and_shape/Roboto-Regular.ttf/hb                               -0.1248         -0.1203            22            19            22            19
BM_Font/load_face_and_shape/RobotoFlex-Variable.ttf/hb                          -0.7018         -0.7026            77            23            77            23
BM_Font/load_face_and_shape/RobotoFlex-Variable.ttf/var/hb …
```
=> GPOS lazy Device

src/hb-sanitize.hh
Assumptions...
Speeds up Gulzar load_face_and_shape benchmark by 7%.
=> [sanitize] Only check trailing edge of ranges

src/graph/classdef-graph.hh, src/graph/coverage-graph.hh, src/graph/graph.hh, src/graph/gsubgpos-graph.hh, src/graph/pairpos-graph.hh
In some fonts, for example Noto Duployan-Regular, nodes can have over a thousand parents... Speed up.
=> [graph] Use a hb_map_t to keep parents, instead of hb_vector_t

src/hb-ot-shape.cc, test/shape/data/in-house/tests/automatic-fractions.tests
HarfBuzz automatically applies fraction features to any instance of U+2044 plus any decimal digits that precede or follow it. However, [_The Unicode Standard_, version 15.0, chapter 6](https://www.unicode.org/versions/Unicode15.0.0/ch06.pdf#page=21) says “The standard form of a fraction built using the fraction slash is defined as follows: any sequence of one or more decimal digits (General Category = Nd), followed by the fraction slash, followed by any sequence of one or more decimal digits.” That is, there must be at least one digit in the numerator and at least one digit in the denominator.
=> Require numerators and denominators in automatic fractions

.github/workflows/msys2-ci.yml
FreeType pulls in HarfBuzz package, and the linker seems to get confused and sometimes pick that up instead of the build HarfBuzz DLL. This causes random failures in the bots.
See eg.:
https://github.com/harfbuzz/harfbuzz/pull/4350
https://github.com/harfbuzz/harfbuzz/pull/4353
=> [ci/msys] Don't install freetype

src/graph/graph.hh, src/graph/gsubgpos-context.hh, src/graph/gsubgpos-graph.hh, src/hb-repacker.hh, src/test-repacker.cc
See: https://github.com/fonttools/fonttools/issues/3260
This font has huge number of subtables, but many are de-dupped. This fixes the repacking failure by ensuring that created extension subtables are shared where possible.
=> [repacker] fix case of failing repacker.

src/hb-repacker.hh
During table splitting we iterate over the lookups map which can be modified during table splitting. This can result in a use after free in the iterator. Create a local copy of the lookup indices to avoid this.
=> [repacker] fix potential use after free in repacker.

src/hb-ot-var-common.hh, src/hb-vector.hh
Building with clang complains about the use of `tuple_variations_t`'s implicit copy constructor and copy assignment operator, since automatic generation of these is deprecated when declaring a non-default destructor. This is a good warning because it isn't obvious that copies were being made instead of the object being moved and this struct should be moved and not copied. Declare all the special member functions, defaulting the moves and deleting the copies.
After making `tuple_variations_t` move only, an issue is revealed in `hb_vector_t::push` which has been requiring that objects be copyable. Remove the old non-emplacing `push` now that this works with all existing objects and make a single `push` which is more like `std::vector::emplace_back` since that is somewhat what the newer …
=> Specify tuple_variations_t special member functions

meson.build, src/meson.build, subprojects/.gitignore
Hi all!
Coming here from mesonbuild/wrapdb#1137. This is a PR to apply all the fixes I needed to make Harfbuzz build with [Microsoft Clang](https://llvm.org/docs/GettingStartedVS.html).
I found many bits where the common behavioural assumption "Visual Studio == MSVC" did not hold, which causes several compile-time errors with compilers but that use the Microsoft STL. These are explained in the individual commit messages-
Please let me know what you think.
=> Fix building with Microsoft Clang

src/hb-ot-var-cvar-table.hh, src/hb-subset.cc
In the same vein as #3736, this fixes compilation when in `HB_NO_VAR` mode.
I’m not familiar with the code, so I hope I didn’t `#ifndef` out too much or too little code.
=> HB_NO_VAR: Fix build, drop fvar, avar, cvar, MVAR tables from subsets

src/hb-map.hh, src/hb-vector.hh
First of all, I want to thank you for your work on compatibility with quite old compilers!
At work, I happen to use a rather ancient environment & compiler: 
- `gcc --version`: `gcc (Debian 4.9.2-10) 4.9.2` 
- `gcc -dumpmachine`: `arm-linux-gnueabihf`
- `uname -srmio`: `Linux 4.1.15-g14db131-dirty armv7l unknown GNU/Linux`. 
When trying to compile the latest sources (current latest commit: https://github.com/harfbuzz/harfbuzz/commit/b8121ccbb687dc853118e81810cc0565ce0037d4) I encountered several compilation errors, which I tried to solve in this pull request. Next, I describe the errors that occurred (in the order they occurred) and the way to solve them.
I build `harfbuzz` with pre-build `freetype` and `icu` with (deprecated) CMake in the next way:
``` shell
$ cmake ../harfbuzz \
-G …
```
=> Added minor fixes to build without errors with gcc 4.9.2

src/hb-ot-var-common.hh, src/hb-ot-var-hvar-table.hh, src/hb-ot-var-mvar-table.hh, src/test-item-varstore.cc
1. It's possible that region lists become empty after instantiation(e.g deltas become all zeros). Return true in this case. And varStore serialize() call will return false if regions are empty.
2.  add an API which does create (), instantiate tuple vars(), and as_item_varstore() together, and update MVAR and HVAR code to call this API instead.
=> [instancer] try to simplify item_variation_t API calls

src/graph/graph.hh, src/hb-ot-var-common.hh, src/hb-priority-queue.hh, src/test-priority-queue.cc
when instantiating varstore, we need to pop a tuple like (combined_gain, i, j), if combined gain is the same then we compare the value of i, and then j. So we'd like to use custom type as the key when popping from the queue. This would match fonttool's algorithm cause it uses heappop(): https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/varLib/varStore.py#L586
I'll add a test for this later(in another PR that I'm still working on)
=> [instancer] templatize the priority queue, use custom type for varstore

src/relative_to.py
The shebang `/usr/bin/python3` assumes python3 is installed in /usr/bin, which isn't always true (e.g., in the manylinux docker image).  Using `/usr/bin/env python3` uses the python3 that is in the path, which is more flexible.
=> Change the shebang used for python

src/hb-ft.cc
What is the right way to automatically generate clickable URLs in gtk-doc? Will this work: `<https://some.url/>`?
=> [docs] Fixed links to freetype FT_LOAD_XXX flags

src/hb-subset-input.cc
Closes: https://github.com/harfbuzz/harfbuzz/issues/4451
=> [subset] keep East Asian spacing vhal, halt, chws, vchw by default

util/hb-subset.cc
Remove note about partial instancing not being supported. Add --variations flag as an alternate name for --instance. This matches other hb utils. Fixes #4462
=> [instancer] Update help message for --instance.

docs/harfbuzz-sections.txt, src/gen-def.py, src/hb-subset-input.cc, src/hb-subset.h, util/Makefile.sources, util/hb-subset.cc, util/helper-subset.hh, util/meson.build, util/test-hb-subset-parsing.c
When parsing axis positions in the --variations flag recognize empty values as meaning the existing value for that part. For example:
:300:500
Specifies min = existing, def = 300, max = 500.
See: https://github.com/fonttools/fonttools/issues/3322
Need to add tests before merging this.
=> [instancer] add the option to leave blanks in the min:def:max syntax.

src/hb-blob.cc
To fix #4511 the filename will be interpreted as UTF-8 on Windows. If the filename is **NOT** valid UTF-8, it will be interpreted according to the system codepage (as before).
The API description of both, `hb_blob_create_from_file_or_fail` and `hb_blob_create_from_file`, was changed to mention how the filename is interpreted on Windows.
=> Adjust function hb_blob_create_from_file_or_fail

src/graph/graph.hh, src/hb-repacker.hh, src/test-repacker.cc
This improves handling of overflow resolution to shared nodes, particularly for cases where the shared node has a large number of incoming overflowing links. These cases are capable of being resolved by the existing implementation, but require a large number of iterations to do so.
Instead of applying duplications one link at a time, duplicate and move multiple links on each iteration. This uses the same approach that was successful for space assignment: move all overflowing links to their own new duplicate.
=> [repacker] Improve resolution of overflows to shared nodes.

.circleci/config.yml
Looks like newer versions of python disable pip for system-managed installations. This should unbreak alpine job and prevent other jobs from potentially breaking in the future.
=> [circleci] Run pip inside a virtual environment

src/hb-subset-plan.cc
```
In file included from hb-subset-plan.hh:30:0,
from hb-subset-plan.cc:27:
hb-subset-plan.cc: In function 'void _update_instance_metrics_map_from_cff2(hb_subset_plan_t*)':
hb-subset-plan.cc:998:81: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
if (unlikely (!plan->check_success (font = _get_hb_font_with_variations (plan))))
^
hb.hh:263:25: note: in definition of macro 'unlikely'
#define unlikely(expr) (expr)
^
```
Fixes: https://github.com/harfbuzz/harfbuzz/issues/4545
=> hb-subset-plan.cc: Fix -Wparentheses warning.

src/hb-object.hh, src/hb-ot-cff1-table.hh
This minor mismatch is detected by new `-Wcalloc-transposed-args` `gcc-14` warning as:
In file included from ../src/hb-subset-plan.cc:38:
../src/hb-ot-cff1-table.hh: In member function 'bool OT::cff1::accelerator_t::get_glyph_from_name(const char*, int, hb_codepoint_t*) const':
../src/hb-ot-cff1-table.hh:1419:60: warning: 'void* calloc(size_t, size_t)' sizes specified with 'sizeof' in the earlier argument and not in the later argument [-Wcalloc-transposed-args]
1419 |         names = (hb_sorted_vector_t<gname_t> *) hb_calloc (sizeof (hb_sorted_vector_t<gname_t>), 1);
|                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> use `calloc(nmemb, size)`, not `calloc(size, nmemb)`

meson.build
sets `/std:c++14` as opposed to `-std=c++14`, also restricts the check to only happen when `cpp_std=c++11` so when consumed as a subproject overriding the `cpp_std` of harfbuzz doesnt produce any warning at all.
meson 1.3.0 has support for `cpp_std=c++14,c++11` but thats quite a new version...
=> set msvc style flag std when building with clang-cl

src/hb-directwrite.cc
clang-cl defines `__clang__`, but not `__GNUC__`.
clang-cl is `#pragma GCC diagnostic` aware.
Without this change, clang-cl would emit a fatal error in my build -Werror,-Wcast-function-type on the cast from FARPROC to t_DWriteCreateFactory.
=> Disable Wcast-function-type on clang-cl, too

src/hb-ot-var-avar-table.hh
This fixes a warning from clang-tidy:
warning: std::move of the variable 'mapping' of the trivially-copyable
type 'AxisValueMap' has no effect [performance-move-const-arg]
=> Remove unnecessary std::move().

CMakeLists.txt
The existing way of working used in this file was deprecated in cmake 3.12 and a new way supplied.
See https://cmake.org/cmake/help/latest/policy/CMP0148.html
=> cmake: Switch to `find_package(Python3)`.

src/meson.build
Hi,
This PR fixes a linking error when using `clang-cl` or `clang` as supplied by Visual Studio. PE-COFF cannot export extern, non-`dllexport` symbols in shared libraries, a case which is already handled for MSVC itself, but the check in `compiled_tests` does not consider one of the three Microsoft-supplied compilers.
I've also clarified the `TODO`s so as to list the underlying reason.
=> [meson] Block uses of hb-static throughout Microsoft compilers

test/api/test-ot-math.c
The removed lines are redundant. These should have been added due to a slip.
=> fix(test-ot-math.c): remove redundant lines

src/OT/glyf/glyf-helpers.hh, src/hb-common.cc, src/hb-font.hh, src/hb-ot-shaper-arabic.cc, src/hb-ot-tag.cc
All warning are for format specifiers (-WFormat) in sprintf().
Test: Compile only
=> Fixing compiler warnings

src/graph/classdef-graph.hh, src/graph/pairpos-graph.hh, src/graph/test-classdef-graph.cc, src/test-repacker.cc
The existing implementation was not correctly computing the final serialized sizes of class def tables. It was computing an approximate incremental size increase based only on the next class to be added. I've update the estimator to keep a running total for the current split. This allows the format to switch back and forth as needed.
To confirm the new implementation is correct I updated the tests to compare to actual classdef serialization sizes.
=> [repacker] Rework how ClassDef sizes are estimated during splitting. 

src/OT/glyf/glyf-helpers.hh, src/hb-common.cc, src/hb-common.h, src/hb-font.hh, src/hb-ot-shaper-arabic.cc, src/hb-ot-tag.cc, src/hb.hh
This is a modified and cleaned-up version of PR #4619 by @jpcomito: hb-common.h now expects 'inttypes.h' presence with MSVC exceptions, defines __STDC_FORMAT_MACROS in there (if not already defined) and undoes c930ae2 (PR #1974) and 902ab86.
=> Use inttypes.h PRI?32 macros in format strings for [u]int32_t args.

configure.ac, meson.build, test/api/hb-test.h
Bumps minimum required versions for glib and cairo in configure.ac:
glib2 >= 2.30 is needed for g_unicode_script_from_iso15924() and
g_unicode_script_to_iso15924(), and cairo >= 1.10 is needed for the
new cairo_operator_t members like CAIRO_OPERATOR_SCREEN. It also
defines g_assert_false and g_assert_nonnull for old glib2 versions
in hb-test.h (like it is done for g_assert_true.)
For meson: It doesn't check versions at all. It walks through a lot of
weirdness when a requirement isn't found, so I didn't touch it as I am
not proficient with it.
For cmake: It doesn't check versions at all. It is weirdly written, so
I didn't touch it as I am not very proficient with it..
Reference issue: https://github.com/harfbuzz/harfbuzz/issues/4577
Reference issue: …
=> Bump minimum required versions for glib and cairo in configure.ac.

src/gen-tag-table.py, src/hb-ot-tag-table.hh
Commit dd3c858f84105021cf1e427399b971bf26dde8b3 split `ot_languages` into `ot_languages2` and `ot_languages3`, with `hb_ot_tag_to_language` giving priority to the former. This means some two-letter tags no longer need special cases in `hb_ot_ambiguous_tag_to_language`. For example, the OpenType tag 'ARA ' corresponds to the BCP 47 tag `ar`, which used to need a special case because it alphabetically follows `aao` (Algerian Saharan Arabic), but not anymore.
=> Recognize the disambiguation priority of `ot_languages2`

src/hb-ot-layout-base-table.hh
https://learn.microsoft.com/en-us/typography/opentype/spec/base#baselangsysrecord-1
=> [subset] Offsets in BaseLangSysRecord are relative to the parent table and not the BaseLangSysRecord.

src/OT/Color/COLR/COLR.hh, src/OT/Color/COLR/colrv1-closure.hh, src/OT/Layout/GDEF/GDEF.hh, src/hb-subset-plan-member-list.hh, src/hb-subset-plan.cc
Step 1 for subsetting/instantiating COLRv1: collect variation indices and generate inner_maps for subsetting usage(currently COLRv1 subsetting copies varStore as is).
Also merged 2 remap_variation_indices() APIs used by GDEF and BASE into 1, it will be used by COLRv1 as well.
=> [subset] collect variation indices for COLRv1

.github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml
Use setup-python action which which I think uses venv so pip install will not fail as now installing system-wide packages with pip is disallowed.
=> [ci] Try to fix pip install on macOS runner

src/hb-subset-cff2.cc
=> [instancer] add a warning for CFF partial instancing

src/hb-ot-var-common.hh, src/hb-subset-instancer-iup.cc, test/subset/meson.build
- Slightly increase the tolerance to account for differences in floating point math across platforms.
- The specific issue is a fused multiply add (d = d1 + (x - x1) * scale; in hb-subset-instancer-iup.cc)
- Also fix more implicit double conversion warnings.
=> Fix IUP differences accoss platforms.

subprojects/packagefiles/ragel/meson.build
When cross compiling it will build a target (host) binary that can't be run on the building machine.
Also remove the install flag which is not compatible with the native flag, but the custom built ragel is correctly picked.
=> [meson] build ragel as a native tool

src/hb-aat-layout-common.hh, src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout-morx-table.hh
Shows 5% speedup in en-words test case with Helvetica Neue.
=> [aat] For short words, use buffer digest to skip morx / kerx subtables

meson.build
Hi,
The Meson build files were updated lately to look for FreeType with a minimum version requirement, but then that broke the dependency search with CMake as FreeType's pkg-config files used a different versioning scheme.  This updates the Meson build files to account for that for CMake.
=> Meson: Use actual FreeType version when using CMake

CMakeLists.txt
ICU 75.1 requires C++17 support so use `find_package(ICU)` which determines the versioning. Sets `CMAKE_CXX_STANDARD` when that happens.
Follows along with what Meson build did in 93d58f83.
=> Use find_package for ICU

test/api/test-buffer.c, test/api/test-unicode.c
Clean up tests using deprecated API
- HB_BUFFER_FLAGS_DEFAULT
- HB_SCRIPT_CANADIAN_ABORIGINAL
=> clean up tests using deprecated api

src/hb-subset-plan.cc
For #4762. This just fixes the issue with variations related code in subset plan, there're still issues with the HB_TINY build. linker failure and unused variable warnings
e.g:
```
[3/170] Linking target src/libharfbuzz-cairo.so.0.60850.0
FAILED: src/libharfbuzz-cairo.so.0.60850.0 
cc  -o src/libharfbuzz-cairo.so.0.60850.0 src/libharfbuzz-cairo.so.0.60850.0.p/hb-cairo.cc.o src/libharfbuzz-cairo.so.0.60850.0.p/hb-cairo-utils.cc.o src/libharfbuzz-cairo.so.0.60850.0.p/hb-static.cc.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libharfbuzz-cairo.so.0 -Bsymbolic-functions '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/usr/local/google/home/qxliu/harfbuzz/tiny/src src/libharfbuzz.so.0.60850.0 -lm /usr/lib/x86_64-linux-gnu/libcairo.so -Wl,--end-group
/usr/bin/ld: …
```
=> fix build with HB_TINY

src/hb-subset-cff2.cc
For #4776 . Don't print from the library.
=> [instancer] remove the warning for CFF partial instancing

meson.build
Hi,
This brings PR #4734 to also work with Visual Studio as it expects `/std:c++17` and does not understand `-std=c++17`, so that builds on Visual Studio against ICU >= 75.x will work without passing `-Dcpp_std=c++17` in the Meson setup command line.
=> meson: Fix builds against ICU >= 75.x on Visual Studio

docs/harfbuzz-sections.txt, src/hb-coretext.cc, src/hb-face-builder.cc, src/hb-face.cc, src/hb-face.h, src/hb-face.hh, src/hb-ft.cc, test/api/meson.build, test/api/test-get-table-tags.c
New API:
+hb_get_table_tags_func_t
+hb_face_set_get_table_tags_func()
Towards fixing https://github.com/harfbuzz/harfbuzz/issues/4821
To be implemented by face-builder, FreeType, and CoreText backends.
=> [face] Add get_table_tags callback

src/hb-style.cc
I asked Wolthera regarding their comment in https://wolthera.info/2024/07/making-sense-of-font-selection/
> Finally, some fonts have a [STAT](https://learn.microsoft.com/en-us/typography/opentype/spec/stat) table, which gives even more info about those axes (if a variable font) and allows for non-variable families to describe their relations in an axis like manner. There’s no API to retrieve this info in Harfbuzz, however, FontConfig knows nothing about it either, and even the CSS working group hasn’t made any statements on whether to interpret the STAT table at all.
and they gave me comprehensive feedback regarding the API which the first part was the documentation that can be improved as apparently it wasn't apparent to them that the API is able to deal with STAT also.
They also gave me …
=> [style][doc] Mention explicitly it goes through STAT table

src/hb-ot-layout-common.hh
From https://github.com/fonttools/fonttools/pull/3617
See: https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae
The spec says they are expected to be in the font-specific name ID range (256–32767), though that is not a requirement in this Feature Parameters specification.
=> [subset] remove unnecessary check on name IDs

test/subset/run-tests.py
One problematic input is `--instance=wdth=112.5` which is parsed using the users local (`strtof`).
So while in C or US locales it yields 112.5 in some European locales it yields 112 as the dot is not valid in this position.
A European user might pass "112,5" instead but for the test the C locale is assumed, so enforce it.
Fixes #4854
If the parameter is intended to be always in C-locale format then an alternative would be to use `hb_parse_double` but that is a hidden symbol not available to the subset binary, or use a temporary C locale as in `hb_variation_to_string`
=> Run subset tests with C-locale

meson_options.txt, src/meson.build
Building harfbuzz when targeting Android API<=20 would need libstdc++ due to lack of uselocale and freelocale in C library but present in libstdc++.
Or we could use `cc.has_function` in top level `meson.build` since we are not using C++ linker but checking function presence with C++ linker, which would cause link failure in this case.
=> [meson] Add back with_libstdcxx build option

src/hb-draw.h
With clang build, I got:
FAILED: test/api/test-draw.p/test-draw.c.o
clang -Itest/api/test-draw.p -Itest/api -I../test/api -I. -I.. -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/freetype2 -I/usr/include/libpng16 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -DHAVE_CONFIG_H -Wall -Wextra -Werror -pthread -MD -MQ test/api/test-draw.p/test-draw.c.o -MF test/api/test-draw.p/test-draw.c.o.d -o test/api/test-draw.p/test-draw.c.o -c ../test/api/test-draw.c ../test/api/test-draw.c:920:26: error: missing field 'reserved4' initializer [-Werror,-Wmissing-field-initializers]
hb_draw_state_t st = HB_DRAW_STATE_DEFAULT;
^
../src/hb-draw.h:73:71: note: expanded from macro 'HB_DRAW_STATE_DEFAULT' …
=> missing-field-initializers in hb-draw.h

src/main.cc
FAILED: src/main.p/main.cc.o
clang++ -Isrc/main.p -Isrc -I../src -I. -I.. -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sysprof-6 -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++11 -fno-exceptions -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -Wall -Wextra -Werror -pthread -Wno-non-virtual-dtor -UNDEBUG -MD -MQ src/main.p/main.cc.o -MF src/main.p/main.cc.o.d -o src/main.p/main.cc.o -c ../src/main.cc ../src/main.cc:220:33: error: missing field 'y_bearing' initializer [-Werror,-Wmissing-field-initializers]
hb_glyph_extents_t extents = {0};
^
../src/main.cc:270:36: error: missing field 'y_bearing' …
=> missing-field-initializers in main.cc

test/api/test-ot-face.c
FAILED: test/fuzzing/hb-shape-fuzzer.p/hb-shape-fuzzer.cc.o clang++ -Itest/fuzzing/hb-shape-fuzzer.p -Itest/fuzzing -I../test/fuzzing -I. -I.. -Isrc -I../src -fdiagnostics-color=always -D_GLIBCXX_ASSERTIONS=1 -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c++11 -fno-exceptions -O3 -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -Wall -Wextra -Werror -MD -MQ test/fuzzing/hb-shape-fuzzer.p/hb-shape-fuzzer.cc.o -MF test/fuzzing/hb-shape-fuzzer.p/hb-shape-fuzzer.cc.o.d -o test/fuzzing/hb-shape-fuzzer.p/hb-shape-fuzzer.cc.o -c ../test/fuzzing/hb-shape-fuzzer.cc In file included from ../test/fuzzing/hb-shape-fuzzer.cc:9: ../test/fuzzing/../api/test-ot-face.c:47:34: error: missing field 'y_bearing' initializer [-Werror,-Wmissing-field-initializers] …
=> missing-field-initializers in test/api/test-ot-face.c

test/fuzzing/hb-draw-fuzzer.cc
../test/fuzzing/hb-draw-fuzzer.cc:19:28: error: unused parameter 'dfuncs' [-Werror,-Wunused-parameter] _move_to (hb_draw_funcs_t *dfuncs, void *draw_data_,
^
../test/fuzzing/hb-draw-fuzzer.cc:22:10: error: unused parameter 'user_data' [-Werror,-Wunused-parameter]
void *user_data)
^
../test/fuzzing/hb-draw-fuzzer.cc:31:28: error: unused parameter 'dfuncs' [-Werror,-Wunused-parameter] _line_to (hb_draw_funcs_t *dfuncs, void *draw_data_,
^
../test/fuzzing/hb-draw-fuzzer.cc:34:10: error: unused parameter 'user_data' [-Werror,-Wunused-parameter]
void *user_data)
^
../test/fuzzing/hb-draw-fuzzer.cc:44:33: error: unused parameter 'dfuncs' [-Werror,-Wunused-parameter] _quadratic_to (hb_draw_funcs_t *dfuncs, void *draw_data_,
^
../test/fuzzing/hb-draw-fuzzer.cc:46:15: error: unused parameter …
=> unused-parameter in test/fuzzing/hb-draw-fuzzer.cc

.github/workflows/linux-ci.yml, .github/workflows/macos-ci.yml
Setup a repository token and use it, this seems to be required now.
=> [ci] Fix Codecov upload

.github/workflows/macos-ci.yml
It seems that lxml does not have 3.13 binary wheels (for macOS at least), and building it from source is failing.
=> [ci] Pin Python version to 3.12 on macOS

.circleci/config.yml, subprojects/cairo.wrap, subprojects/freetype2.wrap, subprojects/glib.wrap, subprojects/google-benchmark.wrap
This also updates the meson version on Windows cross-build jobs as wraps now requires newer versions of meson. We still require only meson 0.55.0 for building HarfBuzz, but building with fallback wraps is allowed to require newer meson.
=> [meson] Update wrap files

.github/workflows/macos-ci.yml
It seems that Homebrew now packages an alternative implementation of pkg-config called pkgconf and some of the packages we install depend on it, and installing both pkgconf and pkg-config is not supported.
Looks like pkgconf can’t find dependencies for us, so we do some brew unlink/link dance to get both installed, and hope for the best.
=> [ci] Try to fix macOS build

src/harfbuzz-config.cmake.in, src/meson.build
Hi all!
As a follow-up to mesonbuild/meson#13959, I've tried to fix the underlying issue. Please find attached a possible fix for the error described in the linked ticket (tl;dr: meson is unable to recognize harfbuzz's version because it's not set in the cmake config file, which ultimately causes issues when building freetype with harfbuzz support enabled).
Happy to answer any questions that come up!
=> set harfbuzz version in cmake config file

src/hb-ot-layout-gsubgpos.hh
When either casting a signed integer to an unsigned one or subtracting a value from an unsigned one, add assertions to verify we will not end up below expected bounds.
This tracks the extra assertions added to Rustybuzz in https://github.com/harfbuzz/rustybuzz/pull/146 subsequent to having found a bogus type casting in the Rust port via https://github.com/harfbuzz/rustybuzz/issues/142.
=> [gsubgpos] Guard integer arithmetic against wrapping below zero

src/hb-null.hh
With `-Wnontrivial-memaccess`, recent versions of clang flag the usage of memcpy in hb-null.hh with pointers to nontrivially-copyable types. Sidestep this warning by casting the problematic pointer to `void*`.
=> Sidestep nontrivial-memaccess warning in Crap()

test/shape/hb_test_tools.py
The `cgi` module was removed in Python 3.13.
=> Make hb_test_tools.py work in Python 3.13

src/hb-coretext-font.cc
define kCTFont* when unavailable, i.e. ios < 6.0, macOS < 10.8 or tvOS < 9.0. MAC_OS_X_VERSION_MIN_REQUIRED is always defined in AvailabilityMacros.h for all targets, while __ENVIRONMENT_*_VERSION_MIN_REQUIRED__ is defined by compiler when building a specific target
=> [coretext]: fix tvOS build

src/hb-subset-serialize.h
gtk-doc is rather sensitive to white space, and it does not seem to be able to parse bare `unsigned` without `int`.
=> [subset-serialize] Fix doc generation

CMakeLists.txt
Building the main harfbuzz library for an iOS target is now possible. To achieve this, the `BUILD_SHARED_LIBS` option needs to be explicitly set to OFF at line 12 of the project's CMakeLists.txt (please ignore the comment I falsely written...)
```bash
cmake -S. -B _build -DBUILD_FRAMEWORK=ON -DCMAKE_SYSTEM_NAME=iOS -H. 
sudo cmake --build _build --config Release --target install -- CODE_SIGNING_ALLOWED=NO
```
This configuration will build the harfbuzz library as a static library, and will not build the libharfbuzz-subset library.
Building with `BUILD_SHARED_LIBS` enabled results in a compilation failure in `hb-coretext-font.cc` when targeting iOS due to issues with dynamic library linking on the platform.
=> Add support for Apple framework builds

docs/usermanual-integration.xml
As extensively discussed and documented in #1484, Core Text does not operate in 96 DPI. Core Text doesn't actually have a concept of DPI internally, as it doesn't rasterize anything by itself, it just generates vector paths that get passed along to Core Graphics.
In practice this means Core Text operates in the classical macOS logical DPI of 72, with one typographic point corresponding to one point in the Core Graphics coordinate system, which for a normal bitmap context then corresponds to one pixel -- or two pixels for a "retina" context with a 2x scale transform.
As of f401f85a5a3ec4ab9c28012a0bfe713d7ee96951, we no longer apply any assumptions in HB about the target DPI being different than the 72 DPI used by CT, for example to account for the Web's standard of 96 DPI, so let's remove …
=> Remove outdated documentation note about CT operating in 96 DPI

src/hb-aat-layout-common.hh, src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout-morx-table.hh, src/hb-ot-kern-table.hh
Use a set of all left glyphs participating in kerning, and all right glyphs participating in kerning, and use these two to weed out non-kerning pairs before bsearching into the kerns.
Speeds up shaping of HelveticaNeue by ~10%.
=> [kern/kerx] Use hb-set-t for left/right, to guard bsearch & remove aat buffer-digest code

src/hb-aat-layout-common.hh, src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout-morx-table.hh
It has a lot of small chains, many of them for Hebrew, or other scripts. But using the buffer-digest, for all buffers, not only short ones, we can skip such subchains.
=> [aat] Speed up Lucida Grande among others

src/hb-face.cc, src/hb-face.h, test/api/test-font.c
If referencing the face blob is not possible (e.g. not implemented by the font functions), use face builder to create a blob out of individual table blobs.
Fixes https://github.com/harfbuzz/harfbuzz/issues/5036
=> [face] Add fallback implementation to hb_face_reference_blob

src/hb-aat-layout-common.hh, src/hb-aat-layout-kerx-table.hh, src/hb-aat-layout-morx-table.hh, src/hb-bit-page.hh
And match them against the buffer glyph_set.
4% speedup in LucidaGrande. 12% in Times.
=> [morx] Only collect glyphs that can initiate action in the machine

src/hb-aat-layout-trak-table.hh, src/hb-aat-layout.cc, src/hb-aat-layout.hh, src/hb-coretext-shape.cc, src/hb-ft.cc, src/hb-ot-font.cc, src/hb-ot-shape.cc, src/hb-ot-shape.hh
This is what CoreText does.  Before, trak was double-applied with `--shaper-ot --font-funcs=coretext`.
Fixes https://github.com/harfbuzz/harfbuzz/issues/5049
=> [ot-font/trak] Move trak application to ot-font instead of ot-shape

src/hb-bit-set.hh
Allocation 2-page sets as exact count as well.
Don't do the same for the page_map.
@garretrieger Any chance you can measure if this has any effect on the subset benchmarks? Thanks.
=> [set] Tweak allocation

src/OT/Color/COLR/COLR.hh, src/OT/Var/VARC/VARC.cc, src/OT/Var/VARC/VARC.hh, src/hb-decycler.hh, src/hb-ft-colr.hh, src/hb.hh, src/meson.build, src/test-decycler.cc
This is an algorithm I came up with, based on the Floyd's
Tortoise-Hare constant-memory linear-time linked-list cycle-detection
algorithm. It is linear-time and malloc-free. It *eventually* detects
cycles, not immediately.
https://en.wikipedia.org/wiki/Cycle_detection#Floyd's_tortoise_and_hare
The main different with Floyd's algorithm is that this algorithm
detects cycles when one is traversing down a graph, not just a
linked list.
Our existing cycle-detection algorithms use a set-of-integers,
either hb_set_t, or more efficient in this case, hb_map_t. Those
include at least one malloc, and as such show up on profiles.
Port hb-ot-font COLRv1 to use the decycler instead of previous
hb_map_t usage for cycle detection.
benchmark-font paint_glyph on NotoColorEmoji-Regular.ttf:
Before: 8ms; …
=> [decycler] Implement an efficient graph cycle detector

meson.build
Simplify and respect -Dfreetype=disabled again.
Bug: https://bugs.gentoo.org/950274
Fixes: 1ad48fddd08654052da4f8a93609e7f4380d5c42
See-Also: 604fe807078ce41d0ac7742547e90b17c066709f
@eli-schwartz
=> meson: refactor freetype dependency logic

meson.build
No idea why it was there to begin with. We control warnings from hb.hh.
=> [meson] Remove -Wno-non-virtual-dtor

src/hb-coretext-font.cc
Clang analyzer found a little memory leak when updating!
=> Fix memory leak in hb_coretext_get_glyph_name

src/fontations/lib.rs
- **Banish static lifetimes**
- **"where" not needed for trait impl**
=> Two small Rust tidyups

.circleci/config.yml
Alpine is frequently failing with compiler crashing, but we don’t really need Alpine. No other job building with --buildtype=minsize, so keep it but use Ubuntu.
=> [ci] Port minsize job from Alpine to Ubuntu

src/hb-common.cc
Clarify that the serialized forms of features and variations won't have any whitespace in them. This can help for parsing when embedding these strings into larger serializations.
=> Improve docs for feature and variation serialization

docs/harfbuzz-sections.txt, src/fontations/lib.rs, src/hb-common.cc, src/hb-common.h, src/hb-static.cc, src/hb.hh
Going to close. Just leaving here for the future.
It requires making `hb_malloc` etc public. Which would have no purpose for us as is.
=> [fontations] Make fontations use hb_malloc et al

src/hb-bit-set.hh, src/hb-vector.hh
Was shrinking malloced vectors inadverently.
=> [set] Fix reallocation

src/OT/Color/COLR/COLR.hh, src/hb-font.hh, src/hb-ft.cc
So it applies to all font-funcs.
=> [font] Move synthetic glyph extents into font layer

src/hb-coretext-shape.cc
Even when at default, looks like this is necessary.
Fixes https://github.com/harfbuzz/harfbuzz/issues/5142
=> [coretext] Always set all variations

.ci/build-win32.sh, .ci/build-win64.sh, subprojects/libffi.wrap
To fix failing CI runs because freedesktop.org is down.
=> [ci] Add libffi warp with fallback download URL

src/hb-coretext.cc, util/font-options.hh
Needs tests...
TTC indices > 0 can't be loaded with CoreText API it seems.
Fixes https://github.com/harfbuzz/harfbuzz/issues/5158
=> [coretext] Fix loading named instances

src/fontations/Cargo.lock, src/fontations/Cargo.toml, src/fontations/lib.rs
Reduces one Vec use.
https://github.com/googlefonts/fontations/pull/1419
Needs to wait for a Skrifa merge & release.
=> [fontations] Use the proposed pop_layer_with_mode

.ci/build-win.sh, README.md, README.mingw.md
It got deleted in cf1fdf1632d26cb30bf718396a3189a5f1cf1519 but it is still useful. Needs to be updated to meson world, though.
=> [doc] Restore README.mingw.md

src/OT/Layout/GDEF/GDEF.hh
Don't return false in case of a Hinting Device table. 
Unfortunately I didn't find a testcase for this.
=> [subset] bug fix for CaretValueFormat3

src/hb-subset.cc
Not needed now that we are checking accelerator validity.
=> [subset] remove CFF/CFF2 table presence checks.

src/hb-font.hh, src/hb-ft.cc
1. The floor/ceil was being applied in the wrong order for y direction.
2. If the scale is negative, the floor/ceil should be reversed.
Just round them instead. That's what coretext / directwrite / fontations font-funcs do.
=> [ot/ft] Round glyph extents instead of floor/ceil

docs/harfbuzz-sections.txt, src/gen-def.py, src/hb-subset.cc, src/hb-subset.h, test/api/test-subset.c
These methods allow retrieving the entire charstrings index structure from a CFF or CFF2 table.
=> [subset] Add hb_subset_cff_get_all_charstrings_data and hb_subset_cff2_get_all_charstrings_data.

src/OT/Var/VARC/VARC.cc, src/hb-atomic.hh, src/hb-ot-layout-common.hh, src/hb-ot-layout-gsubgpos.hh, src/hb-ot-layout.cc, src/hb-ot-shape.cc, src/hb-subset-plan.cc
Last remaining alloc during shaping is gone!
Fixes https://github.com/harfbuzz/harfbuzz/issues/5237
=> [shape] Use font-data for GDEF varStore cache

src/hb-coretext.cc
```
../src/hb-coretext.cc:202:62: warning: format specifies type 'int' but the argument has type 'unsigned int' [-Wformat]
202 |     DEBUG_MSG (CORETEXT, blob, "TTC index %d not supported", ttc_index);
|                                           ~~                 ^~~~~~~~~
|                                           %u
../src/hb-coretext.cc:417:65: warning: format specifies type 'int' but the argument has type 'unsigned int' [-Wformat]
417 |     DEBUG_MSG (CORETEXT, nullptr, "TTC index %d not supported", ttc_index);
|                                              ~~                 ^~~~~~~~~
|                                              %u
```
=> [coretext] Fix -Wformat warning

.github/workflows/linux-ci.yml
Generating manpages is not tested on any CI jobs otherwise.
=> [ci] Install help2man on the linux-ci workflow

test/api/meson.build, test/api/test-ot-math.c
Avoids the unnecessary dependency on FreeType.
=> [test/ot-math] Port to use hb_test_open_font_file()

src/hb-ot-layout-common.hh
Protects against incorrectly accessing rows[0] when rows is empty.
=> In OT::VarData::Serialize don't attempt to serialize an empty set of rows.

meson.build, src/meson.build
Hi there, this is just a small cleanup to remove some of the repeated messages and warnings in the Meson build output. The first change just suppresses the repeated (about 20) calls to `Fetching value of define "_MSC_FULL_VER" : (undefined)` when compiling for Windows, while the second gets rid of `src/meson.build:850: WARNING: Project targets '>= 0.60.0' but uses feature introduced in '1.3.0': fs.relative_to.` by checking the Meson version directly in the if statements enclosing them.
The third is for a more serious issue: `src/meson.build:1055: DEPRECATION: Project uses feature that was always broken, and is now deprecated since '1.3.0': str.format: Value other than strings, integers, bools, options, dictionaries and lists thereof..` However, the only way to get the actual paths for a …
=> [meson] Clean up warnings and fix usage of file objects

src/OT/Color/COLR/COLR.hh, src/harfbuzz-subset.cc, src/harfbuzz.cc, src/hb-draw.cc, src/hb-draw.hh, src/hb-font.hh, src/hb-ft-colr.hh, src/hb-paint-bounded.cc, src/hb-paint-bounded.hh, src/hb-paint-extents.cc, src/meson.build, test/api/results-paint/test-106, test/api/results-paint/test-116, test/api/results-paint/testvf-106, test/api/results-paint/testvf-116
Implement boundedness calculator separately from bounds calculator. Is many times faster for COLRv1 fonts without clipbox.
=> [COLRv1] `paint-bounds`

.github/workflows/msys2-ci.yml
Upstream is dropping it, and mingw-w64-i686-icu package is already gone.
https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages
https://github.com/msys2/MINGW-packages/discussions/19326
=> [ci/msys2] Drop mingw32 build

CMakeLists.txt
Adds 2 missing sources to the cmakelist that caused cmake building to fail.
=> [cmake] Fix missing sources

test/subset/data/tests/cmap4_overflow.tests, test/subset/run-tests.py
The test file has been stripped of most tables to avoid checking in a very large font (since it has a high number of codepoints), which causes OTS to fail on missing required tables.
=> Disable OTS on the cmap4 overflow test case.

CMakeLists.txt
- followup to recent change 2b5f244639079d91233662a00a3c3e149aa1be9a
=> [CMake] remove unused hb-ot-shape-closure

CMakeLists.txt
This practically reverts commit ac92ed7d6875374451246a2391859fb763329adb:
minimum required cmake version is more than new enough.
=> cmake: always set inline hidden flag.

src/meson.build
The failing-alloc.c file is appended to various hb_sources_* as a string, but on >= 1.4.0 we call full_path() on the sources, and this works only with file objects.
=> [meson] Fix build with -Dfuzzer_ldflags on meson >= 1.4.0

CMakeLists.txt
> Specific issues are reported at [#5372 ](https://github.com/harfbuzz/harfbuzz/issues/5372)
**Problem Analysis:**
1. **COFF section limit exceeded** - Windows object files (COFF format) have a hard limit of 65,535 sections. The harfbuzz.cc source generates 33,788 sections, approaching this limit.
2. **Large file size** - The temporary assembly file (ccwnO9s0.s) exceeds the assembler's handling capacity.
**Solution:**
Enable the `-mbig-obj` option for MinGW
=> Fixes "too many sections"

src/OT/Layout/GSUB/LigatureSet.hh, src/graph/classdef-graph.hh, src/graph/coverage-graph.hh, src/graph/graph.hh, src/graph/gsubgpos-graph.hh, src/graph/ligature-graph.hh, src/graph/pairpos-graph.hh, src/graph/serialize.hh, src/hb-repacker.hh, src/test-repacker.cc
Ran into cases where fonts (eg. symbol fonts) with large number of ligatures are overflowing LigatureSubst subtables. This adds support for splitting them to resolve overflows.
Also fixes a bug with handling of node duplication where there are virtual links (LigatureSubst's use virtual links to enforce ordering of the coverage table).
=> [repacker] Implement table splitting for LigatureSubst

CMakeLists.txt
When using HB_HAVE_DIRECTWRITE=ON then we get linker error:
harfbuzz.cc.obj : error LNK2019: unresolved external symbol __imp_DWriteCreateFactory referenced in function "public: __cdecl hb_directwrite_global_t::hb_directwrite_global_t(void)" (??0hb_directwrite_global_t@@QEAA@XZ)
Added linking to dwrite.lib on Windows.
=> CMakeLists.txt + HB_HAVE_DIRECTWRITE=ON : linker error on Windows : 'unresolved external symbol __imp_DWriteCreateFactory'

src/OT/glyf/Glyph.hh
Callers of get_extents_without_var_scaled assume it will set extents if it has returned true.
=> [VARC] fix potential unitialized value use in get_extents_without_var_scaled.

src/OT/Var/VARC/VARC.cc, src/OT/Var/VARC/VARC.hh, src/hb-config.hh
I didn't remove it from `HB_NO_BORING_EXPANSION`; just out of `HB_EXPERIMENTAL_API`. I'm not sure what to do. for AVAR2, we removed it from both, making it survive anyone disabling boring-expansion using `HB_NO_BORING_EXPANSION`. The idea was that Apple shipped avar2, so it's not a boring-expansion project anymore...
=> [VARC] Graduate out of experimental

src/hb-ot-font.cc
Fixes errors/warnings under MSVC:
```
../src/hb-ot-font.cc(681): error C4146: unary minus operator applied to unsigned type, result still unsigned
../src/hb-ot-font.cc(705): error C4146: unary minus operator applied to unsigned type, result still unsigned
../src/hb-ot-font.cc(748): error C4146: unary minus operator applied to unsigned type, result still unsigned
../src/hb-ot-font.cc(782): error C4146: unary minus operator applied to unsigned type, result still unsigned
```
=> Fix unary minus operator applied to unsigned type, result still unsigned

src/OT/Color/CPAL/CPAL.hh, src/hb-bit-page.hh, src/hb-iter.hh, src/hb-ot-cff-common.hh, src/hb-ot-layout-common.hh, src/hb-serialize.hh
Would move multiple times otherwise, if passed an rvalue reference.
=> Remove std::forward inside loops

.github/workflows/linux.yml, RELEASING.md, src/check-release-notes.py, src/meson.build
Add a script to extract the release notes from the NEWS files and use them when creating GitHub releases, so that we don’t need to copy them manually.
Add also a test to make sure the NEWS file always have release notes for the current release.
=> [ci] Add a script to extract release notes from NEWS file

docs/usermanual-getting-started.xml
`A simple shaping example` accidentally uses `buffer` instead of `buf` in a single line.
=> Make example variable names consistent

src/OT/Layout/Common/Coverage.hh, src/hb-cache.hh
Before, our cache.set was always failing for NOT_COVERED, making the cache ineffective for uncovered glyphs. Fix that.
Some nice speedups in Latin fonts.
```
Benchmark                                                                         Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/ot                +0.0006         +0.0006            80            80            80            80
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/ot                          -0.0060         -0.0059            96            96 …
```
=> [Coverage] Cache NOT_COVERED effectively

src/OT/Layout/GSUB/Ligature.hh, src/OT/Layout/GSUB/LigatureSet.hh, src/OT/Layout/GSUB/LigatureSubstFormat1.hh
```
Benchmark                                                                         Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/ot                +0.0154         +0.0158            80            81            79            80
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/ot                          +0.0136         +0.0133            96            98            96            97
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/ot                           +0.0085         +0.0087            38            38 …
```
=> [ligature] Add a set-digest on the second component

src/hb-set-digest.hh
```
Benchmark                                                                         Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------------
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-thelittleprince.txt/ot                -0.0105         -0.0107            82            81            81            81
BM_Shape/NotoNastaliqUrdu-Regular.ttf/fa-words.txt/ot                          +0.0005         +0.0004            96            97            96            96
BM_Shape/Amiri-Regular.ttf/fa-thelittleprince.txt/ot                           -0.0224         -0.0220            39            38 …
```
=> [set-digest] Branch-free may_have

src/hb-set-digest.hh
This reverts commit a4d4c41023dd738d35f2e917d8deea2b473a38aa.
That commit had slowed down clang by 3% while sped up gcc by 3%. Revert, to keep the code *intention* clear. Rely on compiler to avoid branches if it sees fit.
=> Revert "[set-digest] Branch-free tests (#5469)"

src/hb-buffer.cc
Makes failing infinite-recursion fonts and stuff much faster.
=> [buffer] Consume ops in shift_forward

src/hb-ot-math-table.hh
As discussed in #4653, the workaround for Cambria Math is not working since `get_constant` returns a scaled version of `displayOperatorMinHeight` and `delimitedSubFormulaMinHeight`. Replace with a direct lookup to `minHeight`.
=> [ot-math] Fix constant scaling when checking if the font is Cambria Math

src/hb-coretext-font.cc, src/hb-coretext.cc
Comparing a CFIndex with an unsigned int results in a compilation error on iOS armv7 targets:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -Isrc/libharfbuzz.a.p -Isrc -I../src -I. -I.. -I/Volumes/External/videolanci/builds/vCi6yJP3/0/robUx4/vlc/contrib/armv7-iphoneos/include/freetype2 -I/Volumes/External/videolanci/builds/vCi6yJP3/0/robUx4/vlc/contrib/armv7-iphoneos/include -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++11 -fno-exceptions -O2 -g -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -DHAVE_CONFIG_H -mios-version-min=9.0 -arch armv7 -isysroot …
```
=> [coretext] fix unsigned integer comparison

src/hb-ot-var-hvar-table.hh
Sorry I realized that I missed to delete this line in previous PR. We always generate AdvMap in HB.
=> [subset] always generate AdvMap

meson.build, subprojects/icu.wrap
The wrap switched from the transitional `icu-uc = icuuc_dep` syntax to the recommended `dependency_names = icu-uc`, which apparently breaks our fallback path because we pass a `components:` argument to `dependency()` for CMake.  Use a separate `dependency()` invocation to look for a fallback.
=> meson: Fix fallback to WrapDB ICU wrap >= 77.1-3
