- src/hb-private.hh
Based on patch from Björn Breitmeyer
> Fix build on WEC2013

- src/hb-buffer.cc
- src/hb-common.cc
With those small fixes Python bindings are mostly usable.
> More ntrospection fixes

- .travis.yml
Now it passes http://lint.travis-ci.org/
> Fix Travis CI config to pass again

- src/hb-buffer.cc
- src/hb-common.cc
- src/hb-face.cc
- src/hb-font.cc
- src/hb-font.h
- src/hb-ft.cc
- src/hb-glib.cc
- src/hb-gobject-structs.h
- src/hb-ot-font.cc
- src/hb-ot-layout.cc
- src/hb-ot-shape.cc
- src/hb-set.cc
- src/hb-shape-plan.cc
- src/hb-shape.cc
- src/hb-unicode.cc
- src/hb-unicode.h
Based on data from http://upstream-tracker.org/versions/harfbuzz.html
Resolves #103
> Fix "Since:" tags

- .travis.yml
Fixes https://github.com/behdad/harfbuzz/issues/182
> [travis] Enable Mac OS X support

- src/hb-ot-shape-complex-arabic.cc
This aims to make Syriac Abbr Mark sizing more accurate when repeating segments are used, by adding an extra repeat and tightening up the spacing slightly rather than leaving a shortfall corresponding to a partial repeat-width.
> [issue 191] Make apply_stch() give a more precise fit

- docs/harfbuzz-sections.txt
- src/hb-buffer-serialize.cc
- src/hb-buffer.cc
- src/hb-buffer.h
- src/hb-shape.cc
Almost complete, sans reviewing the text of course.
> [docs] More buffers documentation

- src/hb-graphite2.cc
This PR refactors the algorithms that convert Graphites position based glyphs to Harfbuzz's advance+offset. This algorithm handles Nastaliq overlap much better by causing all the negative movement into the space glyph rather than creating lots of offset drift. It has been tested in sile successfully.
> Refactor graphite2 to make ovleraps into negative width spaces

- docs/Makefile.am
- docs/harfbuzz-docs.xml
- docs/usermanual-clusters.xml
I pulled the mailing-list discussion of cluster-level behavior into a docbook file.  Only very small additions made, to incorporate introductory material, plus miscellaneous cleanup, including @khaledhosny 's correction to example listing.
> Add usermanual chapter on cluster levels

- src/hb-ot-tag.cc
This is rebased version of #168 with the commits squashed together.
> Update opentype language tags

- src/sample.py
Reverts behdad/harfbuzz#271
See comments on https://github.com/behdad/harfbuzz/pull/271
> Revert "use utf32"

- src/hb-coretext.cc
Fixes https://github.com/behdad/harfbuzz/issues/267
> Discard reconfigured CTFont if URL changes

- test/api/Makefile.am
This is needed to make "make distcheck" work for me.
> Remove inexistent file ttx file from test/api/Makefile.am

- src/hb-ot-shape-complex-use.cc
AFAICT, this should resolve #381.
> [use] Special-case Chakma split-vowel decomp in the USE shaper.

- win32/config-msvc.mak
Lets see what CI thinks about this.
> Make UCDN default enabled (fixes #389)

- src/hb-ot-tag.cc
- test/api/test-ot-tag.c
Resolves https://github.com/behdad/harfbuzz/issues/324
> Update language tags to OpenType 1.8.1

- test/api/test-font.c
Coverity IDs: 141039, 141040, 141041
> test: Fix some memory leaks in test-font.c

- appveyor.yml
> [ci] Fix Windows CI

- src/hb-ot-map-private.hh
See https://bugzilla.mozilla.org/show_bug.cgi?id=1336600
> avoid UBSan warning in get_stage_lookups

- test/shaping/README.md
@khaledhosny, currently it is `make test`, should be `make check`.
> Minor doc fix: `make check` runs the tests

- src/Makefile.am
https://github.com/behdad/harfbuzz/issues/455
> Use absolute paths of ragel generated headers

- src/hb-graphite2.cc
This PR fixes a bug in converting data from graphite structures to harfbuzz structures for rtl segments.
> Graphite2 bug fix for rtl

- CMakeLists.txt
Marking another symbol as advanced and some formatting
> [cmake] minor

- src/hb-ot-shape-complex-indic.cc
Of course a more reliable method is needed but well, in the meanwhile…
> Unbreak arm-none-eabi build again

- src/hb-graphite2.cc
> Fix missing xscale in rtl graphite unpacking

- BUILD.md
@behdad: have a look at the rest also
> Minor BUILD.md fix

- .circleci/config.yml
- src/hb-buffer-private.hh
- src/hb-buffer.cc
- src/hb-open-file-private.hh
Does the src/hb-* modifications make sense?
> Enable PSVita (arm-none-eabi) compile again and add it to CI

- .ci/deploy-docs.sh
This would do the trick I guess.
> Copy dummy docs/circle.yml to gh-pages branch

- .circleci/config.yml
- CMakeLists.txt
- appveyor.yml
- test/CMakeLists.txt
- test/api/CMakeLists.txt
- test/api/Makefile.am
- test/api/hb-test.h
- test/api/test-c.c
CMake is not my thing, but this seems to work.
> Add API tests to cmake builds

- .ci/deploy-docs.sh
- .ci/run-coveralls.sh
- .travis.yml
Use a matrix to avoid a gazillion if's.
> [ci] Sort out Travis configuration

- .circleci/config.yml
Not a super useful bot I guess but has interesting compile warnings https://circleci.com/gh/ebraminio/harfbuzz/374
Btw, main.exe result of harfbuzz compile really works on a dosbox.
WDYT?
> [ci] Add a DOS/djgpp compiler

- .circleci/config.yml
- test/Makefile.am
- test/api/Makefile.am
> [cmake] Enable cmake tests on distribution and test it

- .circleci/config.yml
- CMakeLists.txt
- autogen.sh
- src/Makefile.am
- src/check-defs.sh
- src/check-header-guards.sh
- src/check-libstdc++.sh
- src/check-static-inits.sh
- src/check-symbols.sh
- test/fuzzing/CMakeLists.txt
Some of #678 and https://github.com/harfbuzz/harfbuzz/pull/675#discussion-diff-159685424R7
> Improve tests

- .circleci/config.yml
- CMakeLists.txt
- test/shaping/CMakeLists.txt
Hmm, but why isatty is detected on macOS but couldn't be used?
> [cmake] Add header existence tests

- test/shaping/run-tests.py
The CTest issue is reported here https://gitlab.kitware.com/cmake/cmake/issues/17630 and I marked the places stderr was used buffer in case that bug is fixed.
> [test] Better tests output by converting stderr to stdout

- .circleci/config.yml
- .travis.yml
> [ci] unbreak bots with outdated freetype version

- CMakeLists.txt
> [cmake] unistd typo fix

- util/hb-subset.cc
> [subset] Fix Windows issue on endlines

- test/api/test-subset.c
https://developer.gnome.org/glib/stable/glib-Testing.html#g-assert-cmpmem
> [test] Fix test-subset on old distros

- src/hb-open-type-private.hh
Fix clang issues https://travis-ci.org/harfbuzz/harfbuzz/jobs/339669946#L1472 and https://travis-ci.org/harfbuzz/harfbuzz/jobs/339669947#L2249 so Travis will be revived hopefully.
> Fix cast warnings with clang

- src/hb-subset-glyf.cc
- src/hb-subset-plan.cc
- src/hb-subset.cc
> Favor use of static instead HB_INTERNAL

- src/hb-gobject-structs.h
TBR: @behdad 
Not sure about the naming just want to bring back some of the bots.
> fix gobject compile issue

- .circleci/config.yml
- test/subset/CMakeLists.txt
> Install fonttools on distcheck bot and enable cmake hb-subset test

- .travis.yml
- configure.ac
- src/Makefile.am
@behdad, not exactly an expert on autotools, is this even a correct path? Should I use AS_IF here?
> Add --with-stdcpp for ossfuzzer and mupdf use

- src/Makefile.am
This brings all the bots, [hopefully], yay! Of course this part can be refactored to look better.
> Fix symbol exporting issue on MINGW

- configure.ac
- src/Makefile.am
Also improve wording a bit and fix make check in `--with-libstdc++=yes`.
> Rename --with-stdcpp → --with-libstdc++

- src/Makefile.am
> Another attempt on fixing the tests on Travis

- .travis.yml
- appveyor.yml
Travis has made lots of noise recently, https://lists.freedesktop.org/archives/harfbuzz/2018-February/006399.html
> Redirect email notifications to another mailing list dedicated for this

- configure.ac
- src/Makefile.am
- src/harfbuzz-config.cmake.in
> autoconf: provide a harfbuzz-config for use from CMake

- CMakeLists.txt
- src/Makefile.am
- src/Makefile.sources
- src/hb-version.h
Probably needs Cmake updates.
https://github.com/harfbuzz/harfbuzz/issues/817
> Include hb-version.h in git

- .ci/fail.sh
https://github.com/harfbuzz/harfbuzz/pull/821#issuecomment-368116538
>  Workaround for old automake on Travis Linux images

- .circleci/config.yml
> [ci] Add clang O3/O0 testers

- src/Makefile.sources
- src/hb-aat-layout-ankr-table.hh
- src/hb-aat-layout-kerx-table.hh
- src/hb-aat-layout.cc
- src/hb-ot-layout-private.hh
- src/hb-ot-layout.cc
Needed for kerx, https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6ankr.html
> [aat] Implement ankr

- src/dev-run.sh
- src/hb-aat-layout-trak-table.hh
- src/hb-aat-layout.cc
- util/options.hh
harfbuzz really works beautifully :)
See also #816, #808
> [aat] trak sanitization

- src/hb-ot-colr-table.hh
I guess with this, COLR implementation can be considered something useful.
> [COLR] More sanitization

- src/Makefile.sources
- src/hb-ot-color-colr-table.hh
- src/hb-ot-color-cpal-table.hh
- src/hb-ot-color.cc
- src/hb-ot-layout.cc
> [ot-color] Move the related tables to hb-ot-color-*

- configure.ac
- m4/ax_code_coverage.m4
- src/Makefile.am
> Enable coverage test on autotools

- src/hb-directwrite.cc
It now compiles on GCC also but msys2 needs to be patched like this https://github.com/Alexpux/mingw-w64/pull/5
> [dwrite] GCC/mingw/msys2 compatibility

- configure.ac
- m4/ax_check_link_flag.m4
Complementary to #889 (#883), uploaded separately to see if bots are OK.
> Do feature test before adding -Bsymbolic-functions

- .circleci/config.yml
- src/hb-open-file-private.hh
- src/hb-ot-glyf-table.hh
- src/hb-ot-kern-table.hh
> Fix llvm-gcc-4.2 compile issue and add a macOS bot to test it

- src/hb-private.hh
(Please see discussion at commit 86a0ac2 for more details for re-adding
this patch.)
> hb-private.hh: Add fallback implementation for round()

- src/hb-aat-layout-fmtx-table.hh
- src/hb-aat-layout-trak-table.hh
- src/hb-aat-layout.cc
Fixes #908. Tested manually against Skia to see if the data is located there.
> [aat/fmtx] Implement the table parsing

- src/Makefile.sources
- src/hb-aat-fmtx-table.hh
- src/hb-aat-layout.cc
- src/hb-aat-ltag-table.hh
> [aat] Unprefix not essentially layout tables

- src/Makefile.am
Hopefully to fix Travis's build issue
> [ci] Fix coverage build fail

- src/gen-arabic-table.py
- src/gen-indic-table.py
- src/gen-use-table.py
To fix https://github.com/harfbuzz/harfbuzz/pull/941#issuecomment-377300395
> Make gen-* scripts LC_ALL=C compatible

- src/hb-graphite2.cc
- src/hb-graphite2.h
> [graphite] Make get_table threadsafe

- src/hb-common.cc
- src/hb-ft.cc
- src/hb-glib.cc
- src/hb-icu.cc
- src/hb-ot-font.cc
- src/hb-shape.cc
- src/hb-shaper.cc
- src/hb-ucdn.cc
- src/hb-uniscribe.cc
Fixes #923 hopefully, wanted to go for some macro but felt better to keep it simple, let me know if is wrong or anything.
> Make atexit callbacks threadsafe

- src/Makefile.sources
- src/hb-aat-layout-bsln-table.hh
- src/hb-aat-layout.cc
Fixes #913
Currently only 0 and 1 formatted version of `bsln` exist between the Apple fonts, here is list of format and deltas of each font.
```
format=0; 0, 465, 0, 1345, 507, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /Library/Fonts/Apple Chancery.ttf
format=0; 0, 445, -90, 844, 384, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /Library/Fonts/AppleMyungjo.ttf
format=0; -9, 0, 0, 1628, 614, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /Library/Fonts/Hoefler Text Ornaments.ttf
format=0; 0, 450, 0, 1339, 506, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, /Library/Fonts/Skia.ttf
format=0; 0, 380, 0, 1367, 444, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
```
> [aat] Add bsln table implementation

- src/Makefile.sources
- src/hb-aat-feat-table.hh
- src/hb-aat-layout.cc
Fixes #904, tested manually with Skia.ttf
> [aat] Implement feat table parsing

- src/Makefile.sources
- src/hb-aat-layout-feat-table.hh
- src/hb-aat-layout.cc
Please let me know if any thing else is needed. AFAIK my codes were sanitized carefully at least when they were committed (except the first ones that I tried to fix later)
> [aat] Further improvements on feat

- TODO
- docs/harfbuzz-sections.txt
- src/dump-emoji.cc
- src/dump-fon.cc
- src/hb-blob.cc
- src/hb-blob.h
- src/main.cc
- src/test-buffer-serialize.cc
- src/test-size-params.cc
- src/test-would-substitute.cc
- src/test.cc
- test/api/hb-subset-test.h
- test/api/hb-test.h
- util/options.cc
- util/options.hh
- util/view-cairo.hh
I guess there was some reason that this is not done earlier so no problem if rejected but I guess in case accepted, it will be a useful thing.
> Add hb_blob_create_from_file, a new API

- src/hb-ot-shape-complex-indic-machine.hh
- src/hb-ot-shape-complex-indic-machine.rl
- src/hb-ot-shape-complex-khmer-machine.hh
- src/hb-ot-shape-complex-khmer-machine.rl
- src/hb-ot-shape-complex-myanmar-machine.hh
- src/hb-ot-shape-complex-myanmar-machine.rl
- src/hb-ot-shape-complex-use-machine.hh
- src/hb-ot-shape-complex-use-machine.rl
> Minor, re-add unused to mark to indic-machine

- src/hb-coretext.cc
- src/hb-uniscribe.cc
> Use arrayZ on hb-coretext and hb-uniscribe and fix macOS/Win bots

- src/hb-blob.cc
It makes it compatible with ARMCC which I could have access in a collaboration with @imgtec, thanks!
TBR, @behdad
> Make hb_blob_create_from_file more portable

- src/hb-face.cc
- src/hb-private.hh
This should resolve the outstanding issues with https://github.com/harfbuzz/harfbuzz/issues/630.
Testing build with pull request.
> Fix SunStudio 12.6 build

- src/hb-set-private.hh
- test/api/test-set.c
> Fix hb_set_intersect bug when shrinking vectors

- src/hb-blob.cc
With this hb-shape/hb-view support `cat font.ttf | build/util/hb-view /dev/stdin text` also.
Please have a look and see what can be improved on c53697d3 and aa0c5df41 also (I merged those first for more convince on working on this but like to get feedback on them).
Another possible solution for fixing this is to use third path of `hb_blob_create_from_file` which uses ftell/fopen/fread but currently unable to read from /dev/stdin when piped. In order to make `/dev/stdin` work there I should make that path just like our [current stdin reader](https://github.com/harfbuzz/harfbuzz/blob/c53697d3f2a/util/options.cc#L651-L668) (and possibly use hb_array_t also?) but as we can't turn `-` to `/dev/stdin` on Windows and AIX as the lack of support, I guess that doesn't worth the hassle anyway.
> Support pipe and friends on hb_blob_create_from_file

- test/subset/run-tests.py
> Resolve ttx absolute path before use

- .circleci/config.yml
- src/hb-blob.cc
Fixes #1063.
And assign our Alpine CI bot to always use fallback reader.
> Merge two fread readers of hb_blob_create_from_file

- src/gen-use-table.py
Addresses https://github.com/harfbuzz/harfbuzz/issues/1035
> USE overrides for Bhaiksuki Gap Fillers and Grantha Anusvara

- src/hb-blob.cc
Fixes #1086 and I guess #1046 also (hopefully)
> Use CreateFileW explicitly and pass wchar_t to it

- src/hb-common.cc
> Do not enforce a native direction of LTR for Runic

- appveyor.yml
https://github.com/harfbuzz/harfbuzz/pull/1093#issuecomment-405201903
https://ci.appveyor.com/project/harfbuzz/harfbuzz/build/job/ky7lao1ii1bi7ew4#L71
> appveyor.yml: try updating msys2 to fix failing mingw-w64-x86_64 build

- src/hb-ft.cc
- src/hb-ot-shape.cc
A fix for a couple of theoretically possible memory leaks.
> Fix unlikely leaks

- appveyor.yml
Fixes #1122 (at least tries to)
> [ci] Fix Appveyor bot

- src/hb-common.cc
> Support _ in feature ids

- src/hb-common.cc
Add HB_USE_ATEXIT guard around free_static_C_locale missed by previous
commit.
> Add guard around free_static_C_locale

- .circleci/config.yml
> [circleci] Add an obsessive clang bot

- test/api/Makefile.am
- test/api/test-multithread.c
> Add a multithreaded test

- test/api/test-multithread.c
Does it look correct? If so, another round of issues :) (tsan bot was healed before this)
> test-multithread, check the results on every iteration

- .circleci/config.yml
- src/check-symbols.sh
- src/hb-ucdn.cc
- test/fuzzing/run-shape-fuzzer-tests.py
- test/fuzzing/run-subset-fuzzer-tests.py
- util/helper-cairo.cc
> [circleci] Couple of fixes

- .circleci/config.yml
- src/check-symbols.sh
- test/fuzzing/main.cc
- test/fuzzing/run-shape-fuzzer-tests.py
- test/fuzzing/run-subset-fuzzer-tests.py
> [circleci] Fix "msan" and "everything" bots

- src/hb-graphite2.cc
> Update Graphite API to latest

- src/dump-emoji.cc
As @khaledhosny comment. Thanks :)
> [dump-emoji] better explaination of the usage

- .circleci/config.yml
- test/fuzzing/hb-shape-fuzzer.cc
- test/fuzzing/run-shape-fuzzer-tests.py
> Enable vaglrind and dedicate a bot to it

- appveyor.yml
https://github.com/harfbuzz/harfbuzz/pull/1309#issuecomment-432778270
> [appveyor] Limit make to three jobs

- docs/harfbuzz-sections.txt
- src/dump-emoji.cc
- src/hb-open-type.hh
- src/hb-ot-color-cbdt-table.hh
- src/hb-ot-color-sbix-table.hh
- src/hb-ot-color-svg-table.hh
- src/hb-ot-color.cc
- src/hb-ot-color.h
- src/hb-ot-face.cc
- src/hb-ot-face.hh
- src/hb-ot-layout.cc
- test/api/test-ot-color.c
<s>Only sbix part for now,</s> see if the direction looks good. (on top of the other PR)
> Implement ot-color-png

- docs/harfbuzz-sections.txt
- src/dump-emoji.cc
- src/hb-open-type.hh
- src/hb-ot-color-sbix-table.hh
- src/hb-ot-color-svg-table.hh
- src/hb-ot-color.cc
- src/hb-ot-color.h
- src/hb-ot-face.cc
- src/hb-ot-face.hh
- src/hb-ot-layout.cc
- test/api/test-ot-color.c
* hb_ot_color_has_svg
* hb_ot_color_glyph_reference_blob_svg
> [svg] Add public API

- src/hb-ot-color-cbdt-table.hh
- src/hb-ot-color-sbix-table.hh
- src/hb-ot-color.cc
- src/hb-ot-font.cc
- test/api/test-ot-color.c
> [ot-color/png] Consider strike ppem on scaling

- .circleci/config.yml
- CMakeLists.txt
> [cmake] Make build of tests and subset optional

- src/Makefile.sources
- src/hb-aat-layout-just-table.hh
- src/hb-aat-layout.cc
> [just] Initial table implementation

- src/gen-use-table.py
- src/hb-ot-shape-complex-use-table.cc
https://github.com/harfbuzz/harfbuzz/issues/1379
> Change USE Category for Grantha Virama

- src/Makefile.sources
- src/hb-ot-face.hh
- src/hb-ot-font.cc
- src/hb-ot-hmtx-table.hh
- src/hb-ot-stat-table.hh
Related to #1337 
Its reading is tested manually.
> [STAT] Add table parsing

- docs/harfbuzz-sections.txt
- src/Makefile.sources
- src/hb-ot-face.hh
- src/hb-ot-gasp-table.hh
- src/hb-ot-hhea-table.hh
- src/hb-ot-hmtx-table.hh
- src/hb-ot-metrics.cc
- src/hb-ot-metrics.h
- src/hb-ot-os2-table.hh
- src/hb-ot-post-table.hh
- src/hb-ot-var-mvar-table.hh
- test/api/Makefile.am
- test/api/test-ot-metrics.c
hb_ot_metrics_get
Related to #1337
> Implement a simple API for fetching opentype metrics

- src/hb-ot-cff1-table.hh
get rid of assert for issue #1443 and handle default case silently
> removed assert

- src/Makefile.sources
- src/hb-aat-fdsc-table.hh
- src/hb-aat-layout.cc
- src/hb-ot-gasp-table.hh
- src/hb-ot-layout.cc
Related to https://github.com/harfbuzz/harfbuzz/issues/1337
> Implement OT's gasp and AAT's fdsc

- src/hb-ot-os2-table.hh
> [os2] Make newer table fields accessible

- src/hb-aat-fdsc-table.hh
- src/hb-aat-layout-common.hh
- src/hb-ot-head-table.hh
- src/hb-ot-os2-table.hh
- src/hb-ot-stat-table.hh
Things to be used in https://github.com/harfbuzz/harfbuzz/pull/1459
> Apply non-controversial parts of ot-style impl

- .travis.yml
Let's see... as was suggested by log
> [ci] Try to fix Travis macOS bot issue

- src/hb-aat-fdsc-table.hh
- src/hb-aat-layout-common.hh
- src/hb-aat-layout-feat-table.hh
- src/hb-aat-layout-trak-table.hh
- src/hb-aat-layout.cc
- src/hb-buffer.cc
- src/hb-directwrite.cc
- src/hb-dsalgs.hh
- src/hb-map.hh
- src/hb-ot-cmap-table.hh
- src/hb-ot-color-cbdt-table.hh
- src/hb-ot-color-cpal-table.hh
- src/hb-ot-color-sbix-table.hh
- src/hb-ot-color-svg-table.hh
- src/hb-ot-glyf-table.hh
- src/hb-ot-hdmx-table.hh
- src/hb-ot-layout-base-table.hh
- src/hb-ot-os2-table.hh
Mostly places I was involved had the issue so I used the opportunity to fix some more style things in hb-directwrite also.
> minor style fix, use void in methods on no argument

- src/hb-shaper-list.hh
Related to https://github.com/harfbuzz/harfbuzz/issues/1478
> Lower coretext_aat shaper priority

- src/hb-ot-color.h
- src/hb-ot-name.h
- src/hb-ot-var.h
> Fix Solaris Trailing comma in enum warnings

- src/hb-atomic.hh
> Fix Solaris use after free

- CMakeLists.txt
Lets see which bots won't like that.
> [cmake] Enable C++11 on CMake

- .circleci/config.yml
- src/hb-gobject-structs.cc
Just was curious what will be raised
> [ci] Enable more GCC warnings

- test/fuzzing/hb-subset-fuzzer.cc
Add support for toggling retain_gids.
> [subset] Update the subset fuzzer to get  options to use from test case.

- src/hb-common.cc
Copied and edited from the util option documentation. The docbook table syntax is too verbose, but that is the best I can come up with.
> [doc] Document hb_feature_from_string() syntax

- src/hb-subset-plan.cc
- test/api/hb-subset-test.h
- test/api/test-subset-glyf.c
> Make hb_subset_input_glyph_set () actually do something.

- src/hb-graphite2.cc
The Graphite to Harfbuzz conversion code was creating rounding drift that resulted in increasing offsets through a run. This was particularly evident at low scale values.
> Fix offset drift in graphite integration

- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
from hb-subset-plan.hh/.cc files
> remove deprecated variable glyphs_deprecated

- .circleci/config.yml
* Add --with-graphite2 to macOS
* Create a dummy ragel binary
> [ci] Tweak macos and psvita bots

- src/hb-iter.hh
- src/test-iter.cc
These will be nice to have also:
* <s>Being able to have accumulator in a different type</s> (done)
* <s>hb_reduce_right (or hb_reduce_end?)</s> (not needed, we should have reverse instead)
* <s>Make it work somehow without initial value also</s> (possible but a respective default type also is needed) 
This alternatively can be named fold, accumulate, aggregate, compress, or inject [also](https://en.wikipedia.org/wiki/Fold_(higher-order_function)) and things like sum/min/max/average can be implemented upon it.
> [iter] Add hb_reduce

- src/hb-blob.cc
Fix "warning C4068: unknown pragma"
> Fix MSVC C4068 warning

- src/gen-tag-table.py
- src/hb-ot-tag-table.hh
- src/hb-ot-tag.cc
- test/api/test-ot-tag.c
Note that this changes the behavior of `hb_ot_tag_to_language` for unknown tags.
> Comment out entries in ot_languages where fallback suffices

- CMakeLists.txt
This reverts commit 694cb1beeefe1c54b2e613d2d566a21e248a2c9c.
As https://github.com/harfbuzz/harfbuzzjs/commit/38a70d209e6ffd5e42753cb2faadf619ef58abfc
> Revert "Add harfbuzzjs build configuration (#1636)"

- README.md
- TESTING.md
Upstream sample test instructions
> [docs] Add sample test commands

- appveyor.yml
- src/hb-algs.hh
https://github.com/harfbuzz/harfbuzz/issues/1730
> Branch to trial-error fixing Visual Studio builds

- src/hb-aat-layout.cc
- src/hb-algs.hh
- src/hb-ot-post-table.hh
- src/hb-ot-var-mvar-table.hh
Unintentionally but part of #593, I didn't know its essence at the time! :)
> Use a unified and internal bsearch

- src/hb-ot-glyf-table.hh
I guess all of its field will be initialized anyway here but lets make it more defensive
Fixes #1759
> Minor, fix gcc maybe-uninitialized complain

- src/hb-cff-interp-cs-common.hh
- src/hb-cff-interp-dict-common.hh
- src/hb-ot-cff-common.hh
- src/hb-ot-cff1-table.hh
- src/hb-ot-cff2-table.hh
- src/hb-subset-cff1.cc
- src/hb-subset-cff2.cc
> [cff] Use switch on multi-format structs

- src/hb-config.hh
- src/hb.hh
> Add HB_NO_SETLOCALE

- src/hb-blob.cc
- src/hb-config.hh
But don't see the need to add it to lean or tiny personally, what motivated me for PR is to ask about the naming
(fixes #1764)
> Add HB_NO_OEPN

- .circleci/config.yml
- CMakeLists.txt
- src/Makefile.am
- src/hb-cff-interp-common.hh
- src/hb-cff-interp-cs-common.hh
- src/hb-coretext.cc
- src/hb-directwrite.cc
- src/hb-ft.cc
Apprently /usr/include/bits/types/stack_t.h, included somehow by glib and stack_t of cff were in conflict so fixed that also.
> [amalgam] Use it in cmake port and fix conflicts

- docs/usermanual-clusters.xml
Fixes https://github.com/harfbuzz/harfbuzz/issues/1818
> Clusters are reversed based on the direction, not script

- src/hb-ot-metrics.cc
As it is exposed with a different condition
> [metrics] Don't use metrics API in _common

- src/hb-ot-metrics.cc
- src/hb-ot-metrics.h
- test/api/test-ot-metrics.c
> [metrics] Fix _get_variation API to works with actual coord values

- src/hb-ot-metrics.cc
- src/hb-ot-metrics.h
> Add _MAX_VALUE to hb_ot_metrics_t

- src/hb-ot-metrics.cc
> [metrics] Expose raw OS2/HHEA asc/dsc values using private tags

- src/hb-ot-meta-table.hh
- src/hb-ot-meta.cc
- src/hb-ot-meta.h
- src/hb-ot-metrics.cc
- src/hb-ot-metrics.h
- src/hb-ot-metrics.hh
- src/test-ot-meta.cc
- test/api/test-ot-meta.c
> Rename to hb_ot_meta_tag_t and hb_ot_metrics_tag_t

- src/hb-aat-layout-lcar-table.hh
> [lcar] flip for and switch position

- docs/harfbuzz-sections.txt
- src/hb-font.cc
- src/hb-font.h
- test/api/test-ot-extents-cff.c
> [var] Add a new API, hb_font_set_var_named_instance

- test/api/test-ot-face.c
> [fuzz] Add dummy call of the added APIs

- src/hb-ot-os2-table.hh
Separated from #1890 to decide if we like the logic
> [os2] Implement mean optical size fallback

- src/hb-ot-var-fvar-table.hh
Something felt nice while #1893 and #1890
> [fvar] Use roundf instead hardcoding round logic

- src/hb-ot-os2-table.hh
It should have the mentioned fields otherwise I wonder if it useful at all.
> [os2] Replace null pool addr compare by checking vital fields

- src/Makefile.sources
- src/hb-aat-layout-opbd-table.hh
- src/hb-ot-face-table-list.hh
- src/hb-ot-layout.cc
> [opbd] Implement table parsing

- src/hb-font.cc
> Move HB_NO_VAR to a better place in hb-font.cc

- src/hb-ot-glyf-table.hh
Having them all over proved can cause unnoticeable bugs.
Needs more work (creating a SimpleGlyphHeader struct and moving any related logics to it), adding get_{simple,composite} methods to GlyphHeader.
> [glyf] Move GlyphHeader related logics to its, making its fields protected

- src/hb-face.cc
- src/hb-subset.cc
If I've got https://github.com/harfbuzz/harfbuzz/pull/1934#issuecomment-526616048 correctly.
> [subset] Move drop 0 tag table logic

- src/hb-subset.cc
As https://github.com/harfbuzz/harfbuzz/pull/1934#issuecomment-526927171
> [subset] Run once for a tag

- src/hb-subset.cc
As https://github.com/harfbuzz/harfbuzz/pull/1950#issuecomment-526953048
> [subset] Use internal API of hb_set_t

- test/api/test-ot-tag.c
We already tested this languages a few lines above.
> Remove duplicated tests from test-ot-tag

- src/hb-number-parser.hh
- src/hb-number-parser.rl
Which were removed on https://github.com/harfbuzz/harfbuzz/commit/1083df8b80b08aa1a4f2dabfe414aaa4a0ec8aa1
> [number] Add overflow checks used to be done in parse_bcd

- .circleci/config.yml
- src/hb-aat-layout-bsln-table.hh
- src/hb-aat-layout-common.hh
- src/hb-aat-layout-just-table.hh
- src/hb-aat-layout-kerx-table.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-coretext.cc
- src/hb-open-type.hh
- src/hb-ot-cmap-table.hh
- src/hb-ot-color-cbdt-table.hh
- src/hb-ot-color-colr-table.hh
- src/hb-ot-glyf-table.hh
- src/hb-ot-layout-base-table.hh
- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gpos-table.hh
- src/hb-ot-layout-gsub-table.hh
- src/hb-ot-layout-jstf-table.hh
- src/hb-ot-math-table.hh
- src/hb-ot-name-table.hh
- src/hb-ot-shape-complex-arabic-fallback.hh
- src/hb-ot-vorg-table.hh
> Fix macOS build issues with amalgam

- .circleci/config.yml
- src/hb-buffer.cc
- src/hb-common.cc
- src/hb-ft.cc
- src/hb-ot-map.cc
- src/hb-set.hh
> Enable -fno-sanitize-recover=undefined checks

- src/hb-directwrite.cc
Discovered this issue while trying to build it with Clang.
> Fix extra semicolon issue

- src/hb-ot-shape-complex-arabic-fallback.hh
> Fix -Wsizeof-array-div clang warning

- src/hb-ot-hmtx-table.hh
- src/hb-ot-var-hvar-table.hh
First step toward #1594 per @blueshade7 and needed for #1999 (so going to be tested there)
> Implement hmtx/vmtx metrics read from hvar/vvar

- src/hb-cff-interp-common.hh
- src/hb-ot-cff1-table.cc
- src/hb-ot-cff1-table.hh
- src/hb-ot-cff2-table.cc
- src/hb-ot-color-cbdt-table.hh
- src/hb-ot-color-sbix-table.hh
- src/hb-ot-font.cc
- src/hb-ot-glyf-table.hh
- src/hb-ot-hmtx-table.hh
- src/hb-ot-var-hvar-table.hh
- test/api/test-ot-extents-cff.c
> [ot-font] Apply font scaling before turning to int

- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gsub-table.hh
simplifies subsetting offset arrays during stream operations.
> Add subset_offset_array helper function.

- src/gen-use-table.py
- src/hb-ot-shape-complex-use-table.cc
> Reorder U+1C29 LEPCHA VOWEL SIGN OO

- src/hb-ot-glyf-table.hh
- src/hb-ot-var-gvar-table.hh
Another round of cleanups, have some path extractor based on current things, some more cleanup needed however.
> glyf table cleanup

- src/hb-map.hh
Reduces the number of hash computations needed.
> Store the hash value of a key in item_t in hb_map

- .circleci/config.yml
- test/fuzzing/run-shape-fuzzer-tests.py
- test/fuzzing/run-subset-fuzzer-tests.py
> [ci] Fix subset timeout issue of tsan/valgrind bots

- src/hb-ot-layout-gsubgpos.hh
Possible fix to revive ubsan bot fail on https://circleci.com/gh/harfbuzz/harfbuzz/114888
> [gpos] Don't move pointer when match_glyph_data is not set

- src/hb-array.hh
- src/hb-ot-glyf-table.hh
- src/hb-ot-var-gvar-table.hh
> Add in_range in hb_bytes_t to merge range_checker_t with it

- src/hb-ot-cmap-table.hh
- src/hb-ot-layout-gpos-table.hh
- src/hb-ot-name-table.hh
- src/hb-ot-vorg-table.hh
- src/hb-serialize.hh
https://github.com/harfbuzz/harfbuzz/pull/1985#discussion_r327272300 IIUC
> [serialize] Extract iterable copy, copy_all

- src/hb-array.hh
- src/hb-ot-glyf-table.hh
- src/hb-ot-var-gvar-table.hh
Follow up to https://github.com/harfbuzz/harfbuzz/pull/2041#discussion_r341314078
> Use the same range check logic as hb_sanitize_context_t in hb_array_t and rename

- src/hb-buffer.cc
- src/hb-common.cc
- src/hb-face.hh
- src/hb-graphite2.cc
- src/hb-ot-map.hh
- src/hb-ot-shape-complex-arabic.cc
- src/hb-ot-shape.cc
- src/hb-set.hh
- test/shaping/data/aots/hb-aots-tester.cpp
- util/ansi-print.cc
- util/options.cc
- util/options.hh
Also, prefer HB_FEATURE_GLOBAL_START and HB_FEATURE_GLOBAL_END.
> Prefer UINT_MAX instead of uint overflow.

- src/hb-coretext.cc
Instead of trying to map OpenType features to AAT feature selectors which only works for a small subset of OpenType features, use the simpler `kCTFontOpenTypeFeatureTag` with OpenType feature tags directly.
With this change, features like `cvXX` can be enabled in coretext shaper, while they were previously ignored due to missing mapping.
This seems to work even with AAT fonts that don’t have OpenType layout tables, which suggests that CoreText is doing the mapping itself in this case.
`kCTFontOpenTypeFeatureTag` seems to have been introduced in macOS 10.10 and iOS 8.0, though, so its use is conditional on version check for now. Not sure how to check iOS version, so I left this out.
> [coretext] Use kCTFontOpenTypeFeatureTag

- docs/harfbuzz-sections.txt
- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gpos-table.hh
- src/hb-ot-layout-gsub-table.hh
- src/hb-ot-layout-gsubgpos.hh
- src/hb-ot-layout.cc
- src/hb-ot-layout.h
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
- test/api/test-ot-face.c
closure and remap lookup indexes for GSUB/GPOS, save them in the subset_plan object
> [subset] closure lookups for GSUB/GPOS

- docs/harfbuzz-sections.txt
- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gsubgpos.hh
- src/hb-ot-layout.cc
- src/hb-ot-layout.h
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
**This PR is dependent on clousre_lookups PR** #2027 
closure and remap feature indexes for GSUB/GPOS, store them in subset plan object
> [subset] Layout closure features for GSUB/GPOS

- src/hb-ot-layout-gpos-table.hh
Fixed the following sub-issues found in #2060 :
1. Offsets to device tables in PairPosFormat1 were based on the lookup table, not on the PairSet table (see `PairSet::sanitize_closure_t` in `PairPosFormat1::sanitize`).
2. Device tables were not serialized when their offsets were listed in value records in SinglePosFormat1, SinglePosFormat2, PairPosFormat1, or PairPosFormat2.
Since variation data in the GPOS table are stored in a variant of a device table, above issues were preventing a GPOS table with variation data in a variable font to be subsetted correctly.
> [subset] fixed GPOS device table sanitize & serialize

- src/hb-ot-shape.cc
> Only prefer AAT morx over GSUB for horizontal runs

- src/hb-ot-cmap-table.hh
Partial revert of some dead code added as part of https://github.com/harfbuzz/harfbuzz/pull/2121
> [cmap] Remove dead code

- .circleci/config.yml
- src/hb-ot-hdmx-table.hh
- src/hb-ot-layout-common.hh
> Minor, fix warnings raised when built with -std=c++2a

- src/gen-arabic-table.py
- src/gen-emoji-table.py
- src/gen-indic-table.py
- src/gen-tag-table.py
- src/gen-ucd-table.py
- src/gen-use-table.py
- src/gen-vowel-constraints.py
> Add links to files used by python scripts.

- src/hb-serialize.hh
a solution of #2164 [subset] pop_pack() option to not hash & share table
> [subset] add share option to pop_pack()

- src/hb-meta.hh
- src/test-meta.cc
to be used in a solution for #2156
> add hb_unwrap_type

- src/hb-ot-layout-gdef-table.hh
> [subset] GDEF LigCaretList subsetting support

- src/hb-algs.hh
- src/hb-ot-var-fvar-table.hh
- src/hb-sanitize.hh
Similar to stl and glsl's clamp
> [algs] Add hb_clamp

- src/hb-cff-interp-dict-common.hh
- src/hb-ot-cff-common.hh
- src/hb-ot-cff1-table.hh
- src/hb-ot-cff2-table.hh
- src/hb-subset-cff-common.hh
- src/hb-subset-cff1.cc
Removed code no longer used as the result of one-pass CFF/CFF2 subsetters PR#2226.
> Removed unused code from CFF/CFF2 subsetters

- .circleci/config.yml
- CMakeLists.txt
- Makefile.am
And test it in distcheck CI bot
> Bring cmake back to release tarball

- src/hb-ot-cff-common.hh
- src/hb-ot-cmap-table.hh
- src/hb-ot-hdmx-table.hh
- src/hb-pool.hh
Less noise, as was agreed before and applied 385741d565de also
> Turn more of simple dagger chains to foreach

- appveyor.yml
Fixes #2244 
Temporarily setting wraps clone depth to 1, will remove before merge
> [ci/appveyor] Adopt with Meson

- src/gen-def.py
- src/hb-font.cc
- src/hb-font.h
- test/api/test-var-coords.c
let's decide about this in some other time
> Move hb_font_get_var_coords_design behind HB_EXPERIMENTAL_API

- meson.build
- meson_options.txt
- src/meson.build
- test/api/meson.build
> [meson] Make harfbuzz-icu separate module optout-able

- src/hb-serialize.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/2325
> [serializer] Make snapshot()/revert() revert current object links

- src/hb-aat-layout.cc
- src/hb-ot-cff1-table.cc
- src/hb-ot-os2-unicode-ranges.hh
Resolves https://github.com/harfbuzz/harfbuzz/pull/2335#discussion_r410767510
> Minor, use hb_sorted_array::bsearch where possible

- test/api/meson.build
Addresses https://github.com/harfbuzz/harfbuzz/commit/8ae06c9489f132844cbede80b5fe8241ce47fc0e#r38597920
> Refactor test/api/meson.build and always run test-unicode test

- src/hb-blob.cc
- src/hb-cff-interp-common.hh
- src/hb-cff-interp-cs-common.hh
- src/hb-cff2-interp-cs.hh
- src/hb-directwrite.cc
- src/hb-ot-cff-common.hh
- src/hb-ot-cff1-table.hh
- src/hb-ot-cff2-table.hh
- src/hb-ot-layout.cc
- src/hb-ot-os2-unicode-ranges.hh
- src/hb-subset-cff-common.cc
- src/hb-subset-cff-common.hh
- src/hb-subset-cff1.cc
- src/hb-subset-cff2.cc
- src/main.cc
- src/test-buffer-serialize.cc
- util/hb-subset.cc
- util/options.cc
feel free to disagree with ones you don't like ;)
> minor, replace nullptr checks with implicit ones

- src/hb-ot-layout-common.hh
Never drop FeatureVariationRecord for now.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2334
> [subset] FeatureVariations subsetting is wrong

- .circleci/config.yml
- meson.build
- meson_options.txt
- src/gen-def.py
- src/main.cc
- src/meson.build
- test/subset/meson.build
Enables EXPERIMENTAL_APIs, actually wanted to see whether #2352 touches any test result or not.
> [meson] Add an experimental-api option

- src/hb-blob.cc
If the size of opened file is zero, try opening resource fork by appending `/..namedfork/rsrc` to the file name. This is guarded with `__APPLE__` ifdef and uses `_PATH_RSRCFORKSPEC` macro from `sys/paths.h`.
Defining `HB_NO_RSRCFORK` will disable this fallback.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2383
> [blob] Try to support resource fork fonts on macOS

- meson_options.txt
- src/check-symbols.sh
- src/meson.build
> [meson] Prefer C linker and improve exported symbols check

- src/hb-ot-cmap-table.hh
get rid of << operator according to Behdad's comment in #2369
> [subset] don't use << operator in collect_mapping

- src/hb-algs.hh
- src/hb-ot-tag.cc
- test/api/test-ot-tag.c
> Round-trip OpenType tags through BCP 47

- .circleci/config.yml
Had some installation flakiness, let's resolve their issue this time
> [ci] Enable sanitizer bots again

- .circleci/config.yml
- appveyor.yml
- docs/meson.build
- meson.build
- src/meson.build
- test/fuzzing/meson.build
- test/shaping/meson.build
- test/subset/meson.build
We need link_language for `library()` which is in the not released yet 0.55 so let's freely use the new features also.
> [meson] Use / instead join_paths

- .circleci/config.yml
- meson.build
- meson_options.txt
- src/meson.build
- test/subset/meson.build
As https://github.com/harfbuzz/harfbuzz/pull/2412#discussion_r426275027
> [meson] Normalize options names

- meson-mingw-cross.txt
- mingw-meson.sh
This allow also to cross-compile on Linux for Windows
Fixes #2413
> Add shell script and cross-compilation file to compile Harfbuzz with meson

- src/update-unicode-tables.make
Addressing https://github.com/harfbuzz/harfbuzz/pull/2438#issuecomment-637821839
> Simplify update-unicode-tables.make

- configure.ac
- meson.build
As https://github.com/harfbuzz/harfbuzz/pull/2437#issuecomment-639089034
> minor, improve the need for graphite comment

- src/hb-coretext.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/2452
> [coretext] Properly check for macOS 10.10

- .circleci/config.yml
the bots are either not optimized ones or sanitizer ones so not much value
on trying to optimize them further.
> [ci] raise subset fuzzer cases runner timeout

- src/hb-aat-layout-kerx-table.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-ot-layout.cc
> Add messages for GPOS/GSUB (take 2)

- CMakeLists.txt
- configure.ac
- meson.build
Uploaded to get feedback and improve the messaging before the merge.
Disagree with some part or whole? We surely can discuss constructively, nothing is merged and even the merged things can be reverted/improved, so.
> Update build systems status messages

- src/hb-face.cc
> [face] Destroy blob if face closure can not be created

- src/hb-ot-shape.cc
> [ot-shape] Free shape plan maps upon error creating data

- src/hb-ft.cc
> [ft] Do not deference ft_font if it is nullptr

- configure.ac
- src/hb.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/2496
> Always round up

- src/hb-array.hh
- src/hb-open-type.hh
- src/hb-ot-stat-table.hh
- src/hb-ot-var-fvar-table.hh
- src/hb-vector.hh
Based on hb_sorted_array_t::bfind
> Add hb_array_t::lfind

- .circleci/config.yml
- .github/workflows/linux-ci.yml
- Makefile.am
- meson.build
- meson_options.txt
https://github.com/harfbuzz/harfbuzz/pull/2506#issuecomment-650814046
> [meson] Turn benchmark to a feature

- .ci/build-win32.sh
- meson.build
- subprojects/.gitignore
- subprojects/cairo.wrap
- subprojects/libpng.wrap
- subprojects/pixman.wrap
- subprojects/proxy-libintl.wrap
Needed to build hb-view in Windows
> [meson] enable cairo as subproject

- meson.build
minor things related to freetype in meson
> Meson freetype

- meson.build
My take from https://github.com/harfbuzz/harfbuzz/pull/2519#issuecomment-653101100
> [meson] Improve the way cairo-ft availability is checked

- meson.build
- src/meson.build
saw that in pixman meson port and then in mesa's meson port.
> [meson] use null_dep idiom

- meson.build
As https://github.com/harfbuzz/harfbuzz/pull/2519#issuecomment-653094907
> [meson] revert 020b182 as meson fails when there is cyclic dependency

- test/shaping/meson.build
- test/shaping/run-tests.py
As https://github.com/harfbuzz/harfbuzz/commit/43e3ab019c6b6ab8e429b3dd3aa13a7b9e8316e6#r40363339
@khaledhosny would you please have a look? Thanks :)
> [tests] rename no_ft_funcs to NO_FT_FUNCS

- src/hb-aat-layout-kerx-table.hh
- test/shaping/data/in-house/tests/macos.tests
Fixes https://github.com/harfbuzz/harfbuzz/issues/2531.
> [aat] Correct array indexing when looking up actions in KerxSubTableFormat4

- test/shaping/data/aots/Makefile.am
- test/shaping/data/in-house/Makefile.am
- test/shaping/data/text-rendering-tests/Makefile.am
- test/shaping/meson.build
- test/shaping/run-tests.py
https://github.com/harfbuzz/harfbuzz/pull/2535#issuecomment-653933245
> [tests] Use HAVE_FREETYPE itself instead NO_FT_FUNCS

- test/shaping/run-tests.py
- util/hb-shape.cc
> [tests] Replace space with colon in batch mode

- meson_options.txt
- test/fuzzing/meson.build
As ots, https://github.com/khaledhosny/ots/commit/4d37b9b
Closes #2249
> [meson] Add fuzzer_ldflags

- .circleci/config.yml
- test/fuzzing/run-draw-fuzzer-tests.py
- test/fuzzing/run-shape-fuzzer-tests.py
- test/fuzzing/run-subset-fuzzer-tests.py
two bots, one bot here (distcheck) and one in travis still run autotools and
won't be removed till we decide about autotools
> [ci] migrate to meson

- src/gen-indic-table.py
- src/gen-use-table.py
https://lgtm.com/projects/g/harfbuzz/harfbuzz/?mode=list&lang=python there won't be any python suggestions after this
> [py] apply lgtm.com python suggestions

- src/hb-ot-cmap-table.hh
- src/hb-ot-os2-table.hh
collect_mapping is time consuming as it iterates all codepoints in all
cmap subtables, only trigger it when necessary
> [subset] call collect_mapping only when --gids option is used.

- src/hb-ot-shape-complex-khmer.cc
> Remove unused code from the Khmer shaper.

- README
Fixes #2591 guess we can have this one till we go for autotools removal
> Turn README to a soft redirect

- src/hb-ot-glyf-table.hh
Fixes this sanitizer complain https://circleci.com/gh/harfbuzz/harfbuzz/150247 revealed by 02d1ec16
> [glyf] Clamp advance value result

- src/hb-ot-glyf-table.hh
This should make glyf/gvar faster as it will involve less atomic operations and things.
`meson build -Dexperimental_api=true --buildtype=release && ninja -Cbuild && build/perf/perf "--benchmark_filter=glyf.*- ot -"`
Before:
```
----------------------------------------------------------------------------------
Benchmark                                           Time           CPU Iterations
----------------------------------------------------------------------------------
extents/glyf - ot - SourceSerifVariable         46091 ns      46036 ns      16173
extents/glyf/vf - ot - SourceSerifVariable    4160142 ns    4154913 ns        174
extents/glyf - ot - Comfortaa                   25754 ns      25726 ns      27030
extents/glyf/vf - ot - Comfortaa              2627804 ns    2624596 ns …
```
> [glyf] Optimize retrieval of hmtx/vmtx/gvar

- src/hb-ot-glyf-table.hh
> [glyf] protect CompositeGlyph fields

- docs/usermanual-opentype-features.xml
Fixes https://github.com/harfbuzz/harfbuzz/issues/2213
> [docs] Improve documentation for default features

- test/api/test-buffer.c
> [tests] Fix memory leak in test

- src/gen-use-table.py
- src/hb-ot-shape-complex-use-machine.hh
- src/hb-ot-shape-complex-use-machine.rl
- src/hb-ot-shape-complex-use-table.cc
- src/hb-ot-shape-complex-use.hh
IND, Rsv, and O are effectively identical, so they might as well all be O.
> [use] Merge IND and Rsv classes into O

- .circleci/config.yml
- src/hb-ot-shape-complex-use-machine.hh
- src/hb-ot-shape-complex-use-machine.rl
Fixes https://github.com/harfbuzz/harfbuzz/issues/2752
> Fix build with newer ragel

- docs/usermanual-getting-started.xml
Also make the code actually compile.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2106
> [docs] Don’t use FreeType in the simple example

- src/hb-ft.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/2590
> [docs] make it clear that FT_Face must have size

- .github/workflows/msys2-ci.yml
What package manger randomly changes package names without fallback!
> [ci] Fix msys2 breakage

- subprojects/cairo.wrap
There is now a release with meson build support.
> [meson] Pin Cairo subproject 1.17.4

- .ci/build-win32.sh
Fixes https://github.com/harfbuzz/harfbuzz/issues/2840
> [ci] Add top level directory to win32 zip file

- src/hb-ot-layout-gsubgpos.hh
- Lookup::closure_lookups also checks if the lookup is visited and sets the lookup to visited. If we set visited in 'recurse' then Lookup::closure_lookups will fail to recurse into the children of the lookup.
- Also when copying ChainRule's skip LookupRecord's that point to lookups which aren't retained. This matches FontTool's behaviour.
Tests for this are included in https://github.com/googlefonts/harfbuzz/tree/noto_nastaliq_test however, that exposes some additional problems that still aren't fixed.
> [subset] don't set lookup visited in closure_lookups_context_t::recurse.

- src/Makefile.am
- src/hb-aat-layout.h
- src/hb-blob.h
- src/hb-buffer.h
- src/hb-common.h
- src/hb-deprecated.h
- src/hb-draw.h
- src/hb-face.h
- src/hb-font.h
- src/hb-gobject-enums.h.tmpl
- src/hb-gobject-structs.h
- src/hb-map.h
- src/hb-ot-color.h
- src/hb-ot-deprecated.h
- src/hb-ot-font.h
- src/hb-ot-layout.h
- src/hb-ot-math.h
- src/hb-ot-meta.h
- src/hb-ot-metrics.h
- src/hb-ot-name.h
- src/hb-ot-shape.h
- src/hb-ot-var.h
- src/hb-set.h
- src/hb-shape-plan.h
- src/hb-shape.h
- src/hb-style.h
- src/hb-unicode.h
- src/hb-version.h
- src/hb-version.h.in
- src/meson.build
Fixes https://github.com/harfbuzz/harfbuzz/issues/2851
> [introspection] Fix g-ir-scanner syntax errors

- src/hb-aat-layout-common.hh
- test/shaping/data/in-house/tests/macos.tests
- test/shaping/run-tests.py
Reduces false-positives.  See comments for new logic.
Fixes https://github.com/harfbuzz/harfbuzz/issues/2860
Need to add test.
> [aat] Improve unsafe-to-break logic

- .github/workflows/linux-ci.yml
- .github/workflows/msvc-ci.yml
- .github/workflows/msys2-ci.yml
- test/fuzzing/meson.build
We are testing Harfbuzz not meson!
> [ci] Don’t install meson from its master branch

- util/helper-cairo.cc
https://github.com/harfbuzz/harfbuzz/issues/2758
> [hb-view] Add kitty and iTerm2 image support 

- src/hb-ot-layout-gpos-table.hh
> [subset] fix for fuzzer testcase

- src/hb-ot-color-colr-table.hh
> [subset] COLRv1 struct definitions

- src/hb-directwrite.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/2474
> [directwrite] Use correct UTF-16 string length

- src/Makefile.sources
- src/hb-ot-color-colr-table.hh
- src/hb-ot-color-colrv1-closure.hh
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
close over layer/palette indices for COLRv1.
This is dependent on PR  #2929
> [subset] COLRv1 closure

- src/hb-aat-layout.cc
- src/hb-ot-layout.cc
Related to https://github.com/harfbuzz/harfbuzz/issues/3008
> [aat] Add start table/end table to buffer messages

- src/hb-directwrite.cc
Fixes #2996.
I was also working on getting optional feature (with ranges) to work, but does not look like I’ll be able to come back to it any time soon.
> Some directwrite cleanups

- src/hb-ot-shape.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/2265
> Cluster Regional_Indicator pairs (aka emoji flags)

- src/hb-directwrite.cc
Code copied from hb-uniscribe.cc and adapted to use DirectWrite types.
May be there is a better way to de-duplicate the code, though I'm not exactly sure how or if it is worth it.
> [directwrite] Support feature ranges

- src/hb-ot-layout-gsub-table.hh
- src/hb-ot-layout.cc
Narrow down random feature interaction with unsafe-to-break.
> Less random

- src/hb-buffer.cc
- src/hb-buffer.hh
- src/hb-ot-layout.cc
- src/hb-ot-shape.cc
Towards better debugging buffer messages ala "single-step". Would eventually fix https://github.com/harfbuzz/harfbuzz/issues/2468
> Improving buffer synchronization

- .github/workflows/linux-ci.yml
- .github/workflows/macos-ci.yml
- src/check-symbols.py
To collect codecov coverage on macOS as well (hopefully it will run the macOS-specific tests).
> [ci] Add macOS GitHub workflow

- src/hb-bimap.hh
- src/hb-ot-layout-common.hh
Fixes fuzzer case https://oss-fuzz.com/testcase-detail/5499162606043136.
> [subset] bail if region_map is in error.

- .circleci/config.yml
- .github/workflows/linux-ci.yml
- .github/workflows/macos-ci.yml
- .github/workflows/msvc-ci.yml
- .github/workflows/msys2-ci.yml
Should be reverted once HarfBuzz updated to match FontTools.
> [ci] Bin FontTools version due to recent COLRv1 changes

- src/Makefile.sources
- src/hb-directwrite.cc
- src/hb-ms-feature-ranges.cc
- src/hb-ms-feature-ranges.hh
- src/hb-uniscribe.cc
- src/meson.build
Fixes https://github.com/harfbuzz/harfbuzz/issues/3070
> [uniscribe/directwrite] Move feature setup to shared file

- .circleci/config.yml
- .github/workflows/linux-ci.yml
- .github/workflows/macos-ci.yml
- .github/workflows/msvc-ci.yml
- .github/workflows/msys2-ci.yml
- src/hb-ot-color-colr-table.hh
- test/subset/data/Makefile.am
- test/subset/data/Makefile.sources
- test/subset/meson.build
Currently COLRv1 spec is being changed so the subsetting implementation is out of sync. Disable subsetting by failing sanitization for COLRv1 tables and disable all colrv1 tests.
#3075, #3077, #3078
> [subset] temporarily disable COLRv1 subsetting.

- src/hb-cff2-interp-cs.hh
- src/hb-ot-layout-common.hh
- src/hb-set.hh
Trying to fix failing sanitizer test. But this makes bunch of our tests fail. Not sure if tests are wrong or the code. Pushing here to get help from @garretrieger
> Region indices

- test/subset/run-repack-tests.py
- test/subset/run-tests.py
- util/hb-subset.cc
time meson test --suite=subset down from:
```
real	0m22.822s
user	0m44.561s
sys	0m9.255s
```
to:
```
real	0m19.418s
user	0m38.171s
sys	0m3.587s
```
Does not seem to help much, but it is something.
Part of https://github.com/harfbuzz/harfbuzz/issues/3089
> [test] Add batch mode to hb-subset and use it

- src/hb-coretext.cc
Deals with the coretext half of #3066.
> Support passing variations to coretext shaper

- test/subset/run-tests.py
Regardless of the pre sentience or absence of fonttools.
> [test] Always fail subset tests if hashes don’t match

- test/subset/run-tests.py
https://github.com/harfbuzz/harfbuzz/issues/3089#issuecomment-892208892
> [test] Suggest updating the expectation if ttx matches

- src/hb-subset-input.cc
- src/hb-subset.cc
- src/hb-subset.h
- test/api/test-subset.c
These will be left in place until the 3.0.0 release. As discussed in #3078
> [subset] restore old subsetting api methods.

- NEWS
WIP NEWS entries for the next release in case someone wants to add something (if it ended up as 3.0.0m we will need more text about subset API).
> WIP NEWS for the next release

- src/hb-ot-cmap-table.hh
glyphIdArray generation implementation was O(n^2). Refactored to use a hashmap to reduce complexity. After the change subset time for a 22k codepoint subset went from 7s to 0.7s.
> [subset] speedup cmap4 subsetting for large codepoint counts.

- src/hb-ot-cmap-table.hh
- src/hb-serialize.hh
If a cmap4 subtable overflows during serialization drop it and the corresponding EncodingRecord. Don't drop the corresponding cmap12 table if it would have otherwise been removed. Fixes #3173.
> [subset] handle cmap4 overflows.

- docs/harfbuzz-docs.xml
- docs/harfbuzz-sections.txt
- src/gen-def.py
- src/hb-style.cc
- src/hb-style.h
- test/api/test-style.c
> Release hb-style.h API

- CMakeLists.txt
Related to issue #2653 and PR #2874.
> CMake: Detect pthread with module FindThread

- src/hb-subset-input.hh
This is just a tin adjustment to get our build to work again.
> Make the code able to compile with MSVC++ from Visual Studio 2015 (Version 14.0.25431.01, Update 3) sucessfully again.

- src/hb-ot-math-table.hh
1st part for MATH table subsetting
> [subset] add closure_glyphs () method for MATH table

- src/hb-ot-layout.cc
A documentation clarification and a case of confusing formatting.
> Minor fixes

- src/hb-array.hh
- src/hb-map.hh
- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gsubgpos.hh
- src/hb-ot-layout.cc
- src/hb-serialize.hh
- src/hb-set.hh
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
- src/test-map.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/3293
Hopefully I haven't made the bot gods angry...
> Hashmap classes

- .circleci/config.yml
- docs/meson.build
- meson.build
- perf/meson.build
- src/meson.build
- test/fuzzing/meson.build
- test/shape/meson.build
- test/subset/meson.build
We implicitly require it for building ragel subproject. This new version requirement should satisfied in both Fedora 33 and Debian bullseye, and not be too cutting edge for us.
> [meson] Require 0.55.0

- meson.build
- src/hb-directwrite.cc
- src/meson.build
- test/shape/data/in-house/meson.build
- test/shape/data/in-house/tests/coretext.tests
- test/shape/data/in-house/tests/directwrite.tests
- test/shape/data/in-house/tests/uniscribe.tests
- test/shape/meson.build
> [tests] Add tests for platform shapers

- src/hb-repacker.hh
- src/test-repacker.cc
Previous priority implementation would move a node further back within it's layer, but at max priority was unable to move any further up than that. This updates the implementation to have 3 priority levels:
1. Distance is reduced by half of table size.
2. Distance is reduced by full table size (move to beginning of the layer).
3. Distance is set to 0. Vertex will be packed as soon as possible.
Also makes the iterative resolutions aware of max priority, so it won't keep trying to raise priority beyond the maximum.
Fixes #3328
> [repacker] Improve vertex priority packing.

- src/hb-ot-shape-fallback.cc
- src/hb-ot-shape-normalize.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/3340
Should add tests ideally.
> Use invisible-glyph for spaces if font has no ASCII space

- docs/harfbuzz-sections.txt
- src/hb-font.cc
- src/hb-font.h
- src/hb-font.hh
- src/hb-ot-layout-gpos-table.hh
- src/hb-ot-metrics.cc
- src/hb-style.cc
New API:
+ hb_font_set_synthetic_slant()
+ hb_font_get_synthetic_slant()
Fixes https://github.com/harfbuzz/harfbuzz/issues/3196
> [font] Add public API for synthetic slant

- docs/harfbuzz-sections.txt
- src/hb-buffer.cc
- src/hb-buffer.h
- src/hb-buffer.hh
- src/hb-ot-layout.hh
- src/hb-ot-shape.cc
- util/shape-options.hh
What I like about this is that it clarifies what's buffer setup and what's buffer content.
Fixes https://github.com/harfbuzz/harfbuzz/issues/1555
> Add `hb_buffer_create_similar()`; use it in util

- src/hb-font.cc
Mention what the effective values are when no coordinates have been set.
> docs: Add some details about coordinates

- configure.ac
- meson.build
- src/hb-common.cc
Supersedes https://github.com/harfbuzz/harfbuzz/pull/3357
> Fix unintentional locale dependency

- src/hb-font.cc
Make it explicit that the variations setters replace all existing variations, even if  not all axes are included in the provided values.
> Another small doc additions

- docs/usermanual-object-model.xml
Mention readonly/immutable in the object-model section.
> Small doc additions

- src/hb-repacker.hh
- src/hb-vector.hh
This finishes automatic item allocation / destruction and rest of move semantics.
Two tests are failing, in repacker. @garretrieger can you take a look please? Your fini_deep's should be replaced with just fini() if nothing else, but that wasn't enough in my testing.
> [vector] Automatic item allocation / destruction

- .github/workflows/configs-ci.yml
Fixes https://github.com/harfbuzz/harfbuzz/issues/2884
> [ci] Add configs-ci.yml to test different configs

- src/hb-ot-layout.cc
Add some relevant details to the documentation
for this function.
Fixes: #3168
> Improve docs for hb_ot_layout_get_ligature_carets

- src/hb-config.hh
- src/hb-machinery.hh
- src/hb-ot-face-table-list.hh
- src/hb-ot-face.hh
- src/hb-ot-glyf-table.hh
- src/hb-ot-hmtx-table.hh
- src/hb-static.cc
- test/api/Makefile.am
- test/api/hb-test.h
- test/api/meson.build
- test/api/test-be-glyph-advance.c
- test/api/test-be-num-glyphs.c
These implement https://github.com/be-fonts/boring-expansion-spec/issues/
Starts with the >64k glyph limit.
> [Boring Expansion] >64k loca & hmtx tables

- docs/harfbuzz-sections.txt
- src/hb-ot-metrics.cc
- src/hb-ot-metrics.h
Add a variant of hb_ot_metrics_get_position that
synthesizes missing values.
New api: hb_ot_metrics_get_position_with_fallback
> [ot-metrics] Synthesize missing metrics

- src/hb-buffer-verify.cc
- src/hb-buffer.h
- src/hb-buffer.hh
- test/shape/data/in-house/tests/unsafe-to-concat.tests
- util/shape-options.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/3454
> [buffer] Add HB_BUFFER_FLAG_PRODUCE_UNSAFE_TO_CONCAT

- meson.build
> [meson] handle multiple element ICU DEFS

- .github/workflows/msvc-ci.yml
This reverts commit c4cf5ddb272cb1c05a572db5b76629368f9054f5.
> Revert "[ci] Downgrade pip on MSVC jobs"

- src/hb-ot-glyf-table.hh
- src/hb-ot-var-gvar-table.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/3506
@khaledhosny can you please add test case with that glyph and --show-extents?
> [gvar] Fix decoding of private points

- docs/features.dot
This adds the GraphViz source to the [Harfbuzz Cheat Sheet](https://twitter.com/simoncozens/status/1422159944732839942/photo/1) I made. It doesn't hook it up to anywhere in the docs yet; I just don't want the code to get lost.
> Add cheat sheet

- .github/workflows/linux-ci.yml
- .github/workflows/macos-ci.yml
Fixes https://github.com/harfbuzz/harfbuzz/issues/3540
> [ci] Pin gcovr to version 5.0

- src/gen-use-table.py
- src/hb-ot-shape-complex-use-table.hh
> [USE] Classify U+10A38 KHAROSHTHI SIGN BAR ABOVE as CONS_MOD_BELOW

- src/hb-ot-layout-common.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/2965
> 32bit varstore

- src/hb-ot-name-table.hh
- test/api/test-ot-name.c
Very rudimentary.
Fixes https://github.com/harfbuzz/harfbuzz/issues/3354
> [name] Implement approximate language matching

- README.md
I copied the text verbatim, but it probably needs to be edited. I’m not sure if there is more to move here.
> Move freedesktop.org/wiki/HarfBuzz to README.md

- src/hb-bit-set-invertible.hh
- src/hb-coretext.cc
- src/hb-ot-var-fvar-table.hh
- src/hb-repacker.hh
- src/hb-subset.cc
- src/hb.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/3656
> Fix clang -Wcomma warnings

- src/hb-map.hh
- src/hb-static.cc
To fix https://github.com/harfbuzz/harfbuzz/issues/3684
> [map] Another try at hiding minus1

- CMakeLists.txt
- configure.ac
- meson.build
- src/hb-directwrite.cc
- src/meson.build
Fixes https://github.com/harfbuzz/harfbuzz/issues/3478
> Load DirectWrite dynamically

- util/hb-subset.cc
> Typo fix in hb-subset

- src/hb-algs.hh
- src/hb-ot-metrics.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/3716
> More -Wcomma fixes

- src/hb-ot-map.cc
- src/hb-ot-map.hh
- src/hb-ot-shaper-arabic.cc
And apply rclt without a pause.
Fixes https://github.com/harfbuzz/harfbuzz/issues/1573
> [arabic] Disable calt if rclt is present

- src/test-repacker.cc
fixes #3768  
(feel free to ignore, i just thought i'd make a fix too ^^)
> [repacker] fix signedness of char in tests

- src/hb-ft.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/3788
https://github.com/harfbuzz/harfbuzz/issues/3790
> [hb-ft] Only apply FT_Face's transform if we created FT_Face

- src/hb-subset-plan.cc
`hb_ot_layout_collect_lookups() `calls `hb_ot_layout_collect_features()`, we don't need to collect features again
> [subset] No need to collect_features twice

- CMakeLists.txt
> [cmake] Generate pkg-config .pc files

- src/hb-subset-plan.cc
If COLR or MATH tables are being dropped, there is no point in closing glyphs over them, just like it is done for GSUB.
> [subset] Skip glyph closure for any dropped table

- src/OT/Layout/GPOS/PairPosFormat2.hh
- src/OT/Layout/GPOS/PairSet.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/3824
> [GPOS.PairPos] Adjust unsafe-to-break for non-zero ValueFormat2

- src/hb-subset-cff-common.hh
~18% improvement for large subset sizes.
BM_subset/subset_glyphs/SourceHanSans-Regular_subset.otf/10000_median                    -0.1794         -0.1796            54            44            54            44
BM_subset/subset_codepoints/SourceHanSans-Regular_subset.otf/10000_median                -0.1807         -0.1809            52            42            52            42
> [subset] use charstrings directly from accelerator cache if mutability isn't needed.

- .github/workflows/msvc-ci.yml
- .github/workflows/msys2-ci.yml
> Windows CI fixes

- .github/workflows/configs-build.yml
- .github/workflows/linux-ci.yml
https://github.com/actions/runner-images/issues/6002
> [ci] Change Linux runner to Ubuntu 20.04

- src/hb-ot-layout-gsubgpos.hh
Speeds up NotoNastaliq/64 subset benchmark by 45%.
> [gsub] Cache intersects_class results for closure

- src/Makefile.am
- src/hb-features.h.in
- src/meson.build
This header has defines for all the optional
dependendencies that come with their own Harfbuzz
headers, so you can do:
#include <hb.h>
#ifdef HB_DIRECTWRITE
#include <hb-directwrite.h>
#endif
> Generate and install hb-config.h

- docs/harfbuzz-sections.txt
- docs/subset-preprocessing.md
- perf/benchmark-subset.cc
- src/gen-def.py
- src/hb-map.hh
- src/hb-subset-input.cc
- src/hb-subset.h
- test/subset/run-tests.py
- util/hb-subset.cc
> [subset] finalize the hb_subset_preprocess API and remove it from experimental.

- src/Makefile.sources
- src/OT/glyf/CompositeGlyph.hh
- src/OT/glyf/Glyph.hh
- src/OT/glyf/VarCompositeGlyph.hh
- src/OT/glyf/composite-iter.hh
- src/OT/glyf/coord-setter.hh
- src/hb-config.hh
- src/hb-open-type.hh
- src/hb-ot-var-gvar-table.hh
Draft prototype of https://github.com/harfbuzz/boring-expansion-spec/blob/glyf1/glyf1.md
> [glyf] VariableComposites

- src/hb-ot-color-colr-table.hh
> COLRv1: Revamp extents variation

- subprojects/freetype2.wrap
- subprojects/zlib.wrap
Use the one from WrapDB and add zlib wrap because current FreeType tarball misses it.
> [meson] Update freetype2 wrap

- src/hb-deprecated.h
- src/hb-graphite2.h
- src/hb-ot-deprecated.h
See https://github.com/harfbuzz/harfbuzz/issues/3957#issuecomment-1356890525
> [doc] Workaround gtk-doc limitation with HB_DEPRECATED_FOR

- src/hb-subset.cc
> [subset] Don't gate access to the table repacker.

- .github/workflows/msys2-ci.yml
- docs/meson.build
> [doc] Don’t automatically skip building docs on Windows

- src/hb-ft.cc
Spell out what fonts hb_ft_font_get_face() works with.
See https://github.com/harfbuzz/harfbuzz/issues/3984
> [ft] Clarify docs

- test/api/Makefile.am
- test/api/meson.build
- test/api/test-coretext.c
- test/api/test-ft.c
Here are a few tests for what I would consider the mvp level for the native api.
> Test native api

- test/api/results/bad-154
- test/api/results/hand-10
- test/api/results/hand-10.2
- test/api/results/rocher-1
- test/api/results/rocher-2
- test/api/results/rocher-3
- test/api/results/test-10
- test/api/results/test-106
- test/api/results/test-116
- test/api/results/test-123
- test/api/results/test-165
- test/api/results/test-175
- test/api/results/test-6
- test/api/results/test-92
- test/api/test-paint.c
These tests compare the output of the ft and ot
implementations for all the glyphs in the test_glyphs font.
> Add more paint tests

- subprojects/zlib.wrap
- test/api/results/bad-154
- test/api/results/test-154
- test/api/results/testvf-154
Hopefully this fixes the intermittent CI failures due to download failures.
> [wrap] Add fallback source URL for zlib

- meson.build
Include builtin font callbacks and Cairo integration in the configuration summary.
> Update meson summary

- meson.build
Similar to what we do with FreeType ones.
> [meson] Enable all checked for Cairo functions for internal Cairo

- src/hb-ot-layout.cc
Continuation of da7b66c1f8bbf7147f8113.
> [layout] Optimize more buffer message calls

- src/OT/glyf/SimpleGlyph.hh
- src/OT/glyf/path-builder.hh
- src/hb-config.hh
https://github.com/harfbuzz/boring-expansion-spec/issues/41
> [glyf] Support cubic curves

- src/hb-atomic.hh
Fixes https://github.com/harfbuzz/harfbuzz/pull/4119
> [atomic] Use no-op asm for compiler barrier

- src/hb-algs.hh
- src/hb.hh
https://github.com/harfbuzz/harfbuzz/issues/4066#issuecomment-1439510188
> Use __has_builtin for builtin checks instead of compiler versions

- src/OT/glyf/CompositeGlyph.hh
- src/OT/glyf/Glyph.hh
- src/OT/glyf/SimpleGlyph.hh
- src/OT/glyf/VarCompositeGlyph.hh
- src/hb-ot-var-gvar-table.hh
Try to load composite glyphs in-place.  I don't think I broke anything.
> Glyf inplace

- docs/usermanual-getting-started.xml
Guess is probably better than hard-coding latin/ltr if you aren't sure it will always be true.
> Help noobs who don't know their segment properties

- src/OT/glyf/Glyph.hh
- src/hb-algs.hh
- src/hb-array.hh
- src/hb-bit-page.hh
- src/hb-bit-set.hh
- src/hb-cairo-utils.cc
- src/hb-map.hh
Towards fixing https://github.com/harfbuzz/harfbuzz/issues/4227
> Better hash

- docs/harfbuzz-sections.txt
- src/Makefile.sources
- src/OT/glyf/glyf.hh
- src/gen-def.py
- src/hb-ot-layout-common.hh
- src/hb-ot-os2-table.hh
- src/hb-ot-post-table.hh
- src/hb-ot-stat-table.hh
- src/hb-ot-var-fvar-table.hh
- src/hb-subset-input.cc
- src/hb-subset-input.hh
- src/hb-subset-instancer-solver.cc
- src/hb-subset-instancer-solver.hh
- src/hb-subset-plan-member-list.hh
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
- src/hb-subset.h
- src/meson.build
Update internal data structures and do not break existing tests.
Add an experimental API hb_subset_input_set_axis_range (). It will be needed in command line parsing.
No tests are added for STAT/fvar/collecting FeatureVariationRecords changes yet.
> [instancer] update internal hashmaps to use Triple for axes positions

- src/Makefile.am
- src/hb-subset-instancer-solver.cc
- src/meson.build
- src/test-subset-instancer-solver.cc
Also fix bug in the solver code
> [instancer] add tests for instancer-solver from python test suite

- src/hb-algs.hh
- src/hb-map.hh
This inlines some map functionality without changing it much. Needs some benchmarking. Reduces code size a bit.
> Inlined map

- src/hb-subset-instancer-solver.cc
- src/test-subset-instancer-solver.cc
> [instancer-solver] port solver fix from fonttools

- perf/benchmark-subset.cc
retain gids is a more interesting case than no hinting for performance.
> [subset] in subset benchmarks switch nohinting with retaingids.

- src/hb-ot-hmtx-table.hh
Make serializer allocation up front to avoid bounds checking overhead for each metric.
Benchmarks:
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/10_median                   -0.1005         -0.1005             0             0             0             0
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/64_median                   -0.0693         -0.0692             0             0             0             0
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/512_median                  -0.0294         -0.0293             1             1             1             1
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/4096_median                 -0.0033         -0.0032             3             3             3             3 …
> [subset] Optimize hmtx/vmtx serialization.

- src/OT/glyf/glyf.hh
Shows 33% speedup on Mplus/retaingid/10 benchmark:
Benchmark                                                                   Time             CPU      Time Old      Time New       CPU Old       CPU New
--------------------------------------------------------------------------------------------------------------------------------------------------------
BM_subset/subset_glyphs/Mplus1p-Regular.ttf/retaingids/10                -0.3296         -0.3294             0             0             0             0
> [subset/glyf] Don't allocate empty SubsetGlyf's

- src/test-subset-instancer-solver.cc
> [instancer-solver] add tests for instancer-solver crossing calculation fix

- meson.build
> [meson] Remove incorrect option for ICU subproject

- src/meson.build
> [GI] Passing both libharfbuzz_gobject and libharfbuzz as positional parameters

- src/hb-graphite2.cc
- src/wasm/graphite/shape.cc
Based on https://github.com/harfbuzz/harfbuzz/issues/4309#issuecomment-1624730406
Fixes https://github.com/harfbuzz/harfbuzz/issues/4309
> [graphite] Fix cluster advance width

- src/hb-ot-layout-common.hh
- src/hb-ot-var-common.hh
- src/hb-ot-var-cvar-table.hh
- src/hb-ot-var-fvar-table.hh
- src/hb-subset-instancer-solver.cc
- src/hb-subset-instancer-solver.hh
- src/hb-subset-plan-member-list.hh
- src/hb-subset-plan.cc
- src/test-subset-instancer-solver.cc
- src/test-tuple-varstore.cc
This is for #4290 , avar fix will be added later, currently we don't have code for avar yet.
> port instancer solver normalizeValue fixes from fonttools

- src/hb-ot-layout-common.hh
- src/hb-ot-var-cvar-table.hh
- src/hb-subset-plan.cc
1. fix a memory leak in cvar subset()
2. store actual float value in normalized axes_location map rather than F2DOT14 int value
> instancer bug fixes

- src/hb-ot-var-avar-table.hh
- src/hb-ot-var-common.hh
- src/hb-ot-var-fvar-table.hh
- src/hb-subset-input.cc
- src/hb-subset.cc
- avar code changes addressed issues in #4290 
- I'll add a full test once I'm done with gvar code.
> [instancer] support avar table, fix issues in STAT/fvar tables

- src/hb-ot-shape.cc
- test/shape/data/in-house/tests/automatic-fractions.tests
Reverts harfbuzz/harfbuzz#4350
> Revert "Require numerators and denominators in automatic fractions"

- meson.build
- meson_options.txt
- src/Makefile.am
- src/harfbuzz-config.cmake.in
- src/meson.build
- src/relative_to.py
Please test (@sapiippo), it looks to me like it now generates relocatable paths in all cases but I only have NixOS so I can't test your sysroot problem :)
Closes #4025.
> Re-do and clean up CMake support, making it use relocatable paths

- src/hb-ot-layout-common.hh
> [instancer] fix delta_row_encoding_t constructor

- src/hb-ot-layout-common.hh
> [instancer] fix compile warnings

- src/hb-common.cc
> Check for closing quote in parse_tag

- src/OT/Layout/GPOS/AnchorMatrix.hh
- src/OT/Layout/GPOS/CursivePosFormat1.hh
- src/OT/Layout/GPOS/PairPosFormat2.hh
- src/OT/Layout/GPOS/PairSet.hh
- src/OT/Layout/GPOS/PairValueRecord.hh
- src/OT/Layout/GPOS/SinglePosFormat1.hh
- src/OT/Layout/GPOS/SinglePosFormat2.hh
- src/OT/Layout/GPOS/ValueFormat.hh
- src/OT/Layout/types.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-open-type.hh
Playing with adding type information to `base` arguments when it's non-trivial.
> Typed offsets

- meson.build
- fix meson has_function() detection, needs suitable include to avoid false positive (see [1] for details)
[1] https://github.com/mesonbuild/meson/issues/7652
Closes #4266
> [meson] has_function detection needs suitable includes

- src/hb-cff-interp-dict-common.hh
- src/hb-ot-cff-common.hh
- src/hb-ot-cff1-table.hh
- src/hb-ot-cff2-table.hh
This is a little bit brittle as I don't know if I got all the offsets or not (quite possibly not). But otherwise seems to work.
> CFF negative offset

- src/hb-repacker.hh
Found an example font that needs the higher limit.
> [repacker] Increase repacker max rounds to 30.

- src/hb-ot-math-table.hh
- test/api/test-ot-math.c
> [ot-math-table] fix a bug in MathKern::get_value()

- src/hb-ot-math-table.hh
> [ot-math] simplify MathKern::get_value()

- .ci/requirements.in
- .ci/requirements.txt
Reverts harfbuzz/harfbuzz#4603
> Revert "Bump gcovr from 5.0 to 7.2 in /.ci"

- meson.build
See: https://github.com/harfbuzz/harfbuzz/issues/4626
> Fixed: hb-subset.cc -- compile error C1128 on MSVC

- docs/harfbuzz-sections.txt
- src/hb-buffer.cc
- src/hb-buffer.h
- src/hb-buffer.hh
- src/hb-ot-layout-gsubgpos.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/4620
New API:
+hb_buffer_set_random_state()
+hb_buffer_get_random_state()
> [buffer] Add API for random state

- .circleci/config.yml
- util/Makefile.am
> Add test-hb-subset-parsing.c to extra dist. Needed for meson compile w/ experimental api.

- CMakeLists.txt
> Fix for #4395

- src/hb-repacker.hh
In rare cases a subsetting operation may have expanded the non-extension space data enough to make it unable to be repacked. So if we encounter a case that does not repack successfully retry the operation with extension promotion recalculation enabled.
We don't do extension promotion by default since it's rarely needed and it will slow down repacking + increase the repacking size when enabled and not needed.
> [subset] If repacking fails for GSUB/GPOS retry with extension promotion.

- src/hb-aat-layout-common.hh
- src/hb-aat-layout-kerx-table.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-aat-layout.cc
- src/hb-ot-face-table-list.hh
- src/hb-ot-face.cc
- src/hb-ot-kern-table.hh
- src/hb-ot-layout-gsubgpos.hh
- src/hb-ot-layout.cc
- src/hb-set-digest.hh
Still not cached in an accelerator, but shows up promising results.
> [aat] Use set digest to speed up

- meson.build
Fixes:
https://github.com/harfbuzz/harfbuzz/issues/4671
> meson: set -std=c++17 when building with icu >= 75

- src/hb-subset-plan.cc
Pulls out commonly repeated pattern of filling the gid and unicode maps into a templated helper.
> [subset] refactor populate_unicodes_to_retain.

- README.md
... because Unreal Engine matters. How else would you get complex-script chat in Fortnite?
> Update README.md to include Unreal Engine

- src/graph/graph.hh
- src/hb-subset-instancer-solver.cc
As just a minor code tweak to clarify the intention better.
> [subset] Use hb_clamp instead of consequent hb_min and hb_max calls

- docs/wasm-shaper.md
> Update wasm-shaper.md with link to examples.

- src/hb-aat-layout-common.hh
- src/hb-aat-layout-just-table.hh
- src/hb-aat-layout-opbd-table.hh
- src/hb-open-file.hh
- src/hb-ot-cff-common.hh
- src/hb-ot-cff1-table.hh
- src/hb-ot-cff2-table.hh
- src/hb-ot-cmap-table.hh
- src/hb-ot-kern-table.hh
- src/hb-ot-layout-base-table.hh
- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gsubgpos.hh
- src/hb-ot-stat-table.hh
https://github.com/harfbuzz/harfbuzz/pull/4864#issuecomment-2366923736
> Add hb_barrier() to switches of unions

- util/helper-cairo.hh
Works around a Firefox bug.
Fixes https://github.com/harfbuzz/harfbuzz/issues/4811
> [hb-view] Simplify background drawing

- util/helper-cairo.hh
Can be handy for debugging the series of operations cairo performs.
> [util] Support cairo script as output format

- src/hb-aat-layout-morx-table.hh
- test/shape/data/in-house/tests/macos.tests
> Geezapro fix

- perf/meson.build
Fixes https://github.com/harfbuzz/harfbuzz/issues/4896
> [perf] Simplify meson.build

- .github/workflows/macos-ci.yml
The packages are in conflict again, try to remove pkg-config this time and use pkgconf.
> [ci] Try to fix homebrew pkg-config/pkgconf mess

- src/hb-aat-layout-common.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-atomic.hh
Speeds up Times.ttc benchmark by 27%.
> [aat] Add a class-cache to the machine & fix speed regression from 2023!

- src/hb-aat-layout-common.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-bit-page.hh
- src/hb-bit-set-invertible.hh
- src/hb-bit-set.hh
- src/hb-buffer.hh
- src/hb-ot-layout.cc
- src/hb-set-digest.hh
- src/hb-set.hh
Another 12% speedup with LucidaGrande.
> [aat] Speed up subchain skipping using exact sets

- src/OT/Layout/Common/Coverage.hh
- src/OT/Layout/Common/CoverageFormat1.hh
- src/OT/Layout/Common/CoverageFormat2.hh
- src/OT/Layout/GPOS/PairPosFormat1.hh
- src/OT/Layout/GPOS/PairPosFormat2.hh
- src/OT/Layout/types.hh
- src/hb-ot-layout-common.hh
- src/hb-ot-layout-gsubgpos.hh
10% speedup on Roboto-Regular. 5% on SF Pro.
> [OT] PairPos cache

- src/hb-coretext-font.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/5056
> [coretext-font] Support non-BMP characters

- src/hb-coretext-shape.cc
- test/api/test-coretext.c
https://github.com/harfbuzz/harfbuzz/issues/3159#issuecomment-2652262262
Just some Copilot code. Untested.
> [coretext] Copy variations when creating hb-font

- src/hb.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/5080
> Annotate printf functions with gnu_printf format under MingW

- docs/harfbuzz-sections.txt
- src/hb-directwrite.cc
- src/hb-directwrite.h
- test/api/test-directwrite.cc
https://github.com/harfbuzz/harfbuzz/pull/5079#pullrequestreview-2627407692
> [directwrite] Rename font_get_font to font_get_dw_font

- src/hb-directwrite.cc
https://github.com/harfbuzz/harfbuzz/pull/5079#issuecomment-2673805310
> [directwrite] Fix -Wcast-align warning

- docs/harfbuzz-sections.txt
- src/hb-directwrite.cc
- src/hb-directwrite.h
- src/hb-ft.cc
- src/hb-ft.h
- test/api/test-ft.c
- util/helper-cairo-ft.hh
> Rename and deprecate `hb_directwrite_face_get_font_face`, `hb_ft_font_get_face`

- src/OT/Var/VARC/VARC.cc
- src/OT/Var/VARC/VARC.hh
- src/OT/glyf/glyf.hh
- src/hb-geometry.hh
- src/hb-ot-cff2-table.cc
- src/hb-ot-cff2-table.hh
- src/hb-ot-font.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/5007
Untested.
> [`VARC`] Implement get_extents()

- .circleci/config.yml
- meson.build
This reverts commit 958e2c533118516d21c0ad1561e7fb000b8ea8f1.
> Reapply "[meson] Add buildtype=debugoptimize by default"

- src/hb.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/5106
> Use gnu_printf format annotation under MingW with GCC only

- .github/workflows/fontations.yml
- meson.build
- src/check-symbols.py
- src/fontations/Cargo.toml
- src/fontations/lib.rs
- src/fontations/meson.build
- src/meson.build
libharfbuzz.so .text size:
- Without fontations: 1.4mb
- With fontations:
- before: 4.7mb
- after: 1.7mb
> Fontations shrink

- docs/harfbuzz-sections.txt
- perf/benchmark-font.cc
- perf/hb-benchmark.hh
- src/fontations/Cargo.toml
- src/fontations/meson.build
- src/hb-atomic.hh
- src/hb-face.cc
- src/hb-face.h
- src/hb-font.cc
- src/hb-font.h
- src/hb-font.hh
- src/hb-ft.cc
- src/hb-shape.cc
- test/api/test-draw.c
- test/api/test-multithread.c
- test/api/test-ot-extents-cff.c
- test/api/test-ot-face.c
- test/api/test-ot-metrics-tt-var.c
- test/fuzzing/hb-shape-fuzzer.cc
- test/shape/data/aots/hb-aots-tester.cpp
- test/threads/hb-shape-threads.cc
- util/face-options.hh
- util/font-options.hh
For now:
+ hb_font_set_funcs_using()
+ hb_font_list_funcs()
Part of https://github.com/harfbuzz/harfbuzz/issues/5117
> Add API for querying font-funcs / face-loaders and setting them using strings

- src/hb-aat-layout-common.hh
- src/hb-aat-layout-morx-table.hh
- src/hb-aat-layout.cc
- src/hb-aat-layout.hh
- src/hb-ot-shape.cc
- test/shape/data/in-house/tests/aat-morx.tests
Fixes https://github.com/harfbuzz/harfbuzz/discussions/5118
Fixed a few missing property settings as well while in there.
> [AAT] Clean up deleted-glyph handling

- src/fontations/lib.rs
Let's see what tsan thinks... I also have not profiled this.
It also doesn't hold the mutex for the whole use time. It probably should or bad things might happen.
> [fontations] Check for font serial change automatically

- src/hb-aat-layout-common.hh
- src/hb-aat-layout.cc
- src/hb-ot-layout.hh
Should address:
https://github.com/harfbuzz/harfbuzz/pull/5119#issuecomment-2709170388
> [aat/morx] Use a separate bit for deleted-glyphs

- docs/harfbuzz-sections.txt
- src/hb-coretext-shape.cc
- src/hb-coretext.h
- src/hb-face.cc
- src/hb-face.h
- src/hb-font.cc
- src/hb-ft.cc
- src/hb-ft.h
- test/api/hb-test.h
- test/api/meson.build
- test/api/test-face.c
Fixes https://github.com/harfbuzz/harfbuzz/issues/5117
Untested.
New API:
+hb_face_create_or_fail_using()
+hb_ft_face_create_from_blob_or_fail()
+hb_coretext_face_create_from_blob_or_fail()
> Add hb_ft_face_create_from_blob_or_fail() et al

- docs/harfbuzz-sections.txt
- src/OT/Color/COLR/COLR.hh
- src/fontations/lib.rs
- src/hb-ft-colr.hh
- src/hb-paint.cc
- src/hb-paint.h
- src/hb-paint.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/5146
> [paint] Add push_font_transform() / push_inverse_font_transform()

- docs/harfbuzz-sections.txt
- src/harfbuzz.cc
- src/hb-coretext-font.cc
- src/hb-directwrite-font.cc
- src/hb-directwrite.cc
- src/hb-directwrite.h
- src/hb-font.cc
- src/hb-ft.cc
- src/meson.build
Fixes https://github.com/harfbuzz/harfbuzz/issues/5143 eventually.
> [directwrite] Add fontfuncs

- src/hb-coretext-shape.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/5142
> [coretext] Always set all variation axes

- .ci/build-win.sh
Move install dir inside build dir.
> [ci] Massage cross-win building

- src/hb-coretext-shape.cc
Seems to fix https://github.com/harfbuzz/harfbuzz/issues/5163
> [coretext] Only try setting variations if a variable font

- CMakeLists.txt
FT_Get_Transform check was missing in the cmake'ry.
> cmake: add missing FT_Get_Transform check

- src/hb-directwrite-shape.cc
- src/hb-directwrite.cc
- test/shape/data/in-house/tests/directwrite.tests
> [directwrite] Copy font variations when shaping

- src/fontations/Cargo.lock
- src/fontations/Cargo.toml
- src/fontations/lib.rs
One font is failing. I assume hb rejects the post table completely
while fontations partially uses it.
Also, for another font, fontations is returning Some("") for a all glyphs in the font. So I had special code to return false in that case as well. Probably something that needs fixing in fontations. @dfrg
> Fontations glyph name

- src/fontations/lib.rs
Gets rid of one Vec.
Supersedes:
https://github.com/harfbuzz/harfbuzz/pull/5180
https://github.com/harfbuzz/harfbuzz/pull/5184
> [fontations] Implement fill-glyph

- test/fuzzing/run-fuzzer-tests.py
- test/shape/run-tests.py
- test/subset/run-repack-tests.py
- test/subset/run-tests.py
It's not working for me though. Meson doesn't seem to set WINEPATH during testing.
> [test] Respect MESON_EXE_WRAPPER in more test runners

- src/hb-coretext-font.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/5173
> [coretext] Make font-funcs respond to font changes

- docs/harfbuzz-sections.txt
- meson_options.txt
- src/hb-directwrite-font.cc
- src/hb-directwrite-shape.cc
- src/hb-directwrite.cc
- src/hb-directwrite.h
- test/api/test-directwrite.cc
- test/shape/run-tests.py
Fixes https://github.com/harfbuzz/harfbuzz/issues/5190
> [directwrite] Clean up API / font handling and make variations work on font-funcs

- meson.build
- src/hb-directwrite.hh
- src/meson.build
Instead of loading at runtime. I just want to see how CI deals with this. Otherwise, not depending on dwrite is probably desired.
> [directwrite] Link to library

- src/fontations/lib.rs
This reverts 852f66a4187f59f169d0de2ea98725d1d78e8da8 in spirit, using a malloc-free implementation and keeping the fill-glyph optimization.
> [fontations] Handle recursive clip-glyphs

- .github/workflows/msys2-ci.yml
See the commits for details. Feedback welcome.
> [ci/msys2] Some minor cleanups

- util/face-options.hh
- util/font-options.hh
- util/main-font-text.hh
- util/options.hh
Need documentation in the help output...
Fixes https://github.com/harfbuzz/harfbuzz/issues/5164
> [util] Return diff values for diff failures

- util/meson.build
- util/options.hh
TODO:
1. Only when docs are enabled?
2. Installdir
3. How to include in release?
Fixes https://github.com/harfbuzz/harfbuzz/issues/5208
> [util] Towards building manpages

- src/hb-font.hh
- src/hb-ft.cc
- src/hb-ot-font.cc
Such that it works on all font-funcs.
> [font] Move outline emboldening to font layer

- src/hb-aat-layout-common.hh
- src/hb-buffer-deserialize-text-glyphs.hh
- src/hb-ot-layout.hh
- src/hb-ot-shape-fallback.cc
- test/shape/data/in-house/tests/fallback-positioning.tests
Fixes https://github.com/harfbuzz/harfbuzz/issues/5232
> Fix AAT deleted glyph marks interaction with fallback mark positioning

- src/hb-ot-cmap-table.hh
- src/hb-ot-font.cc
Much cleaner.
Fixes https://github.com/harfbuzz/harfbuzz/issues/5235
> [cmap] Move cache from face user-data to cmap accelerator

- util/hb-subset.cc
Fixes https://github.com/harfbuzz/harfbuzz/issues/4913
> [subset] Allow options before --font-file

- .circleci/config.yml
- meson.build
- src/meson.build
Fixes https://github.com/harfbuzz/harfbuzz/issues/5261
> [meson] Require 0.60.0

- src/hb-ot-math-table.hh
> [ot-math] Fix build with HB_NO_MATH

- src/hb-subset-plan-layout.cc
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
- src/meson.build
The aim is to reduce the compiled time of hb-subset-plan.cc which on my machine takes almost 30s to compile.
Before: 27s to compile
After: 16s to compile
> [subset] Start splitting layout specific subset plan functionality.

- src/harfbuzz-subset.cc
- src/hb-subset-plan-var.cc
- src/hb-subset-plan.cc
- src/hb-subset-plan.hh
- src/meson.build
Compile times for hb-subset-plan.cc go from 16s -> 13s.
> [subset] Split subset plan variations function into separate file.

- src/check-symbols.py
Fixes https://github.com/harfbuzz/harfbuzz/issues/5287
> [check-symbols] Ignore another rust symbol

- src/hb.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/5290
> [atexit] Fix extra semicolon

- src/check-c-linkage-decls.py
- src/check-externs.py
- src/check-header-guards.py
- src/check-includes.py
- src/check-libstdc++.py
- src/check-static-inits.py
- src/check-symbols.py
- src/meson.build
> Cleanup check-*.py scripts

- src/hb-harfruzz.cc
- src/rust/Cargo.lock
- src/rust/Cargo.toml
- src/rust/shape.rs
From https://github.com/harfbuzz/harfruzz/pull/57
> [harfruzz] Update to new API

- src/rust/shape.rs
> [harfruzz] Set point_size

- src/rust/Cargo.toml
- src/rust/font.rs
Fixes https://github.com/harfbuzz/harfbuzz/issues/5384
> [fontations] Cache glyph_from_names hashmap on the face

- src/hb-face.cc
- src/hb-font.cc
- src/hb-ot-shaper-arabic.cc
- src/hb-ot-shaper-thai.cc
move this symbol out of the .data section
> const up modifier_combining_marks

- src/OT/Layout/GPOS/AnchorFormat3.hh
- src/hb-ot-layout-common.hh
> [subset] AnchorFormat3: better check for when should downgrade to format1

- .github/workflows/linux.yml
- meson.build
- meson_options.txt
- src/hb-debug.hh
- src/hb-kbts.cc
- src/meson.build
- subprojects/.gitignore
- subprojects/kbts.wrap
- subprojects/packagefiles/kbts/meson.build
- test/shape/data/in-house/meson.build
- test/shape/data/in-house/tests/kbts.tests
Uses https://github.com/JimmyLefevre/kb. For testing.
> Add kbts shaper

- perf/benchmark-font.cc
- perf/benchmark-shape.cc
- perf/hb-benchmark.hh
- perf/meson.build
Over time I'll add more options. But this is a good start.
> [perf] Use GOption

- src/hb-machinery.hh
Might not fix https://github.com/harfbuzz/harfbuzz/issues/5429 but I was inspecting there and looks relevant.
> Try to fix build on gcc-8

- src/rust/shape.rs
lol. That's how desperate we are now.
> [harfrust] Remove one function call

- src/OT/Layout/GSUB/Ligature.hh
- src/hb-ot-layout-gsubgpos.hh
Slight speedup on NotoNastaliq.
> Increase match_positions stack allocation from 4 to 8

- src/OT/Layout/GPOS/PairPosFormat1.hh
- src/OT/Layout/GPOS/PairPosFormat2.hh
- src/OT/Layout/GSUB/LigatureSubstFormat1.hh
- src/hb-ot-layout-gsubgpos.hh
> [external_cache] Remove a conditional

- util/helper-subset.hh
- util/meson.build
> [util] Don't specify helper-subset.hh

- src/hb-buffer-verify.cc
- src/hb-buffer.cc
- src/hb-buffer.hh
- src/hb-limits.hh
- src/hb-ot-layout-gsubgpos.hh
- src/hb-ot-shape.cc
- src/hb-shape.cc
> Remove duplicate buffer->leave call

- src/hb-harfrust.cc
https://github.com/harfbuzz/harfrust/issues/205
> [harfrust] Encode pre-context in the correct order

- src/hb-aat-layout-common.hh
> [aat] Implement collect_glyphs_filtered for LookupFormat10

- src/hb-aat-layout-common.hh
> [aat] Clear cached buffer glyph set

- src/hb-buffer.cc
- src/hb-buffer.hh
Should fix a fuzzer-found issue, now that we have increased most buffer limits.
> [buffer] Add some buffer op accounting to a few methods

- src/hb-algs.hh
Fixes https://github.com/harfbuzz/harfbuzz/issues/5456
> On gcc <= 12 don't use num fast path

- src/hb.hh
I suspect a gcc false positive.
"Fixes" https://github.com/harfbuzz/harfbuzz/issues/5589
> [pragmas] Demote -Wuninitialized from error to warning
